/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AccountMfaPolicyRole = typeof AccountMfaPolicyRole[keyof typeof AccountMfaPolicyRole];


export const AccountMfaPolicyRole = {
  owner: 'owner',
  manager: 'manager',
  dispatch: 'dispatch',
  sales: 'sales',
  finance: 'finance',
  crew: 'crew',
  client: 'client',
} as const;
