/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AccountMfaPolicyRole } from './accountMfaPolicyRole';

export interface AccountMfaPolicy {
  id: string;
  name: string;
  email: string;
  role: AccountMfaPolicyRole;
  /** Whether this account is required to complete MFA before protected dashboard access. */
  mfaRequired: boolean;
}
