/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementCostPayload } from './agreementCostPayload';
import type { AgreementMsaPayload } from './agreementMsaPayload';
import type { AgreementPackagePayload } from './agreementPackagePayload';
import type { AgreementScopePayload } from './agreementScopePayload';

export type AgreementTemplatePayload = AgreementMsaPayload | AgreementScopePayload | AgreementCostPayload | AgreementPackagePayload;
