/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface AgreementPreparationRetryPreview {
  /** @minimum 1 */
  revision: number;
  /** @pattern ^[0-9a-f]{64}$ */
  eligibilityFingerprint: string;
  eligible: boolean;
  alreadyPrepared: boolean;
  /** @nullable */
  reasonCode: string | null;
  /** @nullable */
  sourceReceipt: string | null;
  /** @minimum 1 */
  nextRetryEpoch: number;
}
