/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementActivationPreviewBillingMode } from './agreementActivationPreviewBillingMode';
import type { AgreementPeriod } from './agreementPeriod';

export interface AgreementActivationPreview {
  agreementId: string;
  /** @exclusiveMinimum 0 */
  version: number;
  startsOn: string;
  endsOn: string;
  billingMode: AgreementActivationPreviewBillingMode;
  /** @minimum 0 */
  approvedCents: number;
  /** @minimum 0 */
  billedCents: number;
  /** @minimum 0 */
  remainingCents: number;
  plannedCents: number | null;
  perVisitCents: number | null;
  periods: AgreementPeriod[];
  canActivate: boolean;
  blockedReasons: string[];
}
