/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementCostPayloadItemsItemBasis } from './agreementCostPayloadItemsItemBasis';

export type AgreementCostPayloadItemsItem = {
  id: string;
  description: string;
  unit: string;
  /**
     * @minimum 0
     * @maximum 1000000
     * @exclusiveMinimum true
     */
  quantity: number;
  /**
     * @minimum 0
     * @maximum 10000000000
     */
  unitPriceCents: number;
  basis: AgreementCostPayloadItemsItemBasis;
};
