/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftContent } from './agreementDraftContent';
import type { AgreementDraftPreview } from './agreementDraftPreview';
import type { AgreementDraftTemplateReviewSectionsItem } from './agreementDraftTemplateReviewSectionsItem';
import type { AgreementDraftTemplateSource } from './agreementDraftTemplateSource';

export interface AgreementDraftTemplateReview {
  draftId: string;
  /** @minimum 1 */
  expectedVersion: number;
  reviewToken: string;
  /**
     * @minItems 1
     * @maxItems 4
     */
  sections: AgreementDraftTemplateReviewSectionsItem[];
  before: AgreementDraftContent;
  after: AgreementDraftContent;
  preview: AgreementDraftPreview;
  sources: AgreementDraftTemplateSource[];
}
