/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementChargeFinancialSnapshotAgreement } from './agreementChargeFinancialSnapshotAgreement';
import type { AgreementChargeFinancialSnapshotCharge } from './agreementChargeFinancialSnapshotCharge';
import type { AgreementChargeFinancialSnapshotDraft } from './agreementChargeFinancialSnapshotDraft';

export interface AgreementChargeFinancialSnapshot {
  agreement: AgreementChargeFinancialSnapshotAgreement;
  charge: AgreementChargeFinancialSnapshotCharge;
  draft: AgreementChargeFinancialSnapshotDraft;
}
