/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftPricingPlanAllocationsItem } from './agreementDraftPricingPlanAllocationsItem';
import type { AgreementDraftPricingPlanSchemaVersion } from './agreementDraftPricingPlanSchemaVersion';
import type { AgreementDraftPricingReview } from './agreementDraftPricingReview';

export interface AgreementDraftPricingPlan {
  schemaVersion: AgreementDraftPricingPlanSchemaVersion;
  /** @minimum 1 */
  sourceVersion: number;
  /** @maxItems 3 */
  allocations: AgreementDraftPricingPlanAllocationsItem[];
  review: AgreementDraftPricingReview;
}
