/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementChargeReviewReceiptOutcome } from './agreementChargeReviewReceiptOutcome';

export interface AgreementChargeReviewReceipt {
  eventId: string;
  chargeId: string;
  /** @minimum 1 */
  reviewVersion: number;
  outcome: AgreementChargeReviewReceiptOutcome;
  recordedAt: string;
}
