/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftPricingReviewAllocationsItemBasis } from './agreementDraftPricingReviewAllocationsItemBasis';
import type { AgreementPricingPeriod } from './agreementPricingPeriod';

export type AgreementDraftPricingReviewAllocationsItem = {
  basis: AgreementDraftPricingReviewAllocationsItemBasis;
  /**
     * @minItems 1
     * @maxItems 200
     */
  scopeRowIds: string[];
  costRowIds: string[];
  rateCents: number;
  maximumVisits: number | null;
  periods: AgreementPricingPeriod[];
  authorizedAmountCents: number | null;
};
