/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface AgreementPreparationScanHealth {
  family: string;
  phase: string;
  /** @nullable */
  last_progress_at: string | null;
  /** @nullable */
  last_completed_at: string | null;
  /** @nullable */
  last_error_code: string | null;
}
