/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface AgreementChargePreview {
  agreementId: string;
  sourceKey: string;
  /** @exclusiveMinimum 0 */
  amountCents: number;
  alreadyPrepared: boolean;
  billingDraftId: string | null;
  /** @minimum 0 */
  approvedCents: number;
  /** @minimum 0 */
  billedCents: number;
  /** @minimum 0 */
  remainingCents: number;
}
