/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementRecurrenceOptionBillingMode } from './agreementRecurrenceOptionBillingMode';

/**
 * Selected fields from the existing operational snapshot; other persisted fields may be present.
 */
export interface AgreementRecurrenceOption {
  id: string;
  property_id: string;
  title: string;
  billing_mode: AgreementRecurrenceOptionBillingMode;
  property_name: string;
  [key: string]: unknown;
 }
