/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementEstimateOptionStatus } from './agreementEstimateOptionStatus';

/**
 * Selected fields from the existing operational snapshot; other persisted fields may be present.
 */
export interface AgreementEstimateOption {
  id: string;
  property_id: string;
  title: string;
  scope: string;
  revision: number;
  amount_cents: string;
  status: AgreementEstimateOptionStatus;
  property_name: string;
  [key: string]: unknown;
 }
