/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftContent } from './agreementDraftContent';
import type { AgreementDraftContextSnapshot } from './agreementDraftContextSnapshot';
import type { AgreementDraftDates } from './agreementDraftDates';
import type { AgreementDraftPreview } from './agreementDraftPreview';
import type { AgreementDraftPricingPlan } from './agreementDraftPricingPlan';
import type { AgreementDraftStatus } from './agreementDraftStatus';
import type { AgreementDraftTemplateSource } from './agreementDraftTemplateSource';

export interface AgreementDraft {
  id: string;
  title: string;
  client_id: string | null;
  property_id: string | null;
  lead_id: string | null;
  status: AgreementDraftStatus;
  /** @minimum 1 */
  version: number;
  created_at: string;
  updated_at: string;
  source_estimate_id: string | null;
  estimate_id: string | null;
  content: AgreementDraftContent;
  dates: AgreementDraftDates;
  source_templates: AgreementDraftTemplateSource[];
  context_snapshot: AgreementDraftContextSnapshot;
  created_by: string;
  preview: AgreementDraftPreview;
  pricing_plan?: AgreementDraftPricingPlan | null;
  /** @nullable */
  revises_estimate_id?: string | null;
  /** @nullable */
  change_order_estimate_id?: string | null;
  /**
     * @minimum 1
     * @nullable
     */
  revises_estimate_revision?: number | null;
}
