/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface AgreementChargeReceipt {
  id: string;
  agreementId: string;
  billingDraftId: string;
  sourceKey: string;
  /**
     * @maximum 10000000000
     * @exclusiveMinimum 0
     */
  amountCents: number;
}
