/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AgreementChargeFinancialSnapshotDraft = {
  id: string;
  propertyId: string;
  /** @nullable */
  estimateId: string | null;
  title: string;
  kind: string;
  /** @minimum 0 */
  amountCents: number;
  status: string;
  /** @nullable */
  postingRequestId: string | null;
  /** @nullable */
  postingPayloadSha256: string | null;
  /** @nullable */
  quickbooksId: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  balanceCents: number | null;
  ownershipVerified: boolean;
};
