/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementChargeReviewInputOutcome } from './agreementChargeReviewInputOutcome';

export interface AgreementChargeReviewInput {
  /** @minimum 0 */
  expectedReviewVersion: number;
  /** @minimum 1 */
  cancellationVersion: number;
  /** @pattern ^[0-9a-f]{64}$ */
  snapshotSha256: string;
  outcome: AgreementChargeReviewInputOutcome;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  reason: string;
}
