/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftSummaryStatus } from './agreementDraftSummaryStatus';

export interface AgreementDraftSummary {
  id: string;
  title: string;
  client_id: string | null;
  property_id: string | null;
  lead_id: string | null;
  status: AgreementDraftSummaryStatus;
  /** @minimum 1 */
  version: number;
  created_at: string;
  updated_at: string;
}
