/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AgreementChargeHistoryItemReviewState = typeof AgreementChargeHistoryItemReviewState[keyof typeof AgreementChargeHistoryItemReviewState];


export const AgreementChargeHistoryItemReviewState = {
  unreviewed: 'unreviewed',
  kept_due: 'kept_due',
  correction_required: 'correction_required',
  stale_review: 'stale_review',
} as const;
