/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPricingPeriod } from './agreementPricingPeriod';

export type AgreementDraftPricingPlanAllocationsItem = {
  basis: 'one_time';
  /**
     * @minItems 1
     * @maxItems 200
     */
  scopeRowIds: string[];
} | {
  basis: 'fixed_monthly';
  /**
     * @minItems 1
     * @maxItems 200
     */
  scopeRowIds: string[];
  /** @maxItems 120 */
  periods: AgreementPricingPeriod[];
} | {
  basis: 'per_visit';
  /**
     * @minItems 1
     * @maxItems 200
     */
  scopeRowIds: string[];
  /**
     * @minimum 1
     * @maximum 10000
     */
  maximumVisits: number;
};
