/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AgreementChargeQueueItemState = typeof AgreementChargeQueueItemState[keyof typeof AgreementChargeQueueItemState];


export const AgreementChargeQueueItemState = {
  ready: 'ready',
  review_required: 'review_required',
  unmatched: 'unmatched',
  unavailable: 'unavailable',
} as const;
