/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementTemplateExportKind } from './agreementTemplateExportKind';
import type { AgreementTemplatePayload } from './agreementTemplatePayload';

export interface AgreementTemplateExport {
  kind: AgreementTemplateExportKind;
  name: string;
  description: string;
  body: string;
  payload: AgreementTemplatePayload;
  sourceVersion: number;
  removedDetails: number;
  resetCostRows: number;
}
