/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementChargeHistoryItemReviewState } from './agreementChargeHistoryItemReviewState';
import type { AgreementChargeReviewReceipt } from './agreementChargeReviewReceipt';

export interface AgreementChargeHistoryItem {
  chargeId: string;
  agreementId: string;
  sourceKey: string;
  createdAt: string;
  /** @minimum 0 */
  amountCents: number;
  billingDraftId: string;
  /** @minimum 0 */
  reviewVersion: number;
  reviewState: AgreementChargeHistoryItemReviewState;
  latestReceipt: AgreementChargeReviewReceipt | null;
}
