/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPreparationInputSchedulesItem } from './agreementPreparationInputSchedulesItem';

export interface AgreementPreparationInput {
  /** @minimum 1 */
  expectedVersion: number;
  /**
     * @minimum 1
     * @maximum 90
     */
  validForDays?: number;
  /** @nullable */
  projectId?: string | null;
  /** @maxItems 2 */
  schedules: AgreementPreparationInputSchedulesItem[];
}
