/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Choose one package or individual published components; package references retain their exact fixed versions.
 */
export interface AgreementDraftSelection {
  packageId?: string | null;
  msaId?: string | null;
  scopeId?: string | null;
  costId?: string | null;
}
