/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AgreementEstimateOptionStatus = typeof AgreementEstimateOptionStatus[keyof typeof AgreementEstimateOptionStatus];


export const AgreementEstimateOptionStatus = {
  draft: 'draft',
  sent: 'sent',
  approved: 'approved',
  declined: 'declined',
} as const;
