/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type AgreementDraftTemplateSourceKind = typeof AgreementDraftTemplateSourceKind[keyof typeof AgreementDraftTemplateSourceKind];


export const AgreementDraftTemplateSourceKind = {
  msa: 'msa',
  scope: 'scope',
  cost: 'cost',
  package: 'package',
} as const;
