/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * At least a client or inquiry is required. Property and source estimate must match the selected context.
 */
export interface AgreementDraftContext {
  clientId?: string | null;
  propertyId?: string | null;
  leadId?: string | null;
  sourceEstimateId?: string | null;
}
