/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPreparationJobStatus } from './agreementPreparationJobStatus';
import type { AgreementPreparationPeriodSource } from './agreementPreparationPeriodSource';
import type { AgreementPreparationWorkSource } from './agreementPreparationWorkSource';

export interface AgreementPreparationJob {
  jobId: string;
  /** @nullable */
  agreementId: string | null;
  source: AgreementPreparationPeriodSource | AgreementPreparationWorkSource | null;
  status: AgreementPreparationJobStatus;
  /** @nullable */
  failureCode: string | null;
  /** @minimum 1 */
  revision: number;
  /** @minimum 0 */
  retryEpoch: number;
  /** @minimum 0 */
  attempts: number;
  /** @minimum 0 */
  attemptsInEpoch: number;
  availableAt: string;
  createdAt: string;
  /** @nullable */
  completedAt: string | null;
  /** @nullable */
  chargeId: string | null;
}
