/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPreparationInputSchedulesItemBasis } from './agreementPreparationInputSchedulesItemBasis';
import type { AgreementPreparationInputSchedulesItemCadence } from './agreementPreparationInputSchedulesItemCadence';

export type AgreementPreparationInputSchedulesItem = {
  basis: AgreementPreparationInputSchedulesItemBasis;
  cadence: AgreementPreparationInputSchedulesItemCadence;
  /**
     * @minimum 1
     * @maximum 52
     */
  intervalCount: number;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  localTime: string;
  firstVisitOn: string;
};
