/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementChargeFinancialSnapshot } from './agreementChargeFinancialSnapshot';
import type { AgreementChargeReviewAllowedOutcomesItem } from './agreementChargeReviewAllowedOutcomesItem';
import type { AgreementChargeReviewReceipt } from './agreementChargeReviewReceipt';
import type { AgreementChargeReviewReviewState } from './agreementChargeReviewReviewState';

export interface AgreementChargeReview {
  chargeId: string;
  agreementId: string;
  /** @minimum 0 */
  reviewVersion: number;
  latestReceipt: AgreementChargeReviewReceipt | null;
  correctionPending: boolean;
  /** @minimum 1 */
  cancellationVersion: number;
  snapshot: AgreementChargeFinancialSnapshot;
  /** @pattern ^[0-9a-f]{64}$ */
  snapshotSha256: string;
  allowedOutcomes: AgreementChargeReviewAllowedOutcomesItem[];
  /** @nullable */
  postingBlockReason: string | null;
  reviewState: AgreementChargeReviewReviewState;
}
