/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftTemplateSourceKind } from './agreementDraftTemplateSourceKind';
import type { AgreementTemplatePayload } from './agreementTemplatePayload';

export interface AgreementDraftTemplateSource {
  id: string;
  kind: AgreementDraftTemplateSourceKind;
  /** @minimum 1 */
  version: number;
  name: string;
  body: string;
  payload: AgreementTemplatePayload;
}
