/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentAvailabilityWindow } from './assessmentAvailabilityWindow';

export interface AssessmentAvailabilityUpdate {
  /** @minimum 1 */
  version: number;
  /**
     * @minimum 15
     * @maximum 240
     */
  durationMinutes: number;
  /**
     * @minimum 0
     * @maximum 120
     */
  bufferBefore: number;
  /**
     * @minimum 0
     * @maximum 120
     */
  bufferAfter: number;
  /** @maxItems 14 */
  windows: AssessmentAvailabilityWindow[];
}
