/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface AssessmentAvailabilityWindow {
  /**
     * Day of week, where 0 is Sunday and 6 is Saturday.
     * @minimum 0
     * @maximum 6
     */
  day: number;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  start: string;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  end: string;
}
