/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { BillingDraftKind } from './billingDraftKind';
import type { BillingDraftStatus } from './billingDraftStatus';

export interface BillingDraft {
  id: string;
  property_id: string;
  /** @nullable */
  estimate_id?: string | null;
  title: string;
  amount_cents: number;
  kind: BillingDraftKind;
  status: BillingDraftStatus;
  /** @nullable */
  quickbooks_id?: string | null;
  /** @nullable */
  balance_cents?: number | null;
  /** @nullable */
  payment_url?: string | null;
  ownership_verified?: boolean;
  created_at: string;
  property_name: string;
}
