/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface BillingExternalInvoiceRecord {
  id: string;
  billingDraftId: string;
  /**
     * @maxLength 120
     * @nullable
     */
  reference: string | null;
  invoicedOn: string;
  /**
     * @maxLength 2000
     * @nullable
     */
  note: string | null;
  recordedBy: string;
  recordedAt: string;
  /** @nullable */
  voidedBy: string | null;
  /** @nullable */
  voidedAt: string | null;
  /** @nullable */
  voidReason: string | null;
}
