/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type BusinessCapability = typeof BusinessCapability[keyof typeof BusinessCapability];


export const BusinessCapability = {
  workspaceoverview: 'workspace.overview',
  'workspacemy-day': 'workspace.my-day',
  customersclients: 'customers.clients',
  customersproperties: 'customers.properties',
  customersrequests: 'customers.requests',
  operationsschedule: 'operations.schedule',
  operationsrecurring: 'operations.recurring',
  operationsprojects: 'operations.projects',
  operationsinspections: 'operations.inspections',
  revenuesales: 'revenue.sales',
  revenueagreements: 'revenue.agreements',
  'revenueagreement-templatesmanage': 'revenue.agreement-templates.manage',
  revenuebilling: 'revenue.billing',
  revenueexpenses: 'revenue.expenses',
  marketingcontentwebsite: 'marketing.content.website',
  marketingcontentpages: 'marketing.content.pages',
  marketingcontentteam: 'marketing.content.team',
  marketingcontentforms: 'marketing.content.forms',
  marketingcontentblog: 'marketing.content.blog',
  marketingcontentgalleries: 'marketing.content.galleries',
  marketingcontentmedia: 'marketing.content.media',
  marketingcontentsections: 'marketing.content.sections',
  marketingcontentseo: 'marketing.content.seo',
  marketingcontentmenus: 'marketing.content.menus',
  marketingcontentsidebars: 'marketing.content.sidebars',
  marketingdesignbranding: 'marketing.design.branding',
  marketingdesigncolors: 'marketing.design.colors',
  'marketingdesignsocial-media': 'marketing.design.social-media',
  marketingdesigntypography: 'marketing.design.typography',
  marketinganalyticsview: 'marketing.analytics.view',
  'marketingsearch-consoleview': 'marketing.search-console.view',
  settingspreferences: 'settings.preferences',
  'settingsterm-libraries': 'settings.term-libraries',
} as const;
