/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CancelServiceAgreement {
  /** @exclusiveMinimum 0 */
  version: number;
  effectiveOn: string;
  /**
     * @minLength 1
     * @maxLength 1000
     */
  reason: string;
}
