/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface ClientNote {
  id: string;
  /** @nullable */
  property_id?: string | null;
  /** @nullable */
  property_name?: string | null;
  body: string;
  author_name: string;
  created_at: string;
}
