/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ClientContactKind } from './clientContactKind';

export interface ClientContact {
  id: string;
  client_id: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /** @nullable */
  first_name?: string | null;
  /** @nullable */
  last_name?: string | null;
  /** @nullable */
  email: string | null;
  /**
     * @maxLength 50
     * @nullable
     */
  phone: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  position: string | null;
  kind: ClientContactKind;
  archived: boolean;
  /** @minimum 1 */
  version: number;
}
