/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ClientContact } from './clientContact';
import type { ClientNote } from './clientNote';
import type { ClientWorkspaceActivityItem } from './clientWorkspaceActivityItem';
import type { ClientWorkspaceAgreementsItem } from './clientWorkspaceAgreementsItem';
import type { ClientWorkspaceClient } from './clientWorkspaceClient';
import type { ClientWorkspaceProjectsItem } from './clientWorkspaceProjectsItem';
import type { ClientWorkspacePropertiesItem } from './clientWorkspacePropertiesItem';
import type { ClientWorkspaceRequestsItem } from './clientWorkspaceRequestsItem';
import type { ClientWorkspaceScheduleItem } from './clientWorkspaceScheduleItem';

export interface ClientWorkspace {
  client: ClientWorkspaceClient;
  properties: ClientWorkspacePropertiesItem[];
  contacts: ClientContact[];
  agreements: ClientWorkspaceAgreementsItem[];
  schedule: ClientWorkspaceScheduleItem[];
  requests: ClientWorkspaceRequestsItem[];
  projects: ClientWorkspaceProjectsItem[];
  notes: ClientNote[];
  activity: ClientWorkspaceActivityItem[];
}
