/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface ClientPrimaryContact {
  /**
     * @minLength 1
     * @maxLength 100
     */
  firstName: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  lastName: string;
  /** @maxLength 254 */
  email: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  position: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  phone: string;
}
