/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialFollowUpStatus } from './commercialFollowUpStatus';

export interface CommercialFollowUp {
  /** @minimum 1 */
  expectedVersion: number;
  /**
     * @minLength 1
     * @maxLength 200
     * @nullable
     */
  ownerId: string | null;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  nextAction: string;
  /** @nullable */
  nextActionDueAt: string | null;
  status: CommercialFollowUpStatus;
}
