/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentCategory } from './commercialAssessmentCategory';
import type { CommercialAssessmentPriority } from './commercialAssessmentPriority';

export interface CommercialAssessmentFinding {
  id?: string;
  category: CommercialAssessmentCategory;
  /** @maxLength 200 */
  conditionLabel?: string | null;
  /** @maxLength 200 */
  condition_label?: string | null;
  /** @maxLength 4000 */
  observation: string;
  priority?: CommercialAssessmentPriority | null;
  [key: string]: unknown;
 }
