/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type CommercialAssessmentStatus = typeof CommercialAssessmentStatus[keyof typeof CommercialAssessmentStatus];


export const CommercialAssessmentStatus = {
  draft: 'draft',
  reviewed: 'reviewed',
  archived: 'archived',
} as const;
