/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type CommercialAssessmentCategory = typeof CommercialAssessmentCategory[keyof typeof CommercialAssessmentCategory];


export const CommercialAssessmentCategory = {
  grounds_vegetation: 'grounds_vegetation',
  stormwater_drainage: 'stormwater_drainage',
  grading_erosion: 'grading_erosion',
  tree_land: 'tree_land',
  roads_access: 'roads_access',
  emergency_corrective: 'emergency_corrective',
  recurring_site_management: 'recurring_site_management',
  other: 'other',
} as const;
