/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type CommercialAssessmentDetailReviewsItem = {
  assessment_version: number;
  /** @pattern ^[a-f0-9]{64}$ */
  snapshot_sha256: string;
  created_at: string;
  [key: string]: unknown;
 };
