/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentAppointmentStatus } from './commercialAssessmentAppointmentStatus';

export interface CommercialAssessmentAppointment {
  id: string;
  slot_id: string;
  property_id: string;
  status: CommercialAssessmentAppointmentStatus;
  /** @minimum 1 */
  version: number;
  created_by?: string;
  cancelled_by?: string | null;
  cancelled_at?: string | null;
  /** @maxLength 2000 */
  cancellation_reason?: string | null;
  created_at: string;
  updated_at: string;
  [key: string]: unknown;
 }
