/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentFinding } from './commercialAssessmentFinding';
import type { CommercialAssessmentRecommendation } from './commercialAssessmentRecommendation';

export interface CommercialAssessmentUpdate {
  /** @minimum 1 */
  expectedVersion: number;
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  scopeNote?: string | null;
  /** @maxItems 50 */
  findings: CommercialAssessmentFinding[];
  /** @maxItems 50 */
  recommendations: CommercialAssessmentRecommendation[];
}
