/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialInquiryStatus } from './commercialInquiryStatus';

export interface CommercialInquiry {
  name: string;
  location: string;
  description: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  reported_company_name: string | null;
  /** @nullable */
  reported_property_name: string | null;
  /** @nullable */
  contact_title: string | null;
  /** @nullable */
  property_type: string | null;
  /** @nullable */
  acreage_description: string | null;
  /** @nullable */
  project_stage: string | null;
  /** @nullable */
  service_timing: string | null;
  /** @nullable */
  owner_id: string | null;
  /** @nullable */
  next_action: string | null;
  id: string;
  status: CommercialInquiryStatus;
  /** @minimum 1 */
  version: number;
  services: string[];
  /** @nullable */
  next_action_due_at: string | null;
  created_at: string;
  last_activity_at: string;
}
