/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentAppointment } from './commercialAssessmentAppointment';
import type { CommercialAssessmentDetailReviewsItem } from './commercialAssessmentDetailReviewsItem';
import type { CommercialAssessmentFinding } from './commercialAssessmentFinding';
import type { CommercialAssessmentRecommendation } from './commercialAssessmentRecommendation';
import type { CommercialAssessmentSummary } from './commercialAssessmentSummary';

export type CommercialAssessmentDetail = CommercialAssessmentSummary & ({
  /** @maxLength 4000 */
  scope_note?: string | null;
  findings: CommercialAssessmentFinding[];
  recommendations: CommercialAssessmentRecommendation[];
  reviews: CommercialAssessmentDetailReviewsItem[];
  appointments: CommercialAssessmentAppointment[];
});
