/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentStatus } from './commercialAssessmentStatus';

export interface CommercialAssessmentSummary {
  id: string;
  lead_id: string;
  property_id?: string | null;
  /** @maxLength 200 */
  title: string;
  status: CommercialAssessmentStatus;
  /** @minimum 1 */
  version: number;
  created_at: string;
  updated_at: string;
  [key: string]: unknown;
 }
