/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CommercialAssessmentPriority } from './commercialAssessmentPriority';

export interface CommercialAssessmentRecommendation {
  id?: string;
  /** @minimum 0 */
  findingIndex?: number | null;
  finding_id?: string | null;
  /** @maxLength 4000 */
  recommendation: string;
  priority?: CommercialAssessmentPriority | null;
  [key: string]: unknown;
 }
