/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CommercialAssessmentCreateReceipt {
  assessmentId: string;
  leadId: string;
  /** @minimum 1 */
  leadVersion: number;
  /** @minimum 1 */
  version: number;
  propertyId: string | null;
}
