/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateEstimateKind } from './createEstimateKind';
import type { EstimateLineItem } from './estimateLineItem';
import type { RecurringJobConfiguration } from './recurringJobConfiguration';

export interface CreateEstimate {
  propertyId: string;
  projectId?: string;
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  scope: string;
  terms?: string;
  /** @minItems 1 */
  lineItems: EstimateLineItem[];
  kind: CreateEstimateKind;
  recurring?: RecurringJobConfiguration;
  agreementTemplateId?: string;
}
