/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateExpense {
  propertyId: string;
  /**
     * @maximum 10000000000
     * @exclusiveMinimum 0
     */
  amountCents: number;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  category: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  description: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  incurredOn: string;
}
