/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { LegacyProjectPhase } from './legacyProjectPhase';

export interface CreateProject {
  propertyId?: string;
  /**
     * Participating client properties. The server derives client membership and never grants cross-client access.
     * @minItems 1
     * @maxItems 100
     */
  propertyIds?: string[];
  /**
     * @minLength 1
     * @maxLength 10000
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  scope: string;
  /** @maxItems 50 */
  phases?: LegacyProjectPhase[];
}
