/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftContext } from './agreementDraftContext';
import type { AgreementDraftDates } from './agreementDraftDates';
import type { AgreementDraftSelection } from './agreementDraftSelection';

export interface CreateAgreementDraft {
  operationId: string;
  title: string;
  context: AgreementDraftContext;
  selection?: AgreementDraftSelection;
  dates?: AgreementDraftDates;
}
