/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type CreatePackageAgreementTemplateKind = typeof CreatePackageAgreementTemplateKind[keyof typeof CreatePackageAgreementTemplateKind];


export const CreatePackageAgreementTemplateKind = {
  package: 'package',
} as const;
