/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderItem } from './workOrderItem';

export interface CreateWorkOrder {
  propertyId: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  title: string;
  /** @maxLength 10000 */
  scope?: string;
  assignedTo?: string;
  scheduledAt?: string;
  /** @maxItems 100 */
  checklist?: WorkOrderItem[];
  /** @maxItems 50 */
  prerequisites?: WorkOrderItem[];
}
