/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateRecurringServiceBillingMode } from './createRecurringServiceBillingMode';
import type { CreateRecurringServiceCadence } from './createRecurringServiceCadence';

export interface CreateRecurringService {
  propertyId: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  title: string;
  /** @maxLength 10000 */
  scope?: string;
  cadence: CreateRecurringServiceCadence;
  /**
     * @minimum 1
     * @maximum 52
     */
  intervalCount: number;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  nextDate: string;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  localTime?: string;
  assignedTo?: string;
  billingMode: CreateRecurringServiceBillingMode;
}
