/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateDashboardProperty {
  clientId: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  address: string;
  /** @minimum 0 */
  acreage?: number;
  /** @maxLength 10000 */
  accessInstructions?: string;
  /** @nullable */
  propertyTypeId?: string | null;
}
