/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateClientContactKind } from './createClientContactKind';

export interface CreateClientContact {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  /**
     * @maxLength 254
     * @nullable
     */
  email?: string | null;
  /**
     * @maxLength 50
     * @nullable
     */
  phone?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  position?: string | null;
  kind: CreateClientContactKind;
}
