/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { InspectionFinding } from './inspectionFinding';

export interface CreateInspectionReport {
  propertyId: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  title: string;
  /** @maxItems 100 */
  findings: InspectionFinding[];
}
