/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateDashboardProperty {
  clientId: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  name: string;
  /**
     * Legacy formatted address accepted for existing internal callers. New property entry must use structured address fields.
     * @deprecated
     * @minLength 1
     * @maxLength 10000
     */
  address?: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  addressLine1: string;
  /** @maxLength 200 */
  addressLine2?: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  city: string;
  /** @pattern ^[A-Za-z]{2}$ */
  state: string;
  /** @pattern ^\d{5}(?:-\d{4})?$ */
  postalCode: string;
  /** @minimum 0 */
  acreage?: number;
  /** @maxLength 10000 */
  accessInstructions?: string;
  /** @nullable */
  propertyTypeId?: string | null;
}
