/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateEstimateKind } from './createEstimateKind';
import type { EstimateLineItem } from './estimateLineItem';
import type { RecurringJobConfiguration } from './recurringJobConfiguration';

export interface CreateEstimate {
  propertyId: string;
  /** Staff-only Project grouping; the selected property must participate. */
  projectId?: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  title: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  scope: string;
  /** @maxLength 50000 */
  terms?: string;
  /**
     * @minItems 1
     * @maxItems 100
     */
  lineItems: EstimateLineItem[];
  kind: CreateEstimateKind;
  recurring?: RecurringJobConfiguration;
  /** Required for recurring estimates and snapshotted when the draft is created. */
  agreementTemplateId?: string;
}
