/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ClientPrimaryContact } from './clientPrimaryContact';

/**
 * When primaryContact is supplied, address and phone are required for atomic onboarding.
 */
export interface CreateDashboardClient {
  /**
     * @minLength 1
     * @maxLength 10000
     */
  name: string;
  email?: string;
  /** @maxLength 50 */
  phone?: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  address?: string;
  primaryContact?: ClientPrimaryContact;
}
