/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CrmArchiveDetail {
  sourceInstanceId: string;
  collection: string;
  sourceId: string;
  sourceSha256: string;
  importedAt: string;
  /** Original source JSON rendered as text to preserve numeric precision. */
  sourceJson: string;
}
