/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface CrmTask {
  id: string;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  title: string;
  /** @nullable */
  dueAt: string | null;
  /** @nullable */
  assignedToId: string | null;
  completed: boolean;
  /** @nullable */
  assigneeName: string | null;
  /** @nullable */
  createdById: string | null;
  /** @nullable */
  creatorName: string | null;
  createdAt: string;
  updatedAt: string;
  version: number;
  imported: boolean;
}
