/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardProperty {
  id: string;
  client_id: string;
  name: string;
  address: string;
  /** @nullable */
  address_line1?: string | null;
  /** @nullable */
  address_line2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  postal_code?: string | null;
  /**
     * PostgreSQL numeric wire representation; do not coerce missing to zero
     * @nullable
     */
  acreage: string | null;
  /** @nullable */
  property_type_id?: string | null;
  /** @nullable */
  property_type_name?: string | null;
  access_instructions?: string;
  notes?: string;
  archived?: boolean;
  created_at?: string;
}
