/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type DashboardMeRole = typeof DashboardMeRole[keyof typeof DashboardMeRole] | null;


export const DashboardMeRole = {
  owner: 'owner',
  manager: 'manager',
  dispatch: 'dispatch',
  sales: 'sales',
  finance: 'finance',
  crew: 'crew',
  client: 'client',
} as const;
