/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardMeRole } from './dashboardMeRole';

export interface DashboardMe {
  id: string;
  name: string;
  email: string;
  /**
     * Private same-origin avatar endpoint for the current account; null when no avatar is stored.
     * @nullable
     */
  avatarUrl: string | null;
  /** @nullable */
  twoFactorEnabled?: boolean | null;
  mfaRequired: boolean;
  /**
     * Deprecated compatibility alias for mfaRequired.
     * @deprecated
     */
  ownerMfaRequired: boolean;
  /** @nullable */
  role: DashboardMeRole;
}
