/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardClient {
  id: string;
  name: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  billing_address?: string | null;
  /** @minimum 1 */
  version?: number;
  /** @nullable */
  primary_contact_name?: string | null;
  /** @nullable */
  primary_contact_first_name?: string | null;
  /** @nullable */
  primary_contact_last_name?: string | null;
  /** @nullable */
  primary_contact_email?: string | null;
  /** @nullable */
  primary_contact_phone?: string | null;
  /** @nullable */
  primary_contact_position?: string | null;
  [key: string]: unknown;
 }
