/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { EstimateBillingAllocationsAllocationsItemBasis } from './estimateBillingAllocationsAllocationsItemBasis';

export type EstimateBillingAllocationsAllocationsItem = {
  id: string;
  title: string;
  basis: EstimateBillingAllocationsAllocationsItemBasis;
  /** @minimum 0 */
  approvedCents: number;
  /** @minimum 0 */
  billedCents: number;
  /** @minimum 0 */
  remainingCents: number;
};
