/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface EstimateLineItem {
  /**
     * @minLength 1
     * @maxLength 2000
     */
  description: string;
  /** @maxLength 100 */
  unit?: string;
  /** @exclusiveMinimum 0 */
  quantity: number;
  /** @minimum 0 */
  unitPriceCents: number;
}
