/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface Expense {
  id: string;
  property_id: string;
  /** @nullable */
  work_order_id: string | null;
  /**
     * Positive cents returned as a base-10 string because the PostgreSQL source column is bigint.
     * @pattern ^[1-9][0-9]*$
     */
  amount_cents: string;
  category: string;
  description: string;
  incurred_on: string;
  created_by: string;
  property_name: string;
}
