/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { FieldConflictPayload } from './fieldConflictPayload';

export interface FieldConflict {
  id: string;
  work_order_id: string;
  kind: string;
  captured_at: string;
  work_title: string;
  work_status: string;
  property_name: string;
  submitted_by: string;
  payload: FieldConflictPayload;
  base_version: number;
}
