/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Initial shared field-client contract. Additional office routes are documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type FieldOperationKind = typeof FieldOperationKind[keyof typeof FieldOperationKind];


export const FieldOperationKind = {
  note: 'note',
  issue: 'issue',
  time: 'time',
  checklist: 'checklist',
  complete: 'complete',
} as const;
