/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Initial shared field-client contract. Additional office routes are documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { FieldSyncResponseResultsItemStatus } from './fieldSyncResponseResultsItemStatus';

export type FieldSyncResponseResultsItem = {
  id: string;
  status: FieldSyncResponseResultsItemStatus;
};
