/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type FieldOperationPayloadAction = typeof FieldOperationPayloadAction[keyof typeof FieldOperationPayloadAction];


export const FieldOperationPayloadAction = {
  start: 'start',
  stop: 'stop',
  break: 'break',
  travel: 'travel',
} as const;
