/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type GoogleReportingConfigurationSaveFieldsSearchConsoleSite = typeof GoogleReportingConfigurationSaveFieldsSearchConsoleSite[keyof typeof GoogleReportingConfigurationSaveFieldsSearchConsoleSite];


export const GoogleReportingConfigurationSaveFieldsSearchConsoleSite = {
  '': '',
  'sc-domain:p1landmanagementcom': 'sc-domain:p1landmanagement.com',
  'https://wwwp1landmanagementcom/': 'https://www.p1landmanagement.com/',
  'https://p1landmanagementcom/': 'https://p1landmanagement.com/',
} as const;
