/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { GoogleReportingConfigurationCredentialManagement } from './googleReportingConfigurationCredentialManagement';
import type { GoogleReportingConfigurationCredentialMode } from './googleReportingConfigurationCredentialMode';
import type { GoogleReportingConfigurationManagedTargets } from './googleReportingConfigurationManagedTargets';
import type { GoogleReportingConfigurationTargetSource } from './googleReportingConfigurationTargetSource';

export interface GoogleReportingConfiguration {
  effectiveSource: string;
  configurationManagement: string;
  credentialMode: GoogleReportingConfigurationCredentialMode;
  /** @nullable */
  propertyId: string | null;
  searchConsoleConfigured: boolean;
  /** @nullable */
  searchConsoleSite: string | null;
  publicTrackingSource: string;
  note: string;
  /** @pattern ^[a-f0-9]{64}$ */
  version: string;
  targetSource: GoogleReportingConfigurationTargetSource;
  credentialManagement: GoogleReportingConfigurationCredentialManagement;
  managedTargets: GoogleReportingConfigurationManagedTargets;
}
