/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type GoogleReportingConfigurationCredentialManagement = typeof GoogleReportingConfigurationCredentialManagement[keyof typeof GoogleReportingConfigurationCredentialManagement];


export const GoogleReportingConfigurationCredentialManagement = {
  deployment: 'deployment',
} as const;
