/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { GoogleReportingConfigurationSaveFieldsSearchConsoleSite } from './googleReportingConfigurationSaveFieldsSearchConsoleSite';
import type { GoogleReportingConfigurationSaveFieldsTargetSource } from './googleReportingConfigurationSaveFieldsTargetSource';

export type GoogleReportingConfigurationSaveFields = {
  targetSource: GoogleReportingConfigurationSaveFieldsTargetSource;
  /**
     * @maxLength 32
     * @pattern ^[0-9]*$
     */
  propertyId: string;
  searchConsoleSite: GoogleReportingConfigurationSaveFieldsSearchConsoleSite;
};
