/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export * from './commercialFollowUp';
export * from './commercialFollowUpStatus';
export * from './commercialInquiry';
export * from './commercialInquiryDetail';
export * from './commercialInquiryDetailRawIntake';
export * from './commercialInquiryPage';
export * from './commercialInquiryReceipt';
export * from './commercialInquiryStatus';
export * from './dashboardError';
export * from './dashboardMe';
export * from './dashboardMeRole';
export * from './dashboardProperty';
export * from './fieldOperation';
export * from './fieldOperationKind';
export * from './fieldOperationPayload';
export * from './fieldOperationPayloadAction';
export * from './fieldOperationPayloadItemsItem';
export * from './fieldSyncResponse';
export * from './fieldSyncResponseResultsItem';
export * from './fieldSyncResponseResultsItemStatus';
export * from './getScheduleParams';
export * from './getScheduleUnscheduled';
export * from './getSetupStatus200';
export * from './listCommercialInquiriesOverdue';
export * from './listCommercialInquiriesParams';
export * from './listCommercialInquiriesStatus';
export * from './photoUploadReceipt';
export * from './photoUploadReceiptStatus';
export * from './propertyFile';
export * from './propertyTimelineEvent';
export * from './propertyTimelineEventKind';
export * from './propertyTimelineEventPayload';
export * from './readinessItem';
export * from './readinessResult';
export * from './readinessUpdate';
export * from './rescheduleWork';
export * from './schedulePage';
export * from './syncFieldEventsBody';
export * from './uploadFieldPhotoHeaders';
export * from './uploadFieldPhotoXP1Classification';
export * from './workOrder';
export * from './workOrderChecklistItem';
export * from './workVersion';
