/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { InspectionFinding } from './inspectionFinding';

export interface InspectionReport {
  id: string;
  property_id: string;
  /** Submitting staff identity; omitted from client responses. */
  user_id?: string;
  title: string;
  findings: InspectionFinding[];
  published: boolean;
  created_at: string;
  property_name: string;
}
