/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface IntegrationActionQueueItem {
  id: string;
  kind: string;
  status: string;
  /** @minimum 0 */
  attempts: number;
  /** @nullable */
  last_error: string | null;
  created_at: string;
}
