/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPreparationHealth } from './agreementPreparationHealth';
import type { IntegrationActionQueueItem } from './integrationActionQueueItem';
import type { IntegrationConfiguration } from './integrationConfiguration';
import type { QuickBooksIntegrationConfiguration } from './quickBooksIntegrationConfiguration';

export interface IntegrationHealth {
  quickbooks: QuickBooksIntegrationConfiguration;
  email: IntegrationConfiguration;
  sms: IntegrationConfiguration;
  /** @maxItems 50 */
  jobs: IntegrationActionQueueItem[];
  agreementPreparation: AgreementPreparationHealth;
}
