/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface LeadFollowUp {
  id: string;
  name: string;
  status: string;
  /** @nullable */
  owner_id: string | null;
  /** @nullable */
  next_action: string | null;
  /** @nullable */
  next_action_due_at: string | null;
  /** @nullable */
  last_activity_at: string | null;
  version: number;
  /** @nullable */
  converted_client_id: string | null;
  /** @nullable */
  converted_property_id: string | null;
}
