/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Reported intake context; does not change linked operational property records.
 */
export interface LeadSubmittedContext {
  contact_title: string | null;
  reported_property_name: string | null;
  property_type: string | null;
  acreage_description: string | null;
  project_stage: string | null;
  service_timing: string | null;
  services: string[];
}
