/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { LeadDetailFields } from './leadDetailFields';
import type { LeadDetailHistoryItemsItemKind } from './leadDetailHistoryItemsItemKind';

export type LeadDetailHistoryItemsItem = {
  version: number;
  kind: LeadDetailHistoryItemsItemKind;
  fields: LeadDetailFields;
  /** @nullable */
  actor_name: string | null;
  recorded_at: string;
};
