/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ListMarketingGalleriesSort } from './listMarketingGalleriesSort';
import type { ListMarketingGalleriesStatus } from './listMarketingGalleriesStatus';

export type ListMarketingGalleriesParams = {
search?: string;
status?: ListMarketingGalleriesStatus;
sort?: ListMarketingGalleriesSort;
};
