/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type ListSalesInquiriesKind = typeof ListSalesInquiriesKind[keyof typeof ListSalesInquiriesKind];


export const ListSalesInquiriesKind = {
  all: 'all',
  general: 'general',
  commercial: 'commercial',
} as const;
