/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type ListAgreementTemplatesState = typeof ListAgreementTemplatesState[keyof typeof ListAgreementTemplatesState];


export const ListAgreementTemplatesState = {
  published: 'published',
  draft: 'draft',
  archived: 'archived',
  all: 'all',
} as const;
