/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ListSalesInquiriesKind } from './listSalesInquiriesKind';
import type { ListSalesInquiriesOverdue } from './listSalesInquiriesOverdue';
import type { ListSalesInquiriesStatus } from './listSalesInquiriesStatus';

export type ListSalesInquiriesParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string;
/**
 * @maxLength 200
 */
q?: string;
status?: ListSalesInquiriesStatus;
ownerId?: string;
kind?: ListSalesInquiriesKind;
overdue?: ListSalesInquiriesOverdue;
};
