/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type ListAgreementPreparationJobsStatus = typeof ListAgreementPreparationJobsStatus[keyof typeof ListAgreementPreparationJobsStatus];


export const ListAgreementPreparationJobsStatus = {
  pending: 'pending',
  processing: 'processing',
  sent: 'sent',
  failed: 'failed',
} as const;
