/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ListCommercialInquiriesOverdue } from './listCommercialInquiriesOverdue';
import type { ListCommercialInquiriesStatus } from './listCommercialInquiriesStatus';

export type ListCommercialInquiriesParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @maxLength 1024
 * @pattern ^[A-Za-z0-9_-]+$
 */
cursor?: string;
status?: ListCommercialInquiriesStatus;
/**
 * Active owner ID or unassigned
 * @minLength 1
 * @maxLength 200
 */
ownerId?: string;
overdue?: ListCommercialInquiriesOverdue;
};
