/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessCapability } from './businessCapability';

export interface ManagedInvitation {
  id: string;
  email: string;
  role: string;
  firstName: string;
  lastName: string;
  capabilities: BusinessCapability[];
  expiresAt: string;
  /** @nullable */
  acceptedAt: string | null;
  /** @nullable */
  revokedAt: string | null;
  createdAt: string;
}
