/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessCapability } from './businessCapability';
import type { ManagedAccountRole } from './managedAccountRole';

export interface ManagedAccount {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  /** @nullable */
  twoFactorEnabled: boolean | null;
  role: ManagedAccountRole;
  active: boolean;
  firstName: string;
  lastName: string;
  capabilities: BusinessCapability[];
  formNotificationIds: string[];
  /** @minimum 1 */
  version: number;
  /** @nullable */
  reviewedAt: string | null;
  mfaRequired: boolean;
  suggestedCapabilities: BusinessCapability[];
}
