/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogPublicationSchedule } from './marketingBlogPublicationSchedule';
import type { MarketingBlogPublicationStateVisibility } from './marketingBlogPublicationStateVisibility';

export interface MarketingBlogPublicationState {
  requiresAdoption: boolean;
  /** @minimum 1 */
  version: number | null;
  legacyFingerprint: string;
  visibility: MarketingBlogPublicationStateVisibility;
  draftRevisionId: string | null;
  publishedRevisionId: string | null;
  lastPublishedRevisionId: string | null;
  /** @minimum 0 */
  publicationGeneration: number;
  schedule: MarketingBlogPublicationSchedule | null;
}
