/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingCareerSettings } from './marketingCareerSettings';
import type { MarketingCareerSettingsUpdateClearCredentialsItem } from './marketingCareerSettingsUpdateClearCredentialsItem';

export type MarketingCareerSettingsUpdate = MarketingCareerSettings & {
  /**
     * Explicit removal selections. Requires the loaded version and the corresponding integration disabled; cannot also supply a replacement.
     * @maxItems 4
     */
  clearCredentials?: MarketingCareerSettingsUpdateClearCredentialsItem[];
};
