/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingDateRange } from './marketingDateRange';
import type { MarketingSearchConsoleReports } from './marketingSearchConsoleReports';
import type { MarketingSearchConsoleStatus } from './marketingSearchConsoleStatus';

export interface MarketingSearchConsole {
  status: MarketingSearchConsoleStatus;
  fetchedAt: string;
  siteUrl: string;
  dateRange: MarketingDateRange;
  previousDateRange: MarketingDateRange;
  reports: MarketingSearchConsoleReports;
}
