/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingRedirectInputStatusCode } from './marketingRedirectInputStatusCode';

export interface MarketingRedirectInput {
  fromPath: string;
  toPath: string;
  statusCode: MarketingRedirectInputStatusCode;
  isActive: boolean;
  /** @nullable */
  note?: string | null;
}
