/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingEventFormat = typeof MarketingEventFormat[keyof typeof MarketingEventFormat] | null;


export const MarketingEventFormat = {
  single_session: 'single_session',
  multi_session: 'multi_session',
  series: 'series',
  office_hours: 'office_hours',
  one_on_one: 'one_on_one',
  drop_in: 'drop_in',
} as const;
