/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBuilderPropertyOptionsItem } from './marketingBuilderPropertyOptionsItem';
import type { MarketingBuilderPropertyType } from './marketingBuilderPropertyType';

export interface MarketingBuilderProperty {
  key: string;
  label: string;
  type: MarketingBuilderPropertyType;
  placeholder?: string;
  min?: number;
  max?: number;
  options?: MarketingBuilderPropertyOptionsItem[];
  itemSchema?: MarketingBuilderProperty[];
}
