/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingEventUpdateEventType = typeof MarketingEventUpdateEventType[keyof typeof MarketingEventUpdateEventType] | null;


export const MarketingEventUpdateEventType = {
  training: 'training',
  workshop: 'workshop',
  webinar: 'webinar',
  class: 'class',
  consultation: 'consultation',
  appointment: 'appointment',
  community_event: 'community_event',
} as const;
