/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingBlogPublicationActionAction = typeof MarketingBlogPublicationActionAction[keyof typeof MarketingBlogPublicationActionAction];


export const MarketingBlogPublicationActionAction = {
  save: 'save',
  publish: 'publish',
  unpublish: 'unpublish',
  restore: 'restore',
  delete: 'delete',
  schedule: 'schedule',
  cancel_schedule: 'cancel_schedule',
} as const;
