/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingFormDeliveryJobDeliveryResult } from './marketingFormDeliveryJobDeliveryResult';

export interface MarketingFormDeliveryJob {
  id: string;
  submissionId: string;
  kind: string;
  status: string;
  attemptCount: number;
  failedAt?: string | null;
  lastErrorCode?: string | null;
  nextAttemptAt?: string | null;
  createdAt?: string | null;
  deliveryResult?: MarketingFormDeliveryJobDeliveryResult;
}
