/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingCareerApplicationStatus = typeof MarketingCareerApplicationStatus[keyof typeof MarketingCareerApplicationStatus];


export const MarketingCareerApplicationStatus = {
  new: 'new',
  reviewing: 'reviewing',
  shortlisted: 'shortlisted',
  interviewing: 'interviewing',
  offered: 'offered',
  hired: 'hired',
  rejected: 'rejected',
  withdrawn: 'withdrawn',
} as const;
