/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingGallerySettingsBorderRadius = typeof MarketingGallerySettingsBorderRadius[keyof typeof MarketingGallerySettingsBorderRadius];


export const MarketingGallerySettingsBorderRadius = {
  none: 'none',
  sm: 'sm',
  md: 'md',
  lg: 'lg',
} as const;
