/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingGallerySettingsImageRatio = typeof MarketingGallerySettingsImageRatio[keyof typeof MarketingGallerySettingsImageRatio];


export const MarketingGallerySettingsImageRatio = {
  auto: 'auto',
  '1/1': '1/1',
  '4/3': '4/3',
  '3/2': '3/2',
  '16/9': '16/9',
} as const;
