/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingGalleryInputLayout = typeof MarketingGalleryInputLayout[keyof typeof MarketingGalleryInputLayout];


export const MarketingGalleryInputLayout = {
  grid: 'grid',
  masonry: 'masonry',
  carousel: 'carousel',
  slider: 'slider',
  featured: 'featured',
} as const;
