/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingCareerJobInputEmploymentType } from './marketingCareerJobInputEmploymentType';
import type { MarketingCareerJobInputIntegrationMetadata } from './marketingCareerJobInputIntegrationMetadata';
import type { MarketingCareerJobInputStatus } from './marketingCareerJobInputStatus';
import type { MarketingCareerJobInputVisibility } from './marketingCareerJobInputVisibility';
import type { MarketingCareerJobInputWorkMode } from './marketingCareerJobInputWorkMode';

export interface MarketingCareerJobInput {
  department?: string | null;
  location?: string | null;
  locationAddress?: string | null;
  directoryProfileId?: string | null;
  summary?: string | null;
  description?: string | null;
  requirements?: string | null;
  benefits?: string | null;
  applicationInstructions?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  title: string;
  slug?: string;
  salaryCurrency?: string;
  salaryPeriod?: string;
  status?: MarketingCareerJobInputStatus;
  visibility?: MarketingCareerJobInputVisibility;
  employmentType?: MarketingCareerJobInputEmploymentType;
  workMode?: MarketingCareerJobInputWorkMode;
  salaryMin?: number | null;
  salaryMax?: number | null;
  salaryVisible?: boolean;
  noindex?: boolean;
  publishedAt?: string | null;
  closesAt?: string | null;
  integrationMetadata?: MarketingCareerJobInputIntegrationMetadata;
}
