/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogEditorial } from './marketingBlogEditorial';
import type { MarketingBlogPublicationActionAction } from './marketingBlogPublicationActionAction';

export interface MarketingBlogPublicationAction {
  action: MarketingBlogPublicationActionAction;
  /** @minimum 1 */
  expectedVersion: number;
  editorInstanceId: string;
  leaseId: string;
  data?: MarketingBlogEditorial;
  revisionId?: string;
  scheduledAt?: string;
}
