/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingPageBuilderSidebarsItem } from './marketingPageBuilderSidebarsItem';
import type { MarketingSectionBuilder } from './marketingSectionBuilder';

export type MarketingPageBuilder = MarketingSectionBuilder & {
  sidebars: MarketingPageBuilderSidebarsItem[];
};
