/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogPost } from './marketingBlogPost';
import type { MarketingBlogPublicationPostCoverImageSet } from './marketingBlogPublicationPostCoverImageSet';
import type { MarketingBlogPublicationPostPresentation } from './marketingBlogPublicationPostPresentation';
import type { MarketingBlogPublicationState } from './marketingBlogPublicationState';
import type { WebsiteEditorReservation } from './websiteEditorReservation';

export type MarketingBlogPublicationPost = MarketingBlogPost & {
  publication: MarketingBlogPublicationState;
  lease?: WebsiteEditorReservation;
  presentation?: MarketingBlogPublicationPostPresentation;
  /** Private reviewed media metadata. Omission preserves the existing set; null clears it. Original is a 1408x768 PNG; variants are ordered 480, 768, 1280 pixel wide WebP images and defaultMediaId identifies the 1280 variant. Editors cannot manufacture reviewed sets. */
  coverImageSet?: MarketingBlogPublicationPostCoverImageSet;
};
