/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingCareerSettingsIntegrations = {
  googleIndexingEnabled?: boolean;
  indeedFeedEnabled?: boolean;
  indeedApplyEnabled?: boolean;
  indeedDispositionSyncEnabled?: boolean;
  zipRecruiterEnabled?: boolean;
  linkedinApiEnabled?: boolean;
  genericWebhookEnabled?: boolean;
  googleServiceAccountJson?: string;
  indeedApplySecret?: string;
  zipRecruiterApiKey?: string;
  linkedinPartnerId?: string;
  genericWebhookUrl?: string;
  genericWebhookSecret?: string;
};
