/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingPagePatchPageType } from './marketingPagePatchPageType';
import type { MarketingPagePatchStatus } from './marketingPagePatchStatus';

export interface MarketingPagePatch {
  sidebarId?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  ogImageUrl?: string | null;
  canonicalUrl?: string | null;
  title?: string;
  slug?: string;
  template?: string;
  pageType?: MarketingPagePatchPageType;
  status?: MarketingPagePatchStatus;
  /** Retained CMS JSON content. Preserve unknown fields and legacy shapes. */
  content?: unknown | null;
  noindex?: boolean | null;
  /** @minimum 1 */
  expectedVersion: number;
  editorInstanceId: string;
  leaseId: string;
}
