/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingAnalyticsReports } from './marketingAnalyticsReports';
import type { MarketingAnalyticsStatus } from './marketingAnalyticsStatus';
import type { MarketingDateRange } from './marketingDateRange';

export interface MarketingAnalytics {
  status: MarketingAnalyticsStatus;
  fetchedAt: string;
  propertyId: string;
  dateRange: MarketingDateRange;
  previousDateRange: MarketingDateRange;
  reports: MarketingAnalyticsReports;
}
