/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingPageRevision {
  id: string;
  pageId: string;
  title: string;
  status: string;
  changedBy?: string | null;
  changeNote?: string | null;
  createdAt?: string | null;
  /** Retained CMS JSON content. Preserve unknown fields and legacy shapes. */
  content?: unknown | null;
}
