/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBuilderBlock } from './marketingBuilderBlock';
import type { MarketingSectionBuilderAliases } from './marketingSectionBuilderAliases';
import type { MarketingSectionBuilderFormsItem } from './marketingSectionBuilderFormsItem';
import type { MarketingSectionBuilderGalleriesItem } from './marketingSectionBuilderGalleriesItem';
import type { MarketingSectionBuilderPagesItem } from './marketingSectionBuilderPagesItem';
import type { MarketingSectionBuilderTeamItem } from './marketingSectionBuilderTeamItem';

export interface MarketingSectionBuilder {
  blocks: MarketingBuilderBlock[];
  aliases: MarketingSectionBuilderAliases;
  pages: MarketingSectionBuilderPagesItem[];
  forms: MarketingSectionBuilderFormsItem[];
  galleries: MarketingSectionBuilderGalleriesItem[];
  team: MarketingSectionBuilderTeamItem[];
}
