/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogPublicationPostPresentationLayout } from './marketingBlogPublicationPostPresentationLayout';
import type { MarketingBlogPublicationPostPresentationSchemaVersion } from './marketingBlogPublicationPostPresentationSchemaVersion';
import type { MarketingBlogPublicationPostPresentationStructuredData } from './marketingBlogPublicationPostPresentationStructuredData';
import type { MarketingBlogPublicationPostPresentationTitlePartsItem } from './marketingBlogPublicationPostPresentationTitlePartsItem';

export type MarketingBlogPublicationPostPresentation = {
  schemaVersion: MarketingBlogPublicationPostPresentationSchemaVersion;
  layout: MarketingBlogPublicationPostPresentationLayout;
  /** @maxLength 200 */
  eyebrow: string;
  /**
     * @minItems 1
     * @maxItems 20
     */
  titleParts: MarketingBlogPublicationPostPresentationTitlePartsItem[];
  /** @maxLength 2000 */
  imageAlt: string;
  /** @maxLength 32768 */
  relatedContent: string;
  structuredData: MarketingBlogPublicationPostPresentationStructuredData;
} | null;
