/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingEventUpdateCategory = typeof MarketingEventUpdateCategory[keyof typeof MarketingEventUpdateCategory] | null;


export const MarketingEventUpdateCategory = {
  education: 'education',
  professional_development: 'professional_development',
  wellness: 'wellness',
  community: 'community',
  consulting: 'consulting',
  support: 'support',
  operations: 'operations',
} as const;
