/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingSidebarWidgetType = typeof MarketingSidebarWidgetType[keyof typeof MarketingSidebarWidgetType];


export const MarketingSidebarWidgetType = {
  'recent-posts': 'recent-posts',
  newsletter: 'newsletter',
  form: 'form',
  callout: 'callout',
  search: 'search',
  categories: 'categories',
  'tag-cloud': 'tag-cloud',
  'custom-html': 'custom-html',
} as const;
