/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingSeoSettings {
  /** @nullable */
  siteName?: string | null;
  /** @nullable */
  titleSuffix?: string | null;
  /** @nullable */
  defaultMetaDescription?: string | null;
  /** @nullable */
  siteUrl?: string | null;
  /** @nullable */
  defaultOgImageUrl?: string | null;
  /** @nullable */
  organizationName?: string | null;
  /** @nullable */
  organizationLogoUrl?: string | null;
  /** @nullable */
  facebookUrl?: string | null;
  /** @nullable */
  twitterHandle?: string | null;
  /** @nullable */
  linkedinUrl?: string | null;
  /** @nullable */
  instagramUrl?: string | null;
  /** @nullable */
  customRobotsTxt?: string | null;
  /** @nullable */
  defaultRobotsNoindex?: boolean | null;
}
