/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingEventVenueInput {
  name: string;
  slug?: string | null;
  description?: string | null;
  address?: string | null;
  city?: string | null;
  region?: string | null;
  postalCode?: string | null;
  country?: string | null;
  phone?: string | null;
  email?: string | null;
  websiteUrl?: string | null;
  latitude?: string | null;
  longitude?: string | null;
  parkingInfo?: string | null;
  accessibilityInfo?: string | null;
  transitInfo?: string | null;
  arrivalNotes?: string | null;
  isVirtual?: boolean | null;
}
