/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingBuilderPropertyType = typeof MarketingBuilderPropertyType[keyof typeof MarketingBuilderPropertyType];


export const MarketingBuilderPropertyType = {
  text: 'text',
  textarea: 'textarea',
  richtext: 'richtext',
  'image-url': 'image-url',
  url: 'url',
  'page-select': 'page-select',
  'gallery-select': 'gallery-select',
  'team-select': 'team-select',
  select: 'select',
  'form-select': 'form-select',
  boolean: 'boolean',
  number: 'number',
  color: 'color',
  'array-items': 'array-items',
} as const;
