/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingBlogEditorial {
  title: string;
  slug: string;
  content: string;
  authorName: string;
  excerpt: string | null;
  coverImageUrl: string | null;
  category: string | null;
  postType: string | null;
  podcastUrl: string | null;
  externalUrl: string | null;
  sidebarId: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImageUrl: string | null;
  categories: string[] | null;
  tags: string[] | null;
  coverImagePositionX: number | null;
  coverImagePositionY: number | null;
  noindex: boolean | null;
}
