/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingBlogCommentSettings {
  commentsEnabled: boolean;
  allowGuestComments: boolean;
  allowLinksInComments: boolean;
  requireApproval: boolean;
  enableSpamProtection: boolean;
  enableHoneypot: boolean;
  enableRateLimit: boolean;
  /**
     * @minimum 10
     * @maximum 86400
     */
  rateLimitSeconds: number;
  /**
     * @minimum 0
     * @maximum 20
     */
  maxLinksPerComment: number;
}
