/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingEventUpdateAudience = typeof MarketingEventUpdateAudience[keyof typeof MarketingEventUpdateAudience] | null;


export const MarketingEventUpdateAudience = {
  public: 'public',
  members: 'members',
  professionals: 'professionals',
  clients: 'clients',
  staff: 'staff',
  invited: 'invited',
} as const;
