/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingReport } from './marketingReport';

export type MarketingAnalyticsReports = {
  totals: MarketingReport;
  previousTotals: MarketingReport;
  daily: MarketingReport;
  channels: MarketingReport;
  sourceMedium: MarketingReport;
  campaigns: MarketingReport;
  pages: MarketingReport;
  landingPages: MarketingReport;
  countries: MarketingReport;
  regions: MarketingReport;
  cities: MarketingReport;
  devices: MarketingReport;
  browsers: MarketingReport;
  events: MarketingReport;
};
