/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingCareerSettingsIntegrations } from './marketingCareerSettingsIntegrations';
import type { MarketingCareerSettingsSharing } from './marketingCareerSettingsSharing';

export interface MarketingCareerSettings {
  /**
     * Opaque loaded settings version. Required on Business Center saves; send unchanged. Stale versions return 409.
     * @pattern ^[a-f0-9]{64}$
     */
  version?: string;
  sharing?: MarketingCareerSettingsSharing;
  integrations?: MarketingCareerSettingsIntegrations;
}
