/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogPublicationPostCoverImageSetVariantsItemHeight } from './marketingBlogPublicationPostCoverImageSetVariantsItemHeight';
import type { MarketingBlogPublicationPostCoverImageSetVariantsItemMime } from './marketingBlogPublicationPostCoverImageSetVariantsItemMime';
import type { MarketingBlogPublicationPostCoverImageSetVariantsItemWidth } from './marketingBlogPublicationPostCoverImageSetVariantsItemWidth';

export type MarketingBlogPublicationPostCoverImageSetVariantsItem = {
  /** @pattern ^[A-Za-z0-9_-]{1,160}$ */
  mediaId: string;
  /**
     * @maxLength 2048
     * @pattern ^/r2/cms/[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*\/[A-Za-z0-9_.-]+\.(?:png|webp)$
     */
  url: string;
  /** @pattern ^[a-f0-9]{64}$ */
  sha256: string;
  /**
     * @minimum 1
     * @maximum 20971520
     */
  bytes: number;
  mime: MarketingBlogPublicationPostCoverImageSetVariantsItemMime;
  /** @minimum 1 */
  width: MarketingBlogPublicationPostCoverImageSetVariantsItemWidth;
  /** @minimum 1 */
  height: MarketingBlogPublicationPostCoverImageSetVariantsItemHeight;
  /**
     * @minimum 1
     * @maximum 100
     */
  quality: number;
};
