/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogEditorialPresentationStructuredDataAuthorType } from './marketingBlogEditorialPresentationStructuredDataAuthorType';
import type { MarketingBlogEditorialPresentationStructuredDataType } from './marketingBlogEditorialPresentationStructuredDataType';

export type MarketingBlogEditorialPresentationStructuredData = {
  type: MarketingBlogEditorialPresentationStructuredDataType;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  headline: string;
  /** @maxLength 12000 */
  description: string;
  authorType: MarketingBlogEditorialPresentationStructuredDataAuthorType;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  publishedDate: string | null;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  modifiedDate: string | null;
};
