/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogEditorialPresentationLayout } from './marketingBlogEditorialPresentationLayout';
import type { MarketingBlogEditorialPresentationSchemaVersion } from './marketingBlogEditorialPresentationSchemaVersion';
import type { MarketingBlogEditorialPresentationStructuredData } from './marketingBlogEditorialPresentationStructuredData';
import type { MarketingBlogEditorialPresentationTitlePartsItem } from './marketingBlogEditorialPresentationTitlePartsItem';

export type MarketingBlogEditorialPresentation = {
  schemaVersion: MarketingBlogEditorialPresentationSchemaVersion;
  layout: MarketingBlogEditorialPresentationLayout;
  /** @maxLength 200 */
  eyebrow: string;
  /**
     * @minItems 1
     * @maxItems 20
     */
  titleParts: MarketingBlogEditorialPresentationTitlePartsItem[];
  /** @maxLength 2000 */
  imageAlt: string;
  /** @maxLength 32768 */
  relatedContent: string;
  structuredData: MarketingBlogEditorialPresentationStructuredData;
} | null;
