/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingBlogPublicationScheduleStatus = typeof MarketingBlogPublicationScheduleStatus[keyof typeof MarketingBlogPublicationScheduleStatus];


export const MarketingBlogPublicationScheduleStatus = {
  pending: 'pending',
  published: 'published',
  cancelled: 'cancelled',
  failed: 'failed',
} as const;
