/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/** Optional editorial presentation from the dashboard OpenAPI contract. */
export type MarketingBlogPresentation = {
  schemaVersion: 1;
  layout: "editorial";
  eyebrow: string;
  titleParts: Array<{ text: string; emphasis: boolean }>;
  imageAlt: string;
  relatedContent: string;
  structuredData: {
    type: "Article" | "BlogPosting";
    headline: string;
    description: string;
    authorType: "Organization" | "Person";
    publishedDate: string | null;
    modifiedDate: string | null;
  };
};
