/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingFormFieldsItem } from './marketingFormFieldsItem';
import type { MarketingFormKind } from './marketingFormKind';
import type { MarketingFormSettings } from './marketingFormSettings';

export interface MarketingForm {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  kind: MarketingFormKind;
  isSystem: boolean;
  isActive: boolean;
  fields: MarketingFormFieldsItem[];
  settings: MarketingFormSettings;
  createdAt?: string | null;
  updatedAt?: string | null;
}
