/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingFormInputFieldsItem } from './marketingFormInputFieldsItem';
import type { MarketingFormInputKind } from './marketingFormInputKind';
import type { MarketingFormInputSettings } from './marketingFormInputSettings';

export interface MarketingFormInput {
  name: string;
  slug: string;
  description?: string | null;
  kind?: MarketingFormInputKind;
  isSystem?: boolean;
  isActive?: boolean;
  fields?: MarketingFormInputFieldsItem[];
  settings?: MarketingFormInputSettings;
  /** Saved timestamp used for an atomic optimistic update. Required when updating an existing form. */
  expectedUpdatedAt?: string | null;
}
