import type { MarketingBlogCoverImageSet } from "./marketingBlogCoverImageSet";
import type { MarketingBlogPresentation } from "./marketingBlogPresentation";
/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogPost } from "./marketingBlogPost";
import type { MarketingBlogPublicationState } from "./marketingBlogPublicationState";
import type { WebsiteEditorReservation } from "./websiteEditorReservation";

export type MarketingBlogPublicationPost = MarketingBlogPost & {
  presentation?: MarketingBlogPresentation | null;
  coverImageSet?: MarketingBlogCoverImageSet | null;
  publication: MarketingBlogPublicationState;
  lease?: WebsiteEditorReservation;
};
