/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingReportUnavailableCode = typeof MarketingReportUnavailableCode[keyof typeof MarketingReportUnavailableCode];


export const MarketingReportUnavailableCode = {
  invalid_date_range: 'invalid_date_range',
  not_configured: 'not_configured',
  provider_unavailable: 'provider_unavailable',
} as const;
