/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @minimum 1
 */
export type MarketingBlogPublicationPostCoverImageSetOriginalWidth = typeof MarketingBlogPublicationPostCoverImageSetOriginalWidth[keyof typeof MarketingBlogPublicationPostCoverImageSetOriginalWidth];


export const MarketingBlogPublicationPostCoverImageSetOriginalWidth = {
  NUMBER_1408: 1408,
} as const;
