/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @minimum 1
 */
export type MarketingBlogPublicationPostCoverImageSetVariantsItemWidth = typeof MarketingBlogPublicationPostCoverImageSetVariantsItemWidth[keyof typeof MarketingBlogPublicationPostCoverImageSetVariantsItemWidth];


export const MarketingBlogPublicationPostCoverImageSetVariantsItemWidth = {
  NUMBER_480: 480,
  NUMBER_768: 768,
  NUMBER_1280: 1280,
} as const;
