/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @minimum 1
 */
export type MarketingBlogEditorialCoverImageSetVariantsItemHeight = typeof MarketingBlogEditorialCoverImageSetVariantsItemHeight[keyof typeof MarketingBlogEditorialCoverImageSetVariantsItemHeight];


export const MarketingBlogEditorialCoverImageSetVariantsItemHeight = {
  NUMBER_262: 262,
  NUMBER_419: 419,
  NUMBER_698: 698,
} as const;
