/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingEventInputStatus = typeof MarketingEventInputStatus[keyof typeof MarketingEventInputStatus] | null;


export const MarketingEventInputStatus = {
  draft: 'draft',
  published: 'published',
  canceled: 'canceled',
  completed: 'completed',
  archived: 'archived',
} as const;
