/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingRealtimeReports } from './marketingRealtimeReports';
import type { MarketingRealtimeStatus } from './marketingRealtimeStatus';
import type { MarketingRealtimeWindowMinutes } from './marketingRealtimeWindowMinutes';

export interface MarketingRealtime {
  status: MarketingRealtimeStatus;
  fetchedAt: string;
  propertyId: string;
  windowMinutes: MarketingRealtimeWindowMinutes;
  reports: MarketingRealtimeReports;
}
