/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingSeoAuditRecord {
  /** @nullable */
  title: string | null;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  seoTitle?: string | null;
  /** @nullable */
  seoDescription?: string | null;
  /** @nullable */
  ogImageUrl?: string | null;
  /** @nullable */
  canonicalUrl?: string | null;
  /** @nullable */
  coverImageUrl?: string | null;
  /** @nullable */
  authorName?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  visibility?: string | null;
  /** @nullable */
  date?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  id: string;
  /** @nullable */
  noindex?: boolean | null;
  /** @nullable */
  isPublished?: boolean | null;
  issues: string[];
}
