/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingRedirectInputStatusCode = typeof MarketingRedirectInputStatusCode[keyof typeof MarketingRedirectInputStatusCode];


export const MarketingRedirectInputStatusCode = {
  NUMBER_301: 301,
  NUMBER_302: 302,
} as const;
