/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingGalleryInputLayout } from './marketingGalleryInputLayout';
import type { MarketingGalleryInputStatus } from './marketingGalleryInputStatus';
import type { MarketingGalleryItem } from './marketingGalleryItem';
import type { MarketingGallerySettings } from './marketingGallerySettings';

export interface MarketingGalleryInput {
  title: string;
  slug: string;
  /** @nullable */
  description?: string | null;
  status: MarketingGalleryInputStatus;
  layout: MarketingGalleryInputLayout;
  settings: MarketingGallerySettings;
  items: MarketingGalleryItem[];
}
