/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingMediaMetadata {
  /** @maxLength 255 */
  originalName?: string;
  /** @maxLength 255 */
  title?: string;
  /** @maxLength 255 */
  alt?: string;
  /** @maxLength 500 */
  caption?: string;
  /** @maxLength 2000 */
  description?: string;
  /** @maxLength 255 */
  seoTitle?: string;
  /** @maxLength 320 */
  seoDescription?: string;
  /** @maxLength 255 */
  ogTitle?: string;
  /** @maxLength 320 */
  ogDescription?: string;
}
