/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/** Private reviewed image metadata; verification remains server-owned. */
export type MarketingBlogReviewedImage = {
  mediaId: string;
  url: string;
  sha256: string;
  bytes: number;
  mime: "image/png" | "image/webp";
  width: number;
  height: number;
  quality: number | null;
};
