/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogEditorialCoverImageSet } from './marketingBlogEditorialCoverImageSet';
import type { MarketingBlogEditorialPresentation } from './marketingBlogEditorialPresentation';

export interface MarketingBlogEditorial {
  title: string;
  slug: string;
  content: string;
  authorName: string;
  excerpt: string | null;
  coverImageUrl: string | null;
  category: string | null;
  postType: string | null;
  podcastUrl: string | null;
  externalUrl: string | null;
  sidebarId: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImageUrl: string | null;
  categories: string[] | null;
  tags: string[] | null;
  coverImagePositionX: number | null;
  coverImagePositionY: number | null;
  noindex: boolean | null;
  presentation?: MarketingBlogEditorialPresentation;
  /** Private reviewed media metadata. Omission preserves the existing set; null clears it. Original is a 1408x768 PNG; variants are ordered 480, 768, 1280 pixel wide WebP images and defaultMediaId identifies the 1280 variant. Editors cannot manufacture reviewed sets. */
  coverImageSet?: MarketingBlogEditorialCoverImageSet;
}
