/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingEventAudience } from './marketingEventAudience';
import type { MarketingEventCategory } from './marketingEventCategory';
import type { MarketingEventDeliveryMode } from './marketingEventDeliveryMode';
import type { MarketingEventEventType } from './marketingEventEventType';
import type { MarketingEventFormat } from './marketingEventFormat';
import type { MarketingEventRegistrationApprovalMode } from './marketingEventRegistrationApprovalMode';
import type { MarketingEventStatus } from './marketingEventStatus';

export interface MarketingEvent {
  title: string;
  slug: string;
  description?: string | null;
  location?: string | null;
  zoomLink?: string | null;
  imageUrl?: string | null;
  virtualJoinUrl?: string | null;
  virtualDialInInfo?: string | null;
  recordingUrl?: string | null;
  recordingAccess?: string | null;
  registrationType?: string | null;
  registrationCurrency?: string | null;
  status?: MarketingEventStatus;
  visibility?: string | null;
  eventType?: MarketingEventEventType;
  category?: MarketingEventCategory;
  audience?: MarketingEventAudience;
  format?: MarketingEventFormat;
  deliveryMode?: MarketingEventDeliveryMode;
  registrationFormId?: string | null;
  registrationApprovalMode?: MarketingEventRegistrationApprovalMode;
  timezone?: string | null;
  venueId?: string | null;
  organizerId?: string | null;
  locationName?: string | null;
  locationAddress?: string | null;
  latitude?: string | null;
  longitude?: string | null;
  speakerName?: string | null;
  speakerBio?: string | null;
  speakerImageUrl?: string | null;
  recurrencePattern?: string | null;
  recurrenceDaysOfWeek?: string | null;
  parentEventId?: string | null;
  isVirtual?: boolean | null;
  memberOnly?: boolean | null;
  showInArchives?: boolean | null;
  registrationEnabled?: boolean | null;
  waitlistEnabled?: boolean | null;
  isRecurring?: boolean | null;
  imagePositionX?: number | null;
  imagePositionY?: number | null;
  recordingPrice?: number | null;
  registrationFee?: number | null;
  capacity?: number | null;
  recurrenceInterval?: number | null;
  recurrenceCount?: number | null;
  date: string;
  endDate?: string | null;
  registrationOpensAt?: string | null;
  registrationClosesAt?: string | null;
  recurrenceEndDate?: string | null;
  tags?: string[] | null;
  id: string;
  createdAt?: string | null;
}
