/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingGalleryInput } from './marketingGalleryInput';

export type MarketingGallery = MarketingGalleryInput & ({
  id: string;
  imageCount: number;
  /** @nullable */
  authorName?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  publishedAt?: string | null;
});
