/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingGallerySettingsBorderRadius } from './marketingGallerySettingsBorderRadius';
import type { MarketingGallerySettingsCaptionPosition } from './marketingGallerySettingsCaptionPosition';
import type { MarketingGallerySettingsCropMode } from './marketingGallerySettingsCropMode';
import type { MarketingGallerySettingsHoverEffect } from './marketingGallerySettingsHoverEffect';
import type { MarketingGallerySettingsImageRatio } from './marketingGallerySettingsImageRatio';
import type { MarketingGallerySettingsSpacing } from './marketingGallerySettingsSpacing';
import type { MarketingGallerySettingsTransitionEffect } from './marketingGallerySettingsTransitionEffect';

export interface MarketingGallerySettings {
  /**
     * @minimum 1
     * @maximum 6
     */
  columnsDesktop?: number;
  /**
     * @minimum 1
     * @maximum 4
     */
  columnsTablet?: number;
  /**
     * @minimum 1
     * @maximum 2
     */
  columnsMobile?: number;
  /**
     * @minimum 0
     * @maximum 200
     */
  maxImages?: number;
  spacing?: MarketingGallerySettingsSpacing;
  imageRatio?: MarketingGallerySettingsImageRatio;
  cropMode?: MarketingGallerySettingsCropMode;
  borderRadius?: MarketingGallerySettingsBorderRadius;
  transitionEffect?: MarketingGallerySettingsTransitionEffect;
  captionPosition?: MarketingGallerySettingsCaptionPosition;
  hoverEffect?: MarketingGallerySettingsHoverEffect;
  showTitle?: boolean;
  showCaptions?: boolean;
  lightbox?: boolean;
  /** @maxLength 32 */
  arrowIconColor?: string;
  /** @maxLength 32 */
  arrowBackgroundColor?: string;
  /** @maxLength 120 */
  customClassName?: string;
}
