/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingCareerApplicationNotesItem } from './marketingCareerApplicationNotesItem';
import type { MarketingCareerApplicationStatus } from './marketingCareerApplicationStatus';

export interface MarketingCareerApplication {
  id: string;
  jobId: string;
  firstName: string;
  lastName: string;
  email: string;
  resumeFileName?: string;
  resumeMimeType?: string;
  source?: string;
  createdAt?: string;
  updatedAt?: string;
  phone?: string | null;
  coverLetter?: string | null;
  linkedinUrl?: string | null;
  portfolioUrl?: string | null;
  status: MarketingCareerApplicationStatus;
  notes?: MarketingCareerApplicationNotesItem[];
  [key: string]: unknown;
 }
