/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogCommentStatusProperty } from './marketingBlogCommentStatusProperty';

export interface MarketingBlogComment {
  id: string;
  body: string;
  postId: string;
  authorName: string;
  authorEmail?: string | null;
  moderationNote?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  postTitle?: string | null;
  postSlug?: string | null;
  userId?: string | null;
  userAgent?: string | null;
  ipHash?: string | null;
  status: MarketingBlogCommentStatusProperty;
}
