/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBuilderBlockDefaultProps } from './marketingBuilderBlockDefaultProps';
import type { MarketingBuilderProperty } from './marketingBuilderProperty';

export interface MarketingBuilderBlock {
  type: string;
  label: string;
  description: string;
  category: string;
  iconName?: string;
  isDynamic?: boolean;
  defaultProps: MarketingBuilderBlockDefaultProps;
  propDefs: MarketingBuilderProperty[];
}
