/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingCareerJobEmploymentType } from './marketingCareerJobEmploymentType';
import type { MarketingCareerJobIntegrationMetadata } from './marketingCareerJobIntegrationMetadata';
import type { MarketingCareerJobStatus } from './marketingCareerJobStatus';
import type { MarketingCareerJobVisibility } from './marketingCareerJobVisibility';
import type { MarketingCareerJobWorkMode } from './marketingCareerJobWorkMode';

export interface MarketingCareerJob {
  department?: string | null;
  location?: string | null;
  locationAddress?: string | null;
  directoryProfileId?: string | null;
  summary?: string | null;
  description?: string | null;
  requirements?: string | null;
  benefits?: string | null;
  applicationInstructions?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  title: string;
  slug: string;
  salaryCurrency?: string;
  salaryPeriod?: string;
  status: MarketingCareerJobStatus;
  visibility?: MarketingCareerJobVisibility;
  employmentType?: MarketingCareerJobEmploymentType;
  workMode?: MarketingCareerJobWorkMode;
  salaryMin?: number | null;
  salaryMax?: number | null;
  salaryVisible?: boolean;
  noindex?: boolean;
  publishedAt?: string | null;
  closesAt?: string | null;
  integrationMetadata?: MarketingCareerJobIntegrationMetadata;
  id: string;
  createdBy?: string | null;
  updatedBy?: string | null;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: unknown;
 }
