/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingGalleryItem {
  id?: string;
  imageUrl: string;
  /** @nullable */
  mediaId?: string | null;
  /** @nullable */
  alt?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  linkUrl?: string | null;
  /** @nullable */
  ctaText?: string | null;
  /** @nullable */
  tags?: string[] | null;
  sortOrder?: number;
}
