/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingBlogEditorialCoverImageSetOriginal } from './marketingBlogEditorialCoverImageSetOriginal';
import type { MarketingBlogEditorialCoverImageSetSchemaVersion } from './marketingBlogEditorialCoverImageSetSchemaVersion';
import type { MarketingBlogEditorialCoverImageSetVariantsItem } from './marketingBlogEditorialCoverImageSetVariantsItem';

/**
 * Private reviewed media metadata. Omission preserves the existing set; null clears it. Original is a 1408x768 PNG; variants are ordered 480, 768, 1280 pixel wide WebP images and defaultMediaId identifies the 1280 variant. Editors cannot manufacture reviewed sets.
 */
export type MarketingBlogEditorialCoverImageSet = {
  schemaVersion: MarketingBlogEditorialCoverImageSetSchemaVersion;
  /** @pattern ^[a-f0-9]{64}$ */
  sourceFingerprint: string;
  /** @pattern ^[a-f0-9]{64}$ */
  mediaReviewSha256: string;
  original: MarketingBlogEditorialCoverImageSetOriginal;
  /** @pattern ^[A-Za-z0-9_-]{1,160}$ */
  defaultMediaId: string;
  /**
     * @minItems 3
     * @maxItems 3
     */
  variants: MarketingBlogEditorialCoverImageSetVariantsItem[];
} | null;
