/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingMediaAssetKind } from './marketingMediaAssetKind';
import type { MarketingMediaUsageRefsItem } from './marketingMediaUsageRefsItem';

export interface MarketingMedia {
  id: string;
  filename: string;
  originalName: string;
  url: string;
  mimeType: string;
  fileSize: number;
  title?: string | null;
  alt?: string | null;
  caption?: string | null;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  createdAt?: string | null;
  assetKind?: MarketingMediaAssetKind;
  usageCount?: number;
  liveUsageCount?: number;
  isInUse?: boolean;
  usageRefs?: MarketingMediaUsageRefsItem[];
}
