/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingPageMenuReferenceLabelSource } from './marketingPageMenuReferenceLabelSource';

export interface MarketingPageMenuReference {
  menuId: string;
  menuName: string;
  menuLocation: string;
  itemId: string;
  itemLabel: string;
  itemUrl: string;
  labelSource?: MarketingPageMenuReferenceLabelSource;
  depth: number;
}
