/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingSidebarWidgetSettings } from './marketingSidebarWidgetSettings';
import type { MarketingSidebarWidgetType } from './marketingSidebarWidgetType';

export interface MarketingSidebarWidget {
  id: string;
  type: MarketingSidebarWidgetType;
  title: string;
  settings: MarketingSidebarWidgetSettings;
}
