/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { MarketingTeamInputStatus } from './marketingTeamInputStatus';

export interface MarketingTeamInput {
  /** @maxLength 160 */
  name: string;
  /** @maxLength 240 */
  role: string;
  /** @maxLength 30000 */
  biography: string;
  /** @maxLength 1000 */
  excerpt: string;
  /** @maxLength 2000 */
  photoUrl: string;
  /** @maxLength 300 */
  photoAlt: string;
  status: MarketingTeamInputStatus;
}
