/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface MarketingEventAttendee {
  id: string;
  eventId: string;
  fullName: string;
  email: string;
  status: string;
  phone: string | null;
  paymentStatus: string | null;
  notes: string | null;
  checkedInAt: string | null;
  registeredAt: string | null;
  canceledAt: string | null;
  attended: boolean | null;
}
