/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type MarketingCareerJobInputWorkMode = typeof MarketingCareerJobInputWorkMode[keyof typeof MarketingCareerJobInputWorkMode];


export const MarketingCareerJobInputWorkMode = {
  on_site: 'on_site',
  hybrid: 'hybrid',
  remote: 'remote',
} as const;
