/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type NeedsYouItemKind = typeof NeedsYouItemKind[keyof typeof NeedsYouItemKind];


export const NeedsYouItemKind = {
  'completed-work': 'completed-work',
  'old-requests': 'old-requests',
  'agreement-charges': 'agreement-charges',
  'unassigned-work': 'unassigned-work',
  'new-inquiries': 'new-inquiries',
  'client-estimates': 'client-estimates',
} as const;
