/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingDnsResultRecordsItemStatus } from './onboardingDnsResultRecordsItemStatus';
import type { OnboardingDnsResultRecordsItemType } from './onboardingDnsResultRecordsItemType';

export type OnboardingDnsResultRecordsItem = {
  fqdn: string;
  type: OnboardingDnsResultRecordsItemType;
  expectedValue: string;
  status: OnboardingDnsResultRecordsItemStatus;
  observedValues: string[];
  message: string;
};
