/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingDnsResultRecordsItem } from './onboardingDnsResultRecordsItem';
import type { OnboardingDnsResultStatus } from './onboardingDnsResultStatus';
import type { OnboardingReceipt } from './onboardingReceipt';

export interface OnboardingDnsResult {
  status: OnboardingDnsResultStatus;
  records: OnboardingDnsResultRecordsItem[];
  evidence: OnboardingReceipt;
}
