/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingPlanRecordsItem } from './onboardingPlanRecordsItem';
import type { OnboardingReceipt } from './onboardingReceipt';

export interface OnboardingPlan {
  stackId: string;
  publicOrigin: string;
  adminOrigin: string;
  records: OnboardingPlanRecordsItem[];
  manualInstructions: string[];
  rollbackInstructions: string[];
  requiredVerification: string[];
  evidence: OnboardingReceipt;
}
