/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type OnboardingDnsResultRecordsItemStatus = typeof OnboardingDnsResultRecordsItemStatus[keyof typeof OnboardingDnsResultRecordsItemStatus];


export const OnboardingDnsResultRecordsItemStatus = {
  passed: 'passed',
  pending: 'pending',
  failed: 'failed',
  'manual-review': 'manual-review',
} as const;
