/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingPlanInputAdminRecord } from './onboardingPlanInputAdminRecord';
import type { OnboardingPlanInputCanonicalHost } from './onboardingPlanInputCanonicalHost';
import type { OnboardingPlanInputPublicRecordsItem } from './onboardingPlanInputPublicRecordsItem';
import type { OnboardingPlanInputRoutingMode } from './onboardingPlanInputRoutingMode';

export interface OnboardingPlanInput {
  /**
     * @maxLength 120
     * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
     */
  stackId: string;
  publicDomain: string;
  adminDomain: string;
  canonicalHost: OnboardingPlanInputCanonicalHost;
  publicRecords: OnboardingPlanInputPublicRecordsItem[];
  adminRecord: OnboardingPlanInputAdminRecord;
  dnsOperator: string;
  launchOwner: string;
  routingMode: OnboardingPlanInputRoutingMode;
}
