/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingReadinessInputChecksAdminRouting } from './onboardingReadinessInputChecksAdminRouting';
import type { OnboardingReadinessInputChecksApplicationHealth } from './onboardingReadinessInputChecksApplicationHealth';
import type { OnboardingReadinessInputChecksAuthoritativeDns } from './onboardingReadinessInputChecksAuthoritativeDns';
import type { OnboardingReadinessInputChecksCanonicalRedirect } from './onboardingReadinessInputChecksCanonicalRedirect';
import type { OnboardingReadinessInputChecksCertificate } from './onboardingReadinessInputChecksCertificate';
import type { OnboardingReadinessInputChecksOwnership } from './onboardingReadinessInputChecksOwnership';
import type { OnboardingReadinessInputChecksPublicRouting } from './onboardingReadinessInputChecksPublicRouting';
import type { OnboardingReadinessInputChecksRollbackPlan } from './onboardingReadinessInputChecksRollbackPlan';
import type { OnboardingReadinessInputChecksSameOriginApi } from './onboardingReadinessInputChecksSameOriginApi';

export type OnboardingReadinessInputChecks = {
  ownership: OnboardingReadinessInputChecksOwnership;
  authoritativeDns: OnboardingReadinessInputChecksAuthoritativeDns;
  certificate: OnboardingReadinessInputChecksCertificate;
  publicRouting: OnboardingReadinessInputChecksPublicRouting;
  adminRouting: OnboardingReadinessInputChecksAdminRouting;
  sameOriginApi: OnboardingReadinessInputChecksSameOriginApi;
  applicationHealth: OnboardingReadinessInputChecksApplicationHealth;
  canonicalRedirect: OnboardingReadinessInputChecksCanonicalRedirect;
  rollbackPlan: OnboardingReadinessInputChecksRollbackPlan;
};
