/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingPlanInputAdminRecordProxyMode } from './onboardingPlanInputAdminRecordProxyMode';
import type { OnboardingPlanInputAdminRecordType } from './onboardingPlanInputAdminRecordType';

export type OnboardingPlanInputAdminRecord = {
  type: OnboardingPlanInputAdminRecordType;
  value: string;
  /**
     * @minimum 60
     * @maximum 86400
     */
  ttl: number;
  proxyMode: OnboardingPlanInputAdminRecordProxyMode;
};
