/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type OnboardingDnsInputRecordsItemType = typeof OnboardingDnsInputRecordsItemType[keyof typeof OnboardingDnsInputRecordsItemType];


export const OnboardingDnsInputRecordsItemType = {
  A: 'A',
  AAAA: 'AAAA',
  ALIAS: 'ALIAS',
  ANAME: 'ANAME',
  CNAME: 'CNAME',
} as const;
