/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { OnboardingReadinessResultStatus } from './onboardingReadinessResultStatus';
import type { OnboardingReceipt } from './onboardingReceipt';

export interface OnboardingReadinessResult {
  status: OnboardingReadinessResultStatus;
  passed: string[];
  pending: string[];
  failed: string[];
  evidence: OnboardingReceipt;
}
