/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectPhaseTransitionStatus } from './projectPhaseTransitionStatus';

export interface ProjectPhaseTransition {
  /** @minimum 1 */
  expectedVersion: number;
  status: ProjectPhaseTransitionStatus;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  reason: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  overrideReason?: string;
}
