/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type ProjectPhaseTransitionReceiptStatus = typeof ProjectPhaseTransitionReceiptStatus[keyof typeof ProjectPhaseTransitionReceiptStatus];


export const ProjectPhaseTransitionReceiptStatus = {
  planned: 'planned',
  ready: 'ready',
  in_progress: 'in_progress',
  manager_review: 'manager_review',
  accepted: 'accepted',
  blocked: 'blocked',
  cancelled: 'cancelled',
  archived: 'archived',
} as const;
