/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectPhasePrerequisite } from './projectPhasePrerequisite';

export interface ProjectPhaseDetails {
  /**
     * @minLength 1
     * @maxLength 500
     */
  title: string;
  /** @maxLength 10000 */
  scope?: string;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  plannedStart?: string | null;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  plannedEnd?: string | null;
  /** @maxItems 100 */
  prerequisites?: ProjectPhasePrerequisite[];
}
