/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectPhaseEventDetails } from './projectPhaseEventDetails';
import type { ProjectPhaseEventEventType } from './projectPhaseEventEventType';

export interface ProjectPhaseEvent {
  id: string;
  phase_id: string;
  actor_id: string;
  event_type: ProjectPhaseEventEventType;
  /**
     * @minimum 1
     * @nullable
     */
  prior_version: number | null;
  /** @minimum 1 */
  resulting_version: number;
  /** @nullable */
  from_status?: string | null;
  /** @nullable */
  to_status?: string | null;
  /** @nullable */
  reason?: string | null;
  details: ProjectPhaseEventDetails;
  created_at: string;
}
