/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectPhasePrerequisite } from './projectPhasePrerequisite';
import type { ProjectPhaseStatus } from './projectPhaseStatus';

export interface ProjectPhase {
  id: string;
  project_id: string;
  /** @minimum 0 */
  position: number;
  title: string;
  /** Operational/crew-only scope; omitted from client publications. */
  scope?: string;
  status: ProjectPhaseStatus;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  planned_start?: string | null;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  planned_end?: string | null;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  actual_start?: string | null;
  /**
     * @nullable
     * @pattern ^\d{4}-\d{2}-\d{2}$
     */
  actual_end?: string | null;
  /** Operational/crew-only prerequisites; omitted from client publications. */
  prerequisites?: ProjectPhasePrerequisite[];
  /**
     * Operational override record; omitted from client/crew projections.
     * @nullable
     */
  override_reason?: string | null;
  /**
     * Optimistic concurrency version; omitted from client/crew projections.
     * @minimum 1
     */
  version?: number;
  /**
     * Client-visible only after explicit publication.
     * @nullable
     */
  published_summary?: string | null;
  /** @nullable */
  published_at?: string | null;
  project_name: string;
  property_name: string;
}
