/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { LegacyProjectPhase } from './legacyProjectPhase';

export interface Project {
  /** @nullable */
  id: string | null;
  property_id?: string;
  name: string;
  scope: string;
  /** Legacy project status. The project-phase lifecycle is the authoritative detailed execution state. */
  status: string;
  phases: LegacyProjectPhase[];
  /** @minimum 1 */
  version: number;
  created_at: string;
  property_name?: string;
  /** Staff-only participating-property summary. */
  property_names: string;
  /** Staff-only participating-client summary. */
  client_names?: string;
}
