/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface ProjectPhaseCreateReceipt {
  id: string;
  /** @minimum 1 */
  version: number;
  /** @minimum 0 */
  position: number;
}
