/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectPhaseBillingIntentKind } from './projectPhaseBillingIntentKind';
import type { ProjectPhaseBillingIntentStatus } from './projectPhaseBillingIntentStatus';

export interface ProjectPhaseBillingIntent {
  operation_id: string;
  /** @minimum 1 */
  expected_phase_version: number;
  kind: ProjectPhaseBillingIntentKind;
  created_at: string;
  billing_draft_id: string;
  title: string;
  amount_cents: number;
  status: ProjectPhaseBillingIntentStatus;
  /** @nullable */
  quickbooks_id: string | null;
}
