/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type ProjectPhaseEventEventType = typeof ProjectPhaseEventEventType[keyof typeof ProjectPhaseEventEventType];


export const ProjectPhaseEventEventType = {
  created: 'created',
  updated: 'updated',
  transitioned: 'transitioned',
  published: 'published',
  billing_intent_created: 'billing_intent_created',
} as const;
