/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { PropertyTimelineEventKind } from './propertyTimelineEventKind';
import type { PropertyTimelineEventPayload } from './propertyTimelineEventPayload';

export interface PropertyTimelineEvent {
  id: string;
  kind: PropertyTimelineEventKind;
  /** Stored JSONB; shared field-event payload describes current writes, avoid narrowing historical reads without evidence */
  payload: PropertyTimelineEventPayload;
  conflict: boolean;
  published: boolean;
  captured_at: string;
  title: string;
}
