/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ClientContact } from './clientContact';
import type { ClientNote } from './clientNote';
import type { PropertyWorkspaceAgreementsItem } from './propertyWorkspaceAgreementsItem';
import type { PropertyWorkspaceFilesItem } from './propertyWorkspaceFilesItem';
import type { PropertyWorkspaceInspectionsItem } from './propertyWorkspaceInspectionsItem';
import type { PropertyWorkspaceProjectsItem } from './propertyWorkspaceProjectsItem';
import type { PropertyWorkspaceProperty } from './propertyWorkspaceProperty';
import type { PropertyWorkspaceRequestsItem } from './propertyWorkspaceRequestsItem';
import type { PropertyWorkspaceScheduleItem } from './propertyWorkspaceScheduleItem';

export interface PropertyWorkspace {
  property: PropertyWorkspaceProperty;
  schedule: PropertyWorkspaceScheduleItem[];
  agreements: PropertyWorkspaceAgreementsItem[];
  requests: PropertyWorkspaceRequestsItem[];
  projects: PropertyWorkspaceProjectsItem[];
  inspections: PropertyWorkspaceInspectionsItem[];
  files: PropertyWorkspaceFilesItem[];
  contacts: ClientContact[];
  notes: ClientNote[];
}
