/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface RecordExternalInvoice {
  operationId: string;
  /** @minimum 1 */
  expectedVersion: number;
  /** @minimum 1 */
  expectedAmountCents: number;
  /**
     * @minLength 1
     * @maxLength 120
     */
  reference?: string;
  invoicedOn: string;
  /** @maxLength 2000 */
  note?: string;
}
