/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringBillingPeriod } from './recurringBillingPeriod';
import type { RecurringJobConfigurationBillingMode } from './recurringJobConfigurationBillingMode';
import type { RecurringJobConfigurationCadence } from './recurringJobConfigurationCadence';

export interface RecurringJobConfiguration {
  cadence: RecurringJobConfigurationCadence;
  /**
     * @minimum 1
     * @maximum 52
     */
  intervalCount: number;
  startsOn: string;
  endsOn: string;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  localTime: string;
  billingMode: RecurringJobConfigurationBillingMode;
  /**
     * @minimum 1
     * @nullable
     */
  unitAmountCents: number | null;
  /** @maxItems 120 */
  periods: RecurringBillingPeriod[];
}
