/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringJobConfigurationBillingMode } from './recurringJobConfigurationBillingMode';
import type { RecurringJobConfigurationCadence } from './recurringJobConfigurationCadence';
import type { RecurringJobConfigurationPeriodsItem } from './recurringJobConfigurationPeriodsItem';

export interface RecurringJobConfiguration {
  cadence: RecurringJobConfigurationCadence;
  /**
     * @minimum 1
     * @maximum 52
     */
  intervalCount: number;
  startsOn: string;
  endsOn: string;
  localTime: string;
  billingMode: RecurringJobConfigurationBillingMode;
  /** @nullable */
  unitAmountCents: number | null;
  periods: RecurringJobConfigurationPeriodsItem[];
}
