/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { RecurringJobCadence } from './recurringJobCadence';

export interface RecurringJob {
  id: string;
  property_id: string;
  title: string;
  cadence: RecurringJobCadence;
  interval_count: number;
  next_date: string;
  local_time: string;
  paused: boolean;
  /** @nullable */
  agreement_status?: string | null;
  /** @nullable */
  next_visit?: string | null;
  /** Operational authorization status for the next occurrence. */
  generation_status?: string;
  /**
     * @minimum 0
     * @nullable
     */
  visit_allowance?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  visits_reserved?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  visits_remaining?: number | null;
}
