/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface SalesInquiry {
  name: string;
  location: string;
  description: string;
  status: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  source: string | null;
  /** @nullable */
  inquiry_type: string | null;
  /** @nullable */
  owner_id: string | null;
  /** @nullable */
  owner_name: string | null;
  /** @nullable */
  next_action: string | null;
  /** @nullable */
  reported_company_name: string | null;
  id: string;
  /** @nullable */
  next_action_due_at: string | null;
  created_at: string;
  version: number;
  /** @nullable */
  converted_client_id: string | null;
  /** @nullable */
  converted_property_id: string | null;
}
