/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { SalesPipelineConfigStagesItemColor } from './salesPipelineConfigStagesItemColor';
import type { SalesPipelineConfigStagesItemKey } from './salesPipelineConfigStagesItemKey';

export type SalesPipelineConfigStagesItem = {
  key: SalesPipelineConfigStagesItemKey;
  /**
     * @minLength 1
     * @maxLength 40
     */
  label: string;
  color: SalesPipelineConfigStagesItemColor;
};
