/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Operational lead snapshot. Additional persisted fields remain intentionally forward-compatible.
 */
export interface SalesLead {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  location: string;
  description: string;
  /** @nullable */
  source?: string | null;
  status: string;
  created_at: string;
  /** @nullable */
  converted_client_id?: string | null;
  /** @nullable */
  converted_property_id?: string | null;
  [key: string]: unknown;
 }
