/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceRequestEventDetails } from './serviceRequestEventDetails';
import type { ServiceRequestEventEventType } from './serviceRequestEventEventType';

export interface ServiceRequestEvent {
  id: string;
  service_request_id: string;
  actor_id: string;
  event_type: ServiceRequestEventEventType;
  /**
     * @minimum 1
     * @nullable
     */
  prior_version: number | null;
  /** @minimum 1 */
  resulting_version: number;
  /** @nullable */
  from_status?: string | null;
  /** @nullable */
  to_status?: string | null;
  /** @nullable */
  reason?: string | null;
  details: ServiceRequestEventDetails;
  created_at: string;
}
