/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface ServiceRequestLifecycle {
  id: string;
  property_id: string;
  /** Operational submitter identity. Omitted from client responses. */
  user_id?: string;
  description: string;
  /** Office roles receive the operational lifecycle status. Clients receive a safe, non-dispatch/non-billing status label. */
  status: string;
  /**
     * Optimistic concurrency version. Omitted from client-safe projections.
     * @minimum 1
     */
  version?: number;
  created_at: string;
  /** Most recent lifecycle update. Omitted where unavailable on historical records. */
  updated_at?: string;
  property_name: string;
}
