/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceRequestConversionPreviewWorkOrder } from './serviceRequestConversionPreviewWorkOrder';
import type { ServiceRequestLifecycle } from './serviceRequestLifecycle';

export interface ServiceRequestConversionPreview {
  request: ServiceRequestLifecycle;
  workOrder: ServiceRequestConversionPreviewWorkOrder;
  /** @maxItems 0 */
  providerActions: unknown[];
}
