/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPeriod } from './agreementPeriod';
import type { ServiceAgreementFinancialBillingMode } from './serviceAgreementFinancialBillingMode';
import type { ServiceAgreementFinancialStatus } from './serviceAgreementFinancialStatus';

export interface ServiceAgreementFinancial {
  id: string;
  propertyId: string;
  recurringServiceId: string;
  title: string;
  startsOn: string;
  endsOn: string;
  status: ServiceAgreementFinancialStatus;
  scope: string;
  cancellationEffectiveOn: string | null;
  /** @exclusiveMinimum 0 */
  version: number;
  estimateId: string;
  /** @exclusiveMinimum 0 */
  estimateRevision: number;
  predecessorId: string | null;
  billingMode: ServiceAgreementFinancialBillingMode;
  unitAmountCents: number | null;
  activatedOn: string | null;
  cancellationReason: string | null;
  periods: AgreementPeriod[];
}
