/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceRequestWorkItem } from './serviceRequestWorkItem';

export interface ServiceRequestConversionPreviewInput {
  /**
     * @minLength 1
     * @maxLength 500
     */
  title: string;
  /** @maxLength 10000 */
  scope?: string;
  /** @maxItems 100 */
  checklist?: ServiceRequestWorkItem[];
  /** @maxItems 50 */
  prerequisites?: ServiceRequestWorkItem[];
}
