/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementPeriodInput } from './agreementPeriodInput';
import type { ServiceAgreementTermsBillingMode } from './serviceAgreementTermsBillingMode';

/**
 * Finite term of at most120 calendar months. Monthly periods must exactly partition the term in calendar-month order with explicit partial-period amounts and null unitAmountCents. Per-visit terms require a rate and an empty period list. Server cross-field validation is authoritative.
 */
export interface ServiceAgreementTerms {
  /**
     * @minLength 1
     * @maxLength 500
     */
  title: string;
  startsOn: string;
  endsOn: string;
  billingMode: ServiceAgreementTermsBillingMode;
  unitAmountCents: number | null;
  /** @maxItems 120 */
  periods: AgreementPeriodInput[];
}
