/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceRequestConversionPreviewInput } from './serviceRequestConversionPreviewInput';

export type ServiceRequestConversion = ServiceRequestConversionPreviewInput & {
  operationId: string;
  /** @minimum 1 */
  expectedRequestVersion: number;
};
