/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceRequestConversionPreviewWorkOrderStatus } from './serviceRequestConversionPreviewWorkOrderStatus';
import type { ServiceRequestWorkItem } from './serviceRequestWorkItem';

export type ServiceRequestConversionPreviewWorkOrder = {
  propertyId: string;
  title: string;
  scope: string;
  checklist: ServiceRequestWorkItem[];
  prerequisites: ServiceRequestWorkItem[];
  status: ServiceRequestConversionPreviewWorkOrderStatus;
  /** @nullable */
  assignedTo: null;
  /** @nullable */
  scheduledAt: null;
};
