/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementDraftContent } from './agreementDraftContent';
import type { AgreementDraftDates } from './agreementDraftDates';

export interface UpdateAgreementDraft {
  /** @minimum 1 */
  expectedVersion: number;
  title: string;
  content: AgreementDraftContent;
  dates: AgreementDraftDates;
}
