/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { ClientPrimaryContact } from './clientPrimaryContact';

export interface UpdateDashboardClient {
  /**
     * @minLength 1
     * @maxLength 10000
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  address: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  phone: string;
  /**
     * @maxLength 254
     * @nullable
     */
  email: string | null;
  /** @minimum 1 */
  version: number;
  primaryContact: ClientPrimaryContact;
}
