/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { AgreementTemplatePayload } from './agreementTemplatePayload';

export interface UpdateAgreementTemplate {
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  description?: string;
  body: string;
  payload: AgreementTemplatePayload;
  /** @minimum 1 */
  expectedEditVersion: number;
}
