/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { UploadFieldPhotoXP1Classification } from './uploadFieldPhotoXP1Classification';

export type UploadFieldPhotoHeaders = {
'x-p1-property': string;
'x-p1-work': string;
'x-p1-classification'?: UploadFieldPhotoXP1Classification;
};
