/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type UploadFieldPhotoXP1Classification = typeof UploadFieldPhotoXP1Classification[keyof typeof UploadFieldPhotoXP1Classification];


export const UploadFieldPhotoXP1Classification = {
  before: 'before',
  during: 'during',
  after: 'after',
  issue: 'issue',
  general: 'general',
} as const;
