/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteMenuItemAction } from './websiteMenuItemAction';
import type { WebsiteMenuItemLabelSource } from './websiteMenuItemLabelSource';

export interface WebsiteMenuItem {
  id: string;
  /** @minLength 1 */
  label: string;
  /** @minLength 1 */
  url: string;
  openInNewTab: boolean;
  action?: WebsiteMenuItemAction;
  pageId?: string | null;
  labelSource?: WebsiteMenuItemLabelSource;
  formSlug?: string | null;
  modalTitle?: string | null;
  modalDescription?: string | null;
  children: WebsiteMenuItem[];
}
