/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteSocialChanges {
  social_facebook_url?: string;
  social_instagram_url?: string;
  social_linkedin_url?: string;
  social_x_url?: string;
  social_tiktok_url?: string;
  social_youtube_url?: string;
  social_pinterest_url?: string;
  social_houzz_url?: string;
  social_yelp_url?: string;
  social_nextdoor_url?: string;
  social_icon_style?: string;
}
