/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteColors {
  brand_primary_color: string;
  brand_secondary_color: string;
  brand_tertiary_color: string;
  brand_quaternary_color: string;
  text_h1_color: string;
  text_h2_color: string;
  text_h3_h6_color: string;
  text_body_color: string;
  text_heading_subtext_color: string;
  text_supporting_copy_color: string;
  text_helper_text_color: string;
  text_meta_color: string;
  text_link_color: string;
  text_link_hover_color: string;
  text_inverse_color: string;
  text_primary_foreground_color: string;
  text_secondary_foreground_color: string;
  text_tertiary_foreground_color: string;
}
