/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteIdentityChanges {
  /** @maxLength 255 */
  company_name?: string;
  /** @maxLength 2000 */
  company_address?: string;
  /** @maxLength 2000 */
  company_phone_numbers?: string;
  /** @maxLength 2048 */
  company_google_business_url?: string;
  /** @maxLength 2048 */
  frontend_logo_url?: string;
  /** @maxLength 2048 */
  favicon_url?: string;
}
