/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WebsiteIntegrationsBackupsEffectiveSource = typeof WebsiteIntegrationsBackupsEffectiveSource[keyof typeof WebsiteIntegrationsBackupsEffectiveSource];


export const WebsiteIntegrationsBackupsEffectiveSource = {
  BACKUP_S3: 'BACKUP_S3',
  S3: 'S3',
  BACKUP_R2: 'BACKUP_R2',
  settings: 'settings',
} as const;
