/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteEmailTemplate {
  id: string;
  slug: string;
  name: string;
  module: string;
  subject: string;
  htmlBody: string;
  description: string;
  version: string;
  variables: string[];
  isActive: boolean;
  updatedAt: string | null;
}
