/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteIdentitySettings {
  company_name: string;
  company_address: string;
  company_phone_numbers: string;
  company_google_business_url: string;
  frontend_logo_url: string;
  favicon_url: string;
}
