/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteIntegrationSecretsMailchimpApiKey } from './websiteIntegrationSecretsMailchimpApiKey';
import type { WebsiteIntegrationSecretsMailgunApiKey } from './websiteIntegrationSecretsMailgunApiKey';
import type { WebsiteIntegrationSecretsR2AccessKeyId } from './websiteIntegrationSecretsR2AccessKeyId';
import type { WebsiteIntegrationSecretsR2SecretAccessKey } from './websiteIntegrationSecretsR2SecretAccessKey';

export interface WebsiteIntegrationSecrets {
  mailgun_api_key?: WebsiteIntegrationSecretsMailgunApiKey;
  mailchimp_api_key?: WebsiteIntegrationSecretsMailchimpApiKey;
  r2_access_key_id?: WebsiteIntegrationSecretsR2AccessKeyId;
  r2_secret_access_key?: WebsiteIntegrationSecretsR2SecretAccessKey;
}
