/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteBackupSummaryReason } from './websiteBackupSummaryReason';
import type { WebsiteBackupSummarySchemaVersion } from './websiteBackupSummarySchemaVersion';
import type { WebsiteBackupSummaryStorageSource } from './websiteBackupSummaryStorageSource';

export interface WebsiteBackupSummary {
  schemaVersion: WebsiteBackupSummarySchemaVersion;
  clientStackId: string | null;
  key: string;
  createdAt: string;
  reason: WebsiteBackupSummaryReason;
  appVersion: string;
  gitCommitSha: string | null;
  environment: string;
  storageSource: WebsiteBackupSummaryStorageSource;
  /** @minimum 0 */
  tableCount: number;
  /** @minimum 0 */
  totalRowCount: number;
  /** @minimum 0 */
  mediaAssetCount: number;
}
