/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteDocumentInput {
  /**
     * @minLength 1
     * @maxLength 255
     */
  title: string;
  /**
     * @maxLength 160
     * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
     */
  slug: string;
  /**
     * @minLength 1
     * @maxLength 120
     */
  category: string;
  /** @maxLength 500000 */
  content: string;
  /**
     * @minimum -100000
     * @maximum 100000
     */
  sortOrder: number;
  isPublished: boolean;
}
