/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteBackupStorage } from './websiteBackupStorage';
import type { WebsiteBackupSummary } from './websiteBackupSummary';

export interface WebsiteBackupStatus {
  enabled: boolean;
  configured: boolean;
  /** @minimum 1 */
  intervalHours: number;
  /** @minimum 1 */
  retentionDays: number;
  /** @minimum 1 */
  maxSnapshots: number;
  storage: WebsiteBackupStorage | null;
  latest: WebsiteBackupSummary | null;
  recent: WebsiteBackupSummary[];
}
