/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WebsiteEditorReservationStatus = typeof WebsiteEditorReservationStatus[keyof typeof WebsiteEditorReservationStatus];


export const WebsiteEditorReservationStatus = {
  acquired: 'acquired',
  locked_by_other: 'locked_by_other',
  expired_available: 'expired_available',
} as const;
