/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export interface WebsiteColorChanges {
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  brand_primary_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  brand_secondary_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  brand_tertiary_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  brand_quaternary_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_h1_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_h2_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_h3_h6_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_body_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_heading_subtext_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_supporting_copy_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_helper_text_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_meta_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_link_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_link_hover_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_inverse_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_primary_foreground_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_secondary_foreground_color?: string;
  /** @pattern ^(?:#[0-9a-fA-F]{6})?$ */
  text_tertiary_foreground_color?: string;
}
