/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WebsiteIntegrationTestResultCode = typeof WebsiteIntegrationTestResultCode[keyof typeof WebsiteIntegrationTestResultCode];


export const WebsiteIntegrationTestResultCode = {
  connection_verified: 'connection_verified',
  connection_unavailable: 'connection_unavailable',
  invalid_configuration: 'invalid_configuration',
} as const;
