/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteMenuItem } from './websiteMenuItem';

export interface WebsiteMenu {
  id: string;
  /** @minLength 1 */
  name: string;
  location: string;
  items: WebsiteMenuItem[];
  createdAt?: string | null;
  updatedAt?: string | null;
  /** @minimum 1 */
  version: number;
}
