/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WebsiteMenuItemAction = typeof WebsiteMenuItemAction[keyof typeof WebsiteMenuItemAction];


export const WebsiteMenuItemAction = {
  'internal-link': 'internal-link',
  'custom-link': 'custom-link',
  'form-modal': 'form-modal',
} as const;
