/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteContentComponent } from './websiteContentComponent';
import type { WebsiteContentDraftContent } from './websiteContentDraftContent';
import type { WebsiteContentOwnedBlog } from './websiteContentOwnedBlog';
import type { WebsiteContentRoute } from './websiteContentRoute';

export interface WebsiteContent {
  stackId: string;
  route: WebsiteContentRoute;
  component: WebsiteContentComponent;
  previewUrl: string;
  draftContent: WebsiteContentDraftContent;
  /** @minimum 0 */
  draftRevision: number;
  publishedRevision: number | null;
  publishedAt: string | null;
  /** Permanent Blog ownership. Structured Website fields and revisions are retained read-only. */
  ownedBlog?: WebsiteContentOwnedBlog;
}
