/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteIntegrationSecretInput } from './websiteIntegrationSecretInput';

export type WebsiteIntegrationSaveFields = {
  mailgun_domain?: string;
  mailgun_from_address?: string;
  mailchimp_audience_id?: string;
  mailchimp_server_prefix?: string;
  r2_account_id?: string;
  r2_bucket_name?: string;
  r2_public_url?: string;
  mailgun_api_key?: WebsiteIntegrationSecretInput;
  mailchimp_api_key?: WebsiteIntegrationSecretInput;
  r2_access_key_id?: WebsiteIntegrationSecretInput;
  r2_secret_access_key?: WebsiteIntegrationSecretInput;
};
