/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WebsiteIntegrationConfigurationManagement } from './websiteIntegrationConfigurationManagement';
import type { WebsiteIntegrationEffectiveSource } from './websiteIntegrationEffectiveSource';
import type { WebsiteIntegrationFields } from './websiteIntegrationFields';
import type { WebsiteIntegrationProvider } from './websiteIntegrationProvider';
import type { WebsiteIntegrationSecrets } from './websiteIntegrationSecrets';

export interface WebsiteIntegration {
  provider: WebsiteIntegrationProvider;
  version: string;
  effectiveSource: WebsiteIntegrationEffectiveSource;
  fields: WebsiteIntegrationFields;
  secrets: WebsiteIntegrationSecrets;
  configurationManagement: WebsiteIntegrationConfigurationManagement;
  /** @nullable */
  configurationIssue: string | null;
  testEffects: string;
}
