/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WebsiteMenuItemLabelSource = typeof WebsiteMenuItemLabelSource[keyof typeof WebsiteMenuItemLabelSource];


export const WebsiteMenuItemLabelSource = {
  page: 'page',
  custom: 'custom',
} as const;
