/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */

export type WorkOrderJobKind = typeof WorkOrderJobKind[keyof typeof WorkOrderJobKind];


export const WorkOrderJobKind = {
  one_time: 'one_time',
  recurring_visit: 'recurring_visit',
  internal: 'internal',
} as const;
