/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Initial shared field-client contract. Additional office routes are documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderChecklistItem } from './workOrderChecklistItem';

export interface WorkOrder {
  id: string;
  property_id: string;
  property_name: string;
  title: string;
  scope?: string;
  status: string;
  version?: number;
  /** @nullable */
  scheduled_at?: string | null;
  address?: string;
  access_instructions?: string;
  checklist?: WorkOrderChecklistItem[];
  published?: boolean;
}
