/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type { WorkOrderChecklistItem } from './workOrderChecklistItem';

/**
 * Authorized work projection. Clients receive only identity, property name, title, scheduled_at and public status; operational fields are absent, not null placeholders.
 */
export interface WorkOrder {
  id: string;
  property_id: string;
  property_name: string;
  title: string;
  scope?: string;
  status: string;
  version?: number;
  /** @nullable */
  scheduled_at?: string | null;
  address?: string;
  access_instructions?: string;
  checklist?: WorkOrderChecklistItem[];
  published?: boolean;
  /** @nullable */
  assigned_to?: string | null;
}
