// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/p1-redesign/Earthwork.tsx": () => import("../components/mockups/p1-redesign/Earthwork.tsx"),
  "./components/mockups/p1-redesign/Editorial.tsx": () => import("../components/mockups/p1-redesign/Editorial.tsx"),
  "./components/mockups/p1-redesign/Topographic.tsx": () => import("../components/mockups/p1-redesign/Topographic.tsx")
};
