import {CommercialInbox,type CommercialInboxApi} from "../src/CommercialInbox";
import {createRoot} from 'react-dom/client';
import {CommercialContextPanel} from '../src/CommercialContextPanel';
import {ContextError,type ContextTransport,type Context,type ContextInput} from '../src/commercial-context.types';
import '../src/style.css';
const root=createRoot(document.getElementById('root')!);let assertions=0;
function check(value:unknown,label:string){if(!value)throw Error(label);assertions++;}
const tick=()=>new Promise(resolve=>setTimeout(resolve,35));
function button(text:string){const found=[...document.querySelectorAll('button')].find(el=>el.textContent?.trim()===text);if(!found)throw Error('Missing button '+text);return found;}
function control(label:string){const found=[...document.querySelectorAll('label')].find(el=>[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').replace(/\s+/g,' ').trim()===label)?.querySelector('input,select,textarea');if(!found)throw Error('Missing control '+label);return found as HTMLInputElement|HTMLSelectElement;}
async function fill(label:string,value:string){const el=control(label);Object.getOwnPropertyDescriptor(el instanceof HTMLSelectElement?HTMLSelectElement.prototype:el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLSelectElement?'change':'input',{bubbles:true}));await tick();}
let state:Context={lead:{id:'first',version:1,status:'new',organization_id:null,contact_id:null,property_id:null},intake:{submission_id:'original-receipt',raw_intake:{name:'Original immutable person',company:'Original reported company'}},organization:null,contact:null,property:null};
const calls:ContextInput[]=[],versions:number[]=[];let getFailure=false,oldSearch:((value:any)=>void)|null=null,saveRelease:(()=>void)|null=null;
const api:ContextTransport={get:async()=>{if(getFailure){getFailure=false;throw Error('Read temporarily unavailable');}return structuredClone(state);},save:async(_id,body)=>{calls.push(structuredClone(body));if(calls.length<=2)throw Error('Temporary delivery error');if(calls.length===3)throw new ContextError('Inquiry changed',409);await new Promise<void>(r=>{saveRelease=r;});state={...state,lead:{...state.lead,version:3,organization_id:'company-b',contact_id:'contact',property_id:null},organization:{id:'company-b',display_name:'Selected B',version:1,archived:false},contact:{id:'contact',name:'Reviewed person',email:null,phone:'7045550100',version:1,archived:false,client_id:null,reviewed_by:'staff',reviewed_at:null,channel_source:'Direct call'}};return{leadId:'first',version:3,organizationId:'company-b',contactId:'contact',propertyId:null};},review:async(_id,b)=>{check(b.expectedVersion===3&&b.contactVersion===1,'Contact correction carries both versions');state={...state,lead:{...state.lead,version:4},contact:{...state.contact!,...b.contact,version:2}};return{leadId:'first',version:4,contactId:'contact',contactVersion:2};},search:async q=>{if(q.q==='slow')return new Promise(r=>{oldSearch=r;});return{items:[{id:q.after?'company-c':'company-b',display_name:q.after?'Selected C':'Selected B',version:1}],nextCursor:q.after?null:'company-b'};}};
const render=(id='first',transport=api)=>root.render(<CommercialContextPanel leadId={id} api={transport} onMutationAck={ack=>versions.push(ack.newVersion)}/>);
async function draft(){await fill('Company name','Reviewed company');await fill('Contact name','Reviewed person');await fill('Contact phone','7045550100');await fill('How were these details reviewed?','Direct call');}
async function run(){
 render();for(let i=0;i<40&&!document.querySelector('.context-form');i++)await tick();await draft();button('Save reviewed links').click();await tick();check(control('Company name').value==='Reviewed company','Network error retains entered fields');check(calls.length===1,'One save dispatched');button('Save reviewed links').click();await tick();check(calls[0].operationId===calls[1].operationId&&JSON.stringify(calls[0])===JSON.stringify(calls[1]),'Exact unchanged retry body and operation ID retained');check(calls[0].property===null&&'create'in calls[0].contact&&calls[0].contact.create.email===null,'Phone-only and absent property remain null');
 await fill('Company name','Changed company');button('Save reviewed links').click();await tick();check(calls[2].operationId!==calls[1].operationId,'Changed body gets new operation ID');check(control('Company name').value==='Changed company','Conflict retains fields');check(button('Save reviewed links').disabled,'Conflict requires explicit refresh');state={...state,lead:{...state.lead,version:2}};button('Reload saved context and discard edits').click();await tick();check(control('Company name').value==='','Explicit reload discards edits');
 await fill('Choose how to link company','existing');await fill('Search company','slow');button('Search company').click();await tick();await fill('Search company','fresh');button('Search company').click();await tick();oldSearch?.({items:[{id:'stale',display_name:'Stale A',version:1}],nextCursor:null});await tick();check(!document.body.textContent?.includes('Stale A'),'Late search response cannot replace new results');button('Load more company').click();await tick();check(document.body.textContent?.includes('Selected C'),'Search pagination reaches next page');const result=[...document.querySelectorAll('.context-picker li button')].find(el=>el.textContent?.startsWith('Selected B')) as HTMLButtonElement;result.click();await tick();check(document.querySelector('[aria-pressed=true]')?.textContent?.includes('Selected B'),'Existing record requires explicit selection');
 await fill('Contact name','Reviewed person');await fill('Contact phone','7045550100');await fill('How were these details reviewed?','Direct call');button('Save reviewed links').click();button('Save reviewed links').click();await tick();check(calls.length===4,'Synchronous busy guard prevents duplicate saves');check('existingId'in calls[3].organization&&calls[3].organization.existingId==='company-b','Selected ID sent without automatic matching');check(calls[3].expectedVersion===2,'Reloaded CAS version used');saveRelease?.();await tick();check(versions.includes(3),'Parent receives updated lead version');check(document.body.textContent?.includes('Original immutable person'),'Original intake remains available read-only');await fill('Reviewed email','corrected@example.test');button('Save contact correction').click();await tick();check(versions.includes(4),'Correction advances shared lead version');check(state.intake?.raw_intake.name==='Original immutable person','Correction does not change original intake');
 // A previous lead read must never overwrite a subsequently selected inquiry.
 let releaseOld:((value:Context)=>void)|undefined;
 const raceApi:ContextTransport={...api,get:async id=>id==='old'?new Promise(r=>{releaseOld=r;}):{...state,lead:{...state.lead,id},organization:{id:'new',display_name:'Newest inquiry',version:1,archived:false}}};
 render('old',raceApi);await tick();render('new',raceApi);await tick();releaseOld?.({...state,organization:{id:'old',display_name:'Old inquiry result',version:1,archived:false}});await tick();check(document.body.textContent?.includes('Newest inquiry')&&!document.body.textContent?.includes('Old inquiry result'),'Stale detail result ignored after inquiry switch');
 let inquiry:any={id:'first',name:'Original immutable person',reported_company_name:'Integrated company',reported_property_name:null,location:'Region',description:'Original',status:'new',version:4,owner_id:null,next_action:'Original next action',next_action_due_at:null,services:[],email:null,phone:'7045550100'};
 let patchVersion=0,releaseCorrection:(()=>void)|undefined;
 const inboxApi:CommercialInboxApi={list:async()=>({items:[inquiry],nextCursor:null}),get:async()=>({...inquiry}),update:async(_id,body)=>{patchVersion=body.expectedVersion;inquiry={...inquiry,version:6,next_action:body.nextAction};return inquiry;}};
 const integratedApi:ContextTransport={...api,get:async()=>structuredClone(state),review:async(_id,body)=>{await new Promise<void>(resolve=>{releaseCorrection=resolve;});state={...state,lead:{...state.lead,version:5},contact:{...state.contact!,...body.contact,version:3}};inquiry={...inquiry,version:5};return{leadId:'first',version:5,contactId:'contact',contactVersion:3};}};
 root.render(<CommercialInbox staff={[]} api={inboxApi} contextApi={integratedApi}/>);await tick();(document.querySelector('.commercial-summary') as HTMLButtonElement).click();await tick();await fill('Next action','Unsaved follow-up must survive');await fill('Reviewed contact name','Correction while follow-up drafted');button('Save contact correction').click();await tick();check(button('Save follow-up').disabled&&(document.querySelector('.commercial-summary') as HTMLButtonElement).disabled,'Context mutation blocks queue selection and follow-up mutation');releaseCorrection?.();await tick();check(control('Next action').value==='Unsaved follow-up must survive','Context version update preserves unsaved follow-up form');button('Save follow-up').click();await tick();check(patchVersion===5,'Follow-up submits latest context version');
 // A newer context GET is not evidence that a drafted follow-up incorporated a colleague's edit.
 let detail={...inquiry,version:1,next_action:'Detail v1'},serverVersion=2,stalePatch=0,releaseInitial:((value:Context)=>void)|undefined;
 const staleInbox:CommercialInboxApi={list:async()=>({items:[detail],nextCursor:null}),get:async()=>({...detail}),update:async(_id,body)=>{stalePatch=body.expectedVersion;if(body.expectedVersion!==serverVersion)throw Error('Expected conflict');throw Error('Stale form was incorrectly blessed');}};
 const newerGet:ContextTransport={...api,get:async()=>new Promise(resolve=>{releaseInitial=resolve;})};
 root.render(<CommercialInbox key="initial-cas-race" staff={[]} api={staleInbox} contextApi={newerGet}/>);await tick();(document.querySelector('.commercial-summary') as HTMLButtonElement).click();await tick();releaseInitial?.({...state,lead:{...state.lead,version:2}});await tick();await fill('Next action','Old locally drafted follow-up');button('Save follow-up').click();await tick();check(stalePatch===1,'Delayed initial context GET cannot advance follow-up CAS');check(control('Next action').value==='Old locally drafted follow-up','Initial GET race leaves stale draft for explicit conflict recovery');
 // Own v1→v2 mutation may advance CAS, but the subsequent GET seeing colleague v3 must not.
 detail={...detail,version:1};serverVersion=3;let reads=0;
 const afterMutation:ContextTransport={...api,get:async()=>({...state,lead:{...state.lead,version:++reads===1?1:3}}),review:async()=>({leadId:'first',version:2,contactId:'contact',contactVersion:3})};
 root.render(<CommercialInbox key="post-ack-cas-race" staff={[]} api={staleInbox} contextApi={afterMutation}/>);await tick();(document.querySelector('.commercial-summary') as HTMLButtonElement).click();await tick();await fill('Next action','Follow-up draft before colleague edit');await fill('Reviewed contact name','Own contact edit');button('Save contact correction').click();await tick();button('Save follow-up').click();await tick();check(stalePatch===2,'Own mutation advances matching baseline only; subsequent newer GET cannot bless stale follow-up');check(control('Next action').value==='Follow-up draft before colleague edit','Post-ack read race preserves follow-up draft on conflict');
 let acceptedPosts=0;
 const readFailureApi:ContextTransport={...api,save:async()=>{acceptedPosts++;state={...state,lead:{...state.lead,version:state.lead.version+1}};getFailure=true;return{leadId:'first',version:state.lead.version,organizationId:'company-b',contactId:'contact',propertyId:null};}};
 root.render(<CommercialContextPanel key="accepted-read-failure" leadId="first" api={readFailureApi}/>);await tick();await fill('How were these details reviewed?','Confirmed by phone');button('Save reviewed links').click();await tick();check(acceptedPosts===1,'Accepted-save read failure makes one POST');check(button('Save reviewed links').disabled,'Known acceptance followed by read failure blocks duplicate save');check(document.body.textContent?.includes('Changes saved.'),'Known acceptance remains visible despite read failure');button('Reload saved context and discard edits').click();await tick();check(acceptedPosts===1&&!button('Save reviewed links').disabled,'Explicit reload recovers accepted state without reposting');check(!document.body.textContent?.includes('Changes saved. Loading the reviewed records'),'Successful explicit reload clears the stale loading status');
 document.getElementById('results')!.textContent=`PASS: ${assertions} synthetic browser assertions`;document.title='PASS prospect context';
}
run().catch(error=>{document.getElementById('results')!.textContent='FAIL: '+error.message;document.title='FAIL prospect context';console.error(error);});
