/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Initial shared field-client contract. Additional office routes are documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type {
  FieldSyncResponse,
  GetSetupStatus200,
  SyncFieldEventsBody,
  WorkOrder
} from './models';

import { customFetch } from '../custom-fetch';

export const getGetMyWorkOrdersUrl = () => {




  return `/api/v1/work-orders`
}

export const getMyWorkOrders = async ( options?: RequestInit): Promise<WorkOrder[]> => {

  return customFetch<WorkOrder[]>(getGetMyWorkOrdersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getSyncFieldEventsUrl = () => {




  return `/api/v1/field/sync`
}

export const syncFieldEvents = async (syncFieldEventsBody: SyncFieldEventsBody, options?: RequestInit): Promise<FieldSyncResponse> => {

  return customFetch<FieldSyncResponse>(getSyncFieldEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncFieldEventsBody,)
  }
);}



export const getGetSetupStatusUrl = () => {




  return `/api/v1/setup`
}

export const getSetupStatus = async ( options?: RequestInit): Promise<GetSetupStatus200> => {

  return customFetch<GetSetupStatus200>(getGetSetupStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}
