/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type {
  AccountMfaPolicy,
  AccountMfaPolicyUpdate,
  AgreementActivationPreview,
  AgreementChargeHistory,
  AgreementChargePreview,
  AgreementChargeQueue,
  AgreementChargeReceipt,
  AgreementChargeReview,
  AgreementChargeReviewHistory,
  AgreementChargeReviewInput,
  AgreementChargeReviewPreview,
  AgreementChargeReviewReceipt,
  AgreementChargeReviewRecordInput,
  AgreementChargeSource,
  AgreementEstimateOption,
  AgreementRecurrenceOption,
  AgreementVersion,
  CancelServiceAgreement,
  CommercialFollowUp,
  CommercialInquiry,
  CommercialInquiryDetail,
  CommercialInquiryPage,
  CreateServiceAgreement,
  DashboardMe,
  DashboardProperty,
  EditServiceAgreement,
  FieldSyncResponse,
  GetScheduleParams,
  GetSetupStatus200,
  ListAgreementChargeQueueParams,
  ListAgreementChargeReviewsParams,
  ListAgreementChargesParams,
  ListCommercialInquiriesParams,
  ListServiceAgreementsParams,
  PhotoUploadReceipt,
  PropertyFile,
  PropertyTimelineEvent,
  ReadinessResult,
  ReadinessUpdate,
  RescheduleWork,
  SchedulePage,
  ServiceAgreement,
  ServiceAgreementFinancial,
  ServiceAgreementPage,
  SyncFieldEventsBody,
  UpdateAccountMfaPolicy,
  UploadFieldPhotoHeaders,
  WorkOrder,
  WorkVersion
} from './models';

import { customFetch } from '../custom-fetch';

export const getGetMyWorkOrdersUrl = () => {




  return `/api/v1/work-orders`
}

export const getMyWorkOrders = async ( options?: RequestInit): Promise<WorkOrder[]> => {

  return customFetch<WorkOrder[]>(getGetMyWorkOrdersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getSyncFieldEventsUrl = () => {




  return `/api/v1/field/sync`
}

export const syncFieldEvents = async (syncFieldEventsBody: SyncFieldEventsBody, options?: RequestInit): Promise<FieldSyncResponse> => {

  return customFetch<FieldSyncResponse>(getSyncFieldEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncFieldEventsBody,)
  }
);}



export const getGetSetupStatusUrl = () => {




  return `/api/v1/setup`
}

export const getSetupStatus = async ( options?: RequestInit): Promise<GetSetupStatus200> => {

  return customFetch<GetSetupStatus200>(getGetSetupStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListCommercialInquiriesUrl = (params?: ListCommercialInquiriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/commercial-inquiries?${stringifiedParams}` : `/api/v1/commercial-inquiries`
}

/**
 * Owner/manager/sales only. Cursor is bound to filters; discard it when filters change. Recent-first created_at/id ordering preserves microseconds.
 */
export const listCommercialInquiries = async (params?: ListCommercialInquiriesParams, options?: RequestInit): Promise<CommercialInquiryPage> => {

  return customFetch<CommercialInquiryPage>(getListCommercialInquiriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetCommercialInquiryUrl = (id: string,) => {




  return `/api/v1/commercial-inquiries/${id}`
}

/**
 * Owner/manager/sales only. No operational identity or access is provisioned.
 */
export const getCommercialInquiry = async (id: string, options?: RequestInit): Promise<CommercialInquiryDetail> => {

  return customFetch<CommercialInquiryDetail>(getGetCommercialInquiryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateCommercialFollowUpUrl = (id: string,) => {




  return `/api/v1/commercial-inquiries/${id}/follow-up`
}

/**
 * Owner/manager/sales only. Optimistic version required; reload detail/list after success.
 */
export const updateCommercialFollowUp = async (id: string,
    commercialFollowUp: CommercialFollowUp, options?: RequestInit): Promise<CommercialInquiry> => {

  return customFetch<CommercialInquiry>(getUpdateCommercialFollowUpUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      commercialFollowUp,)
  }
);}



export const getGetScheduleUrl = (params: GetScheduleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/schedule?${stringifiedParams}` : `/api/v1/schedule`
}

/**
 * Up to32 inclusive New York dates. Pages contain100 items. Crew assigned work only; clients granted accounts only. Unscheduled mode is forbidden to clients.
 */
export const getSchedule = async (params: GetScheduleParams, options?: RequestInit): Promise<SchedulePage> => {

  return customFetch<SchedulePage>(getGetScheduleUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetScheduledWorkUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}`
}

/**
 * Direct role-filtered detail. Private or missing records return404.
 */
export const getScheduledWork = async (id: string, options?: RequestInit): Promise<WorkOrder> => {

  return customFetch<WorkOrder>(getGetScheduledWorkUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getRescheduleWorkUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/reschedule`
}

/**
 * Owner/manager/dispatch only. Draft/scheduled/delayed state and current version required. Recurrence identity stays unchanged.
 */
export const rescheduleWork = async (id: string,
    rescheduleWork: RescheduleWork, options?: RequestInit): Promise<WorkVersion> => {

  return customFetch<WorkVersion>(getRescheduleWorkUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rescheduleWork,)
  }
);}



export const getUpdateWorkReadinessUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/readiness`
}

/**
 * Owner/manager/dispatch only. Operational property required. Version-locked draft/scheduled/delayed edits; accepted changes clear prior overrides and audit before/after. Unchanged requirements return400. Started/stale work returns409.
 */
export const updateWorkReadiness = async (id: string,
    readinessUpdate: ReadinessUpdate, options?: RequestInit): Promise<ReadinessResult> => {

  return customFetch<ReadinessResult>(getUpdateWorkReadinessUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      readinessUpdate,)
  }
);}



export const getListAccountMfaPoliciesUrl = () => {




  return `/api/v1/account-mfa-policies`
}

/**
 * Owner-only list of every active dashboard account, including client accounts, and its configured MFA requirement.
 */
export const listAccountMfaPolicies = async ( options?: RequestInit): Promise<AccountMfaPolicy[]> => {

  return customFetch<AccountMfaPolicy[]>(getListAccountMfaPoliciesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateAccountMfaPolicyUrl = (id: string,) => {




  return `/api/v1/account-mfa-policies/${id}`
}

/**
 * Owner-only update of an active account's configured MFA requirement. The update and audit record are atomic.
 */
export const updateAccountMfaPolicy = async (id: string,
    updateAccountMfaPolicy: UpdateAccountMfaPolicy, options?: RequestInit): Promise<AccountMfaPolicyUpdate> => {

  return customFetch<AccountMfaPolicyUpdate>(getUpdateAccountMfaPolicyUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAccountMfaPolicy,)
  }
);}



export const getGetDashboardMeUrl = () => {




  return `/api/v1/me`
}

/**
 * Verified identity and active business role. Does not grant session assurance or bypass owner MFA. Inactive or missing business profiles return role null.
 */
export const getDashboardMe = async ( options?: RequestInit): Promise<DashboardMe> => {

  return customFetch<DashboardMe>(getGetDashboardMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListDashboardPropertiesUrl = () => {




  return `/api/v1/properties`
}

/**
 * Operational unarchived properties. Client responses omit internal fields; crew only sees properties with active assigned work.
 */
export const listDashboardProperties = async ( options?: RequestInit): Promise<DashboardProperty[]> => {

  return customFetch<DashboardProperty[]>(getListDashboardPropertiesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetPropertyTimelineUrl = (id: string,) => {




  return `/api/v1/properties/${id}/timeline`
}

/**
 * Latest 200 captured field events; clients require both event and work publication. Crew sees assigned work only.
 */
export const getPropertyTimeline = async (id: string, options?: RequestInit): Promise<PropertyTimelineEvent[]> => {

  return customFetch<PropertyTimelineEvent[]>(getGetPropertyTimelineUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListPropertyFilesUrl = (id: string,) => {




  return `/api/v1/properties/${id}/files`
}

/**
 * Ready file metadata only; clients see published files and crew sees files for assigned work. Object keys and storage URLs are never included.
 */
export const listPropertyFiles = async (id: string, options?: RequestInit): Promise<PropertyFile[]> => {

  return customFetch<PropertyFile[]>(getListPropertyFilesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetPrivateFileContentUrl = (id: string,) => {




  return `/api/v1/files/${id}/content`
}

/**
 * Authorized private image bytes; never a storage URL. Requires property grants and publication or crew assignment. Response is uncached.
 */
export const getPrivateFileContent = async (id: string, options?: RequestInit): Promise<Blob> => {

  return customFetch<Blob>(getGetPrivateFileContentUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUploadFieldPhotoUrl = (id: string,) => {




  return `/api/v1/files/${id}`
}

/**
 * Raw image bytes (not multipart or JSON). Keep operation ID, original bytes, property, work and classification unchanged on retry. Never publishes content. Supports exact image/jpeg, image/png or image/webp Content-Type.
 */
export const uploadFieldPhoto = async (id: string,
    uploadFieldPhotoBody: Blob,
    headers: UploadFieldPhotoHeaders, options?: RequestInit): Promise<PhotoUploadReceipt> => {


  const uploadHeaders = new Headers(options?.headers);
  const mime = uploadHeaders.get('Content-Type') || uploadFieldPhotoBody.type;
  if (!['image/jpeg', 'image/png', 'image/webp'].includes(mime))
    throw new TypeError('Photo Blob or Content-Type must declare JPEG, PNG, or WebP');
  uploadHeaders.set('Content-Type', mime);
  for (const [key, value] of Object.entries(headers))
    if (value !== undefined) uploadHeaders.set(key, value);

  return customFetch<PhotoUploadReceipt>(getUploadFieldPhotoUrl(id),
  {
    ...options,
    method: 'POST',
    headers: uploadHeaders,
    body: uploadFieldPhotoBody
  }
);}



export const getListServiceAgreementsUrl = (params?: ListServiceAgreementsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/service-agreements?${stringifiedParams}` : `/api/v1/service-agreements`
}

/**
 * Management/finance financial projection; dispatch scope/dates only. No client, crew or sales access.
 */
export const listServiceAgreements = async (params?: ListServiceAgreementsParams, options?: RequestInit): Promise<ServiceAgreementPage> => {

  return customFetch<ServiceAgreementPage>(getListServiceAgreementsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateServiceAgreementUrl = () => {




  return `/api/v1/service-agreements`
}

export const createServiceAgreement = async (createServiceAgreement: CreateServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getCreateServiceAgreementUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createServiceAgreement,)
  }
);}



export const getGetServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}`
}

export const getServiceAgreement = async (id: string, options?: RequestInit): Promise<ServiceAgreement> => {

  return customFetch<ServiceAgreement>(getGetServiceAgreementUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}`
}

export const updateServiceAgreement = async (id: string,
    editServiceAgreement: EditServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getUpdateServiceAgreementUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editServiceAgreement,)
  }
);}



export const getPreviewServiceAgreementActivationUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/activation-preview`
}

export const previewServiceAgreementActivation = async (id: string,
    agreementVersion: AgreementVersion, options?: RequestInit): Promise<AgreementActivationPreview> => {

  return customFetch<AgreementActivationPreview>(getPreviewServiceAgreementActivationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementVersion,)
  }
);}



export const getActivateServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/activate`
}

export const activateServiceAgreement = async (id: string,
    agreementVersion: AgreementVersion, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getActivateServiceAgreementUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementVersion,)
  }
);}



export const getCancelServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/cancel`
}

export const cancelServiceAgreement = async (id: string,
    cancelServiceAgreement: CancelServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getCancelServiceAgreementUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cancelServiceAgreement,)
  }
);}



export const getPreviewAgreementChargeUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/charge-preview`
}

export const previewAgreementCharge = async (id: string,
    agreementChargeSource: AgreementChargeSource, options?: RequestInit): Promise<AgreementChargePreview> => {

  return customFetch<AgreementChargePreview>(getPreviewAgreementChargeUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeSource,)
  }
);}



export const getListAgreementChargesUrl = (id: string,
    params?: ListAgreementChargesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/service-agreements/${id}/charges?${stringifiedParams}` : `/api/v1/service-agreements/${id}/charges`
}

export const listAgreementCharges = async (id: string,
    params?: ListAgreementChargesParams, options?: RequestInit): Promise<AgreementChargeHistory> => {

  return customFetch<AgreementChargeHistory>(getListAgreementChargesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPrepareAgreementChargeUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/charges`
}

export const prepareAgreementCharge = async (id: string,
    agreementChargeSource: AgreementChargeSource, options?: RequestInit): Promise<AgreementChargeReceipt> => {

  return customFetch<AgreementChargeReceipt>(getPrepareAgreementChargeUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeSource,)
  }
);}



export const getGetAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/review`
}

export const getAgreementChargeReview = async (id: string, options?: RequestInit): Promise<AgreementChargeReview> => {

  return customFetch<AgreementChargeReview>(getGetAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPreviewAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/review-preview`
}

export const previewAgreementChargeReview = async (id: string,
    agreementChargeReviewInput: AgreementChargeReviewInput, options?: RequestInit): Promise<AgreementChargeReviewPreview> => {

  return customFetch<AgreementChargeReviewPreview>(getPreviewAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeReviewInput,)
  }
);}



export const getListAgreementChargeReviewsUrl = (id: string,
    params?: ListAgreementChargeReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/agreement-charges/${id}/reviews?${stringifiedParams}` : `/api/v1/agreement-charges/${id}/reviews`
}

export const listAgreementChargeReviews = async (id: string,
    params?: ListAgreementChargeReviewsParams, options?: RequestInit): Promise<AgreementChargeReviewHistory> => {

  return customFetch<AgreementChargeReviewHistory>(getListAgreementChargeReviewsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getRecordAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/reviews`
}

export const recordAgreementChargeReview = async (id: string,
    agreementChargeReviewRecordInput: AgreementChargeReviewRecordInput, options?: RequestInit): Promise<AgreementChargeReviewReceipt> => {

  return customFetch<AgreementChargeReviewReceipt>(getRecordAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeReviewRecordInput,)
  }
);}



export const getListAgreementChargeQueueUrl = (params?: ListAgreementChargeQueueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/agreement-charge-queue?${stringifiedParams}` : `/api/v1/agreement-charge-queue`
}

/**
 * Management/finance current action queue. Capped, unmatched and prepared cancellation issues remain visible. Recheck eligibility before preparing.
 */
export const listAgreementChargeQueue = async (params?: ListAgreementChargeQueueParams, options?: RequestInit): Promise<AgreementChargeQueue> => {

  return customFetch<AgreementChargeQueue>(getListAgreementChargeQueueUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListAgreementRecurrencesUrl = () => {




  return `/api/v1/recurring-services`
}

export const listAgreementRecurrences = async ( options?: RequestInit): Promise<AgreementRecurrenceOption[]> => {

  return customFetch<AgreementRecurrenceOption[]>(getListAgreementRecurrencesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListAgreementEstimatesUrl = () => {




  return `/api/v1/estimates`
}

export const listAgreementEstimates = async ( options?: RequestInit): Promise<AgreementEstimateOption[]> => {

  return customFetch<AgreementEstimateOption[]>(getListAgreementEstimatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



