/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * P1Dashboard
 * Shared field, scheduling and commercial inbox contract. Other office routes remain documented in docs/dashboard/API.md.
 * OpenAPI spec version: 0.1.0
 */
import type {
  AccountMfaPolicy,
  AccountMfaPolicyUpdate,
  AgreementActivationPreview,
  AgreementChargeHistory,
  AgreementChargePreview,
  AgreementChargeQueue,
  AgreementChargeReceipt,
  AgreementChargeReview,
  AgreementChargeReviewHistory,
  AgreementChargeReviewInput,
  AgreementChargeReviewPreview,
  AgreementChargeReviewReceipt,
  AgreementChargeReviewRecordInput,
  AgreementChargeSource,
  AgreementEstimateOption,
  AgreementPreparationJob,
  AgreementPreparationJobPage,
  AgreementPreparationRetryInput,
  AgreementPreparationRetryPreview,
  AgreementPreparationRetryPreviewInput,
  AgreementPreparationRetryReceipt,
  AgreementRecurrenceOption,
  AgreementVersion,
  AssessmentAvailability,
  AssessmentAvailabilityConfiguration,
  AssessmentAvailabilityUpdate,
  AssessmentSlot,
  BillingDraft,
  BookAssessmentSlot,
  CancelServiceAgreement,
  ClientContact,
  ClientOnboardingReceipt,
  ClientWorkspace,
  CommercialFollowUp,
  CommercialInquiry,
  CommercialInquiryDetail,
  CommercialInquiryPage,
  CreateAssessmentBlackout,
  CreateBillingDraft,
  CreateClientContact,
  CreateClientNote,
  CreateDashboardClient,
  CreateDashboardProperty,
  CreateInspectionReport,
  CreateManualAssessmentSlot,
  CreateProjectPhase,
  CreateRecurringService,
  CreateSalesEstimate,
  CreateSalesLead,
  CreateServiceAgreement,
  CreateServiceRequest,
  CreateWorkOrder,
  CreatedResource,
  DashboardClient,
  DashboardMe,
  DashboardProperty,
  EditServiceAgreement,
  EstimateChangeOrder,
  EstimateDecision,
  EstimateDecisionReceipt,
  EstimateRevision,
  FieldSyncResponse,
  GenerateAssessmentAvailability,
  GeneratedAssessmentAvailability,
  GetScheduleParams,
  GetSetupStatus200,
  InspectionReport,
  IntegrationHealth,
  ListAgreementChargeQueueParams,
  ListAgreementChargeReviewsParams,
  ListAgreementChargesParams,
  ListAgreementPreparationJobsParams,
  ListCommercialInquiriesParams,
  ListServiceAgreementsParams,
  OperationReceipt,
  PhotoUploadReceipt,
  ProjectPhase,
  ProjectPhaseBillingIntent,
  ProjectPhaseBillingIntentInput,
  ProjectPhaseBillingIntentReceipt,
  ProjectPhaseCreateReceipt,
  ProjectPhaseEvent,
  ProjectPhasePublication,
  ProjectPhaseReceipt,
  ProjectPhaseTransition,
  ProjectPhaseTransitionReceipt,
  PropertyFile,
  PropertyTimelineEvent,
  PropertyWorkspace,
  PublicationReceipt,
  ReadinessResult,
  ReadinessUpdate,
  RecurringServicePause,
  RescheduleWork,
  SalesLead,
  SalesLeadConversion,
  SalesLeadConversionReceipt,
  SchedulePage,
  ServiceAgreement,
  ServiceAgreementFinancial,
  ServiceAgreementPage,
  ServiceRequest,
  ServiceRequestConversion,
  ServiceRequestConversionPreview,
  ServiceRequestConversionPreviewInput,
  ServiceRequestConversionReceipt,
  ServiceRequestEvent,
  ServiceRequestLifecycle,
  ServiceRequestTransition,
  ServiceRequestTransitionReceipt,
  SyncFieldEventsBody,
  UpdateAccountMfaPolicy,
  UpdateClientContact,
  UpdateDashboardClient,
  UpdateProjectPhase,
  UploadFieldPhotoHeaders,
  WorkOrder,
  WorkOrderStatusUpdate,
  WorkVersion
} from './models';

import { customFetch } from '../custom-fetch';

export const getGetMyWorkOrdersUrl = () => {




  return `/api/v1/work-orders`
}

export const getMyWorkOrders = async ( options?: RequestInit): Promise<WorkOrder[]> => {

  return customFetch<WorkOrder[]>(getGetMyWorkOrdersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkOrderUrl = () => {




  return `/api/v1/work-orders`
}

/**
 * Owner, manager, or dispatch only. Creates an operational work order. It does not publish client material, post billing, charge payment, or call providers.
 */
export const createWorkOrder = async (createWorkOrder: CreateWorkOrder, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateWorkOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkOrder,)
  }
);}



export const getUpdateWorkOrderStatusUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/status`
}

/**
 * Owner, manager, or dispatch only. Applies a server-validated status transition using the current version. Manager-only overrides are recorded when prerequisites would otherwise block progress.
 */
export const updateWorkOrderStatus = async (id: string,
    workOrderStatusUpdate: WorkOrderStatusUpdate, options?: RequestInit): Promise<PublicationReceipt> => {

  return customFetch<PublicationReceipt>(getUpdateWorkOrderStatusUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workOrderStatusUpdate,)
  }
);}



export const getPublishWorkOrderUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/publish`
}

/**
 * Owner or manager only. Publishes a reviewed work order and eligible non-conflicting field notes, checklists, and completion events. It does not publish issues, alter billing, or record payment.
 */
export const publishWorkOrder = async (id: string, options?: RequestInit): Promise<PublicationReceipt> => {

  return customFetch<PublicationReceipt>(getPublishWorkOrderUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getSyncFieldEventsUrl = () => {




  return `/api/v1/field/sync`
}

export const syncFieldEvents = async (syncFieldEventsBody: SyncFieldEventsBody, options?: RequestInit): Promise<FieldSyncResponse> => {

  return customFetch<FieldSyncResponse>(getSyncFieldEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncFieldEventsBody,)
  }
);}



export const getGetSetupStatusUrl = () => {




  return `/api/v1/setup`
}

export const getSetupStatus = async ( options?: RequestInit): Promise<GetSetupStatus200> => {

  return customFetch<GetSetupStatus200>(getGetSetupStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListCommercialInquiriesUrl = (params?: ListCommercialInquiriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/commercial-inquiries?${stringifiedParams}` : `/api/v1/commercial-inquiries`
}

/**
 * Owner/manager/sales only. Cursor is bound to filters; discard it when filters change. Recent-first created_at/id ordering preserves microseconds.
 */
export const listCommercialInquiries = async (params?: ListCommercialInquiriesParams, options?: RequestInit): Promise<CommercialInquiryPage> => {

  return customFetch<CommercialInquiryPage>(getListCommercialInquiriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetCommercialInquiryUrl = (id: string,) => {




  return `/api/v1/commercial-inquiries/${id}`
}

/**
 * Owner/manager/sales only. No operational identity or access is provisioned.
 */
export const getCommercialInquiry = async (id: string, options?: RequestInit): Promise<CommercialInquiryDetail> => {

  return customFetch<CommercialInquiryDetail>(getGetCommercialInquiryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateCommercialFollowUpUrl = (id: string,) => {




  return `/api/v1/commercial-inquiries/${id}/follow-up`
}

/**
 * Owner/manager/sales only. Optimistic version required; reload detail/list after success.
 */
export const updateCommercialFollowUp = async (id: string,
    commercialFollowUp: CommercialFollowUp, options?: RequestInit): Promise<CommercialInquiry> => {

  return customFetch<CommercialInquiry>(getUpdateCommercialFollowUpUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      commercialFollowUp,)
  }
);}



export const getGetScheduleUrl = (params: GetScheduleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/schedule?${stringifiedParams}` : `/api/v1/schedule`
}

/**
 * Up to32 inclusive New York dates. Pages contain100 items. Crew assigned work only; clients granted accounts only. Unscheduled mode is forbidden to clients.
 */
export const getSchedule = async (params: GetScheduleParams, options?: RequestInit): Promise<SchedulePage> => {

  return customFetch<SchedulePage>(getGetScheduleUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetScheduledWorkUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}`
}

/**
 * Direct role-filtered detail. Private or missing records return404.
 */
export const getScheduledWork = async (id: string, options?: RequestInit): Promise<WorkOrder> => {

  return customFetch<WorkOrder>(getGetScheduledWorkUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getRescheduleWorkUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/reschedule`
}

/**
 * Owner/manager/dispatch only. Draft/scheduled/delayed state and current version required. Recurrence identity stays unchanged.
 */
export const rescheduleWork = async (id: string,
    rescheduleWork: RescheduleWork, options?: RequestInit): Promise<WorkVersion> => {

  return customFetch<WorkVersion>(getRescheduleWorkUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rescheduleWork,)
  }
);}



export const getUpdateWorkReadinessUrl = (id: string,) => {




  return `/api/v1/work-orders/${id}/readiness`
}

/**
 * Owner/manager/dispatch only. Operational property required. Version-locked draft/scheduled/delayed edits; accepted changes clear prior overrides and audit before/after. Unchanged requirements return400. Started/stale work returns409.
 */
export const updateWorkReadiness = async (id: string,
    readinessUpdate: ReadinessUpdate, options?: RequestInit): Promise<ReadinessResult> => {

  return customFetch<ReadinessResult>(getUpdateWorkReadinessUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      readinessUpdate,)
  }
);}



export const getListAccountMfaPoliciesUrl = () => {




  return `/api/v1/account-mfa-policies`
}

/**
 * Owner-only list of every active dashboard account, including client accounts, and its configured MFA requirement.
 */
export const listAccountMfaPolicies = async ( options?: RequestInit): Promise<AccountMfaPolicy[]> => {

  return customFetch<AccountMfaPolicy[]>(getListAccountMfaPoliciesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateAccountMfaPolicyUrl = (id: string,) => {




  return `/api/v1/account-mfa-policies/${id}`
}

/**
 * Owner-only update of an active account's configured MFA requirement. The update and audit record are atomic.
 */
export const updateAccountMfaPolicy = async (id: string,
    updateAccountMfaPolicy: UpdateAccountMfaPolicy, options?: RequestInit): Promise<AccountMfaPolicyUpdate> => {

  return customFetch<AccountMfaPolicyUpdate>(getUpdateAccountMfaPolicyUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAccountMfaPolicy,)
  }
);}



export const getGetDashboardMeUrl = () => {




  return `/api/v1/me`
}

/**
 * Verified identity and active business role. Does not grant session assurance or bypass an account MFA requirement. Inactive or missing business profiles return role null.
 */
export const getDashboardMe = async ( options?: RequestInit): Promise<DashboardMe> => {

  return customFetch<DashboardMe>(getGetDashboardMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetAssessmentAvailabilityUrl = () => {




  return `/api/v1/assessment-availability`
}

/**
 * Returns the office-managed assessment configuration, active blackout dates, and the America/New_York operating timezone. Owner, manager, and dispatch roles only.
 */
export const getAssessmentAvailability = async ( options?: RequestInit): Promise<AssessmentAvailability> => {

  return customFetch<AssessmentAvailability>(getGetAssessmentAvailabilityUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getSaveAssessmentAvailabilityUrl = () => {




  return `/api/v1/assessment-availability`
}

/**
 * Updates the configured weekly assessment windows using an optimistic version. Saving cancels unbooked future generated slots; booked appointments are retained.
 */
export const saveAssessmentAvailability = async (assessmentAvailabilityUpdate: AssessmentAvailabilityUpdate, options?: RequestInit): Promise<AssessmentAvailabilityConfiguration> => {

  return customFetch<AssessmentAvailabilityConfiguration>(getSaveAssessmentAvailabilityUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assessmentAvailabilityUpdate,)
  }
);}



export const getGenerateAssessmentAvailabilityUrl = () => {




  return `/api/v1/assessment-availability/generate`
}

/**
 * Generates slots from configured weekly availability for one through 90 calendar days. Existing bookings, blackouts, daylight-saving transitions, and travel buffers are preserved.
 */
export const generateAssessmentAvailability = async (generateAssessmentAvailability: GenerateAssessmentAvailability, options?: RequestInit): Promise<GeneratedAssessmentAvailability> => {

  return customFetch<GeneratedAssessmentAvailability>(getGenerateAssessmentAvailabilityUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateAssessmentAvailability,)
  }
);}



export const getCreateAssessmentBlackoutUrl = () => {




  return `/api/v1/assessment-availability/blackouts`
}

/**
 * Adds an office blackout. It cannot overlap a booked assessment, including configured travel buffers.
 */
export const createAssessmentBlackout = async (createAssessmentBlackout: CreateAssessmentBlackout, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateAssessmentBlackoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAssessmentBlackout,)
  }
);}



export const getArchiveAssessmentBlackoutUrl = (id: string,) => {




  return `/api/v1/assessment-availability/blackouts/${id}/archive`
}

/**
 * Archives an active assessment blackout. It does not restore cancelled slots automatically.
 */
export const archiveAssessmentBlackout = async (id: string, options?: RequestInit): Promise<OperationReceipt> => {

  return customFetch<OperationReceipt>(getArchiveAssessmentBlackoutUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getListAvailableAssessmentSlotsUrl = () => {




  return `/api/v1/assessment-slots`
}

/**
 * Returns up to 100 future, unbooked slots outside active blackouts. Office roles and invited clients may read availability; clients still need office confirmation for non-assessment services.
 */
export const listAvailableAssessmentSlots = async ( options?: RequestInit): Promise<AssessmentSlot[]> => {

  return customFetch<AssessmentSlot[]>(getListAvailableAssessmentSlotsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateManualAssessmentSlotUrl = () => {




  return `/api/v1/assessment-slots`
}

/**
 * Creates a future manual assessment appointment, subject to blackout and buffered-slot collision checks. Owner, manager, and dispatch roles only.
 */
export const createManualAssessmentSlot = async (createManualAssessmentSlot: CreateManualAssessmentSlot, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateManualAssessmentSlotUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createManualAssessmentSlot,)
  }
);}



export const getBookAssessmentSlotUrl = (id: string,) => {




  return `/api/v1/assessment-slots/${id}/book`
}

/**
 * Atomically reserves an available assessment slot for an accessible operational property. Repeated racing attempts result in one success and a conflict response; the booking does not create a work order or invoice.
 */
export const bookAssessmentSlot = async (id: string,
    bookAssessmentSlot: BookAssessmentSlot, options?: RequestInit): Promise<OperationReceipt> => {

  return customFetch<OperationReceipt>(getBookAssessmentSlotUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookAssessmentSlot,)
  }
);}



export const getListDashboardClientsUrl = () => {




  return `/api/v1/clients`
}

/**
 * Office roles receive active client records and primary-contact summary fields. Client accounts receive only their own IDs and names; crew cannot access this route.
 */
export const listDashboardClients = async ( options?: RequestInit): Promise<DashboardClient[]> => {

  return customFetch<DashboardClient[]>(getListDashboardClientsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateDashboardClientUrl = () => {




  return `/api/v1/clients`
}

/**
 * Office-only client creation. Supplying primaryContact uses atomic onboarding and requires the business address and phone. Without it, the endpoint creates a minimal client record. Neither mode sends invitations, creates a property, schedules work, or posts billing.
 */
export const createDashboardClient = async (createDashboardClient: CreateDashboardClient, options?: RequestInit): Promise<CreatedResource | ClientOnboardingReceipt> => {

  return customFetch<CreatedResource | ClientOnboardingReceipt>(getCreateDashboardClientUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDashboardClient,)
  }
);}



export const getUpdateDashboardClientUrl = (id: string,) => {




  return `/api/v1/clients/${id}`
}

/**
 * Office-only optimistic client update. The supplied version must be current; the primary contact is updated or created in the same transaction. A stale version fails without overwriting either record.
 */
export const updateDashboardClient = async (id: string,
    updateDashboardClient: UpdateDashboardClient, options?: RequestInit): Promise<DashboardClient> => {

  return customFetch<DashboardClient>(getUpdateDashboardClientUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDashboardClient,)
  }
);}



export const getListClientContactsUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}/contacts`
}

/**
 * Lists active and archived contacts for a client. Owner, manager, dispatch, sales, and finance roles only; client and crew accounts cannot read another client's contacts.
 */
export const listClientContacts = async (clientId: string, options?: RequestInit): Promise<ClientContact[]> => {

  return customFetch<ClientContact[]>(getListClientContactsUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateClientContactUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}/contacts`
}

/**
 * Creates an additional primary, billing, site, or other client contact and writes an audit record. Contact identity is kept distinct from dashboard login identities.
 */
export const createClientContact = async (clientId: string,
    createClientContact: CreateClientContact, options?: RequestInit): Promise<ClientContact> => {

  return customFetch<ClientContact>(getCreateClientContactUrl(clientId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClientContact,)
  }
);}



export const getUpdateClientContactUrl = (clientId: string,
    id: string,) => {




  return `/api/v1/clients/${clientId}/contacts/${id}`
}

/**
 * Updates or archives a contact using its current version. A stale or cross-client update fails and does not overwrite contact history.
 */
export const updateClientContact = async (clientId: string,
    id: string,
    updateClientContact: UpdateClientContact, options?: RequestInit): Promise<ClientContact> => {

  return customFetch<ClientContact>(getUpdateClientContactUrl(clientId,id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateClientContact,)
  }
);}



export const getGetClientWorkspaceUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}/workspace`
}

/**
 * Office-only client command-center projection. Aggregates only records already linked to the requested client and includes internal notes for office roles.
 */
export const getClientWorkspace = async (clientId: string, options?: RequestInit): Promise<ClientWorkspace> => {

  return customFetch<ClientWorkspace>(getGetClientWorkspaceUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateClientNoteUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}/notes`
}

/**
 * Office-only append-only internal note. Optional property scope must belong to the requested client; clients and crew cannot read or create notes.
 */
export const createClientNote = async (clientId: string,
    createClientNote: CreateClientNote, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateClientNoteUrl(clientId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClientNote,)
  }
);}



export const getGetIntegrationHealthUrl = () => {




  return `/api/v1/integrations`
}

/**
 * Returns manager-only configuration indicators and the current office action queue. It does not expose provider credentials, trigger provider calls, post invoices, or change delivery state.
 */
export const getIntegrationHealth = async ( options?: RequestInit): Promise<IntegrationHealth> => {

  return customFetch<IntegrationHealth>(getGetIntegrationHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListServiceRequestsUrl = () => {




  return `/api/v1/requests`
}

/**
 * Office roles receive operational service requests with submitting identity. Clients receive requests for accessible properties, but never the internal submitting user ID. This endpoint does not change request status or dispatch work.
 */
export const listServiceRequests = async ( options?: RequestInit): Promise<ServiceRequest[]> => {

  return customFetch<ServiceRequest[]>(getListServiceRequestsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateServiceRequestUrl = () => {




  return `/api/v1/requests`
}

/**
 * Creates a new request for an operational property the actor may access. It does not automatically dispatch work or change a billing record.
 */
export const createServiceRequest = async (createServiceRequest: CreateServiceRequest, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateServiceRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createServiceRequest,)
  }
);}



export const getListServiceRequestLifecycleUrl = () => {




  return `/api/v1/service-requests`
}

/**
 * Lists service requests. Office roles receive operational fields; clients receive only requests for accessible properties with client-safe status labels. Crew members cannot access this route.
 */
export const listServiceRequestLifecycle = async ( options?: RequestInit): Promise<ServiceRequestLifecycle[]> => {

  return customFetch<ServiceRequestLifecycle[]>(getListServiceRequestLifecycleUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetServiceRequestLifecycleUrl = (id: string,) => {




  return `/api/v1/service-requests/${id}`
}

/**
 * Returns one service request. Office roles receive operational fields. Clients require property access and receive a client-safe projection. Crew members cannot access this route.
 */
export const getServiceRequestLifecycle = async (id: string, options?: RequestInit): Promise<ServiceRequestLifecycle> => {

  return customFetch<ServiceRequestLifecycle>(getGetServiceRequestLifecycleUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getTransitionServiceRequestUrl = (id: string,) => {




  return `/api/v1/service-requests/${id}/transitions`
}

/**
 * Owner, manager, or dispatch only. Changes status with optimistic versioning and an explicit reason. It does not assign crews, schedule work, publish client material, post billing, or call providers.
 */
export const transitionServiceRequest = async (id: string,
    serviceRequestTransition: ServiceRequestTransition, options?: RequestInit): Promise<ServiceRequestTransitionReceipt> => {

  return customFetch<ServiceRequestTransitionReceipt>(getTransitionServiceRequestUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serviceRequestTransition,)
  }
);}



export const getGetServiceRequestHistoryUrl = (id: string,) => {




  return `/api/v1/service-requests/${id}/history`
}

/**
 * Office-only append-only service-request lifecycle history. Clients and crew cannot access this route.
 */
export const getServiceRequestHistory = async (id: string, options?: RequestInit): Promise<ServiceRequestEvent[]> => {

  return customFetch<ServiceRequestEvent[]>(getGetServiceRequestHistoryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPreviewServiceRequestConversionUrl = (id: string,) => {




  return `/api/v1/service-requests/${id}/conversion-preview`
}

/**
 * Owner, manager, or dispatch only. Previews an unscheduled, unassigned, unpublished draft work order from a triaged or scheduled request. It never writes, dispatches, bills, publishes, or calls a provider.
 */
export const previewServiceRequestConversion = async (id: string,
    serviceRequestConversionPreviewInput: ServiceRequestConversionPreviewInput, options?: RequestInit): Promise<ServiceRequestConversionPreview> => {

  return customFetch<ServiceRequestConversionPreview>(getPreviewServiceRequestConversionUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serviceRequestConversionPreviewInput,)
  }
);}



export const getConvertServiceRequestUrl = (id: string,) => {




  return `/api/v1/service-requests/${id}/conversions`
}

/**
 * Owner, manager, or dispatch only. Creates exactly one retry-safe planning draft from a triaged or scheduled request. The operation ID is idempotent for the same actor and payload. The resulting draft is unassigned, unscheduled, unpublished, and has no billing or provider side effects.
 */
export const convertServiceRequest = async (id: string,
    serviceRequestConversion: ServiceRequestConversion, options?: RequestInit): Promise<ServiceRequestConversionReceipt> => {

  return customFetch<ServiceRequestConversionReceipt>(getConvertServiceRequestUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serviceRequestConversion,)
  }
);}



export const getListProjectPhasesUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/phases`
}

/**
 * Lists normalized phases for an operational project. Office roles receive the operational model. Clients receive explicitly published summaries only; crew receive phases tied to active assigned work only.
 */
export const listProjectPhases = async (projectId: string, options?: RequestInit): Promise<ProjectPhase[]> => {

  return customFetch<ProjectPhase[]>(getListProjectPhasesUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateProjectPhaseUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/phases`
}

/**
 * Owner or manager only. Creates an additive normalized project phase without replacing legacy project history. It does not dispatch work, publish client material, post billing, or call providers.
 */
export const createProjectPhase = async (projectId: string,
    createProjectPhase: CreateProjectPhase, options?: RequestInit): Promise<ProjectPhaseCreateReceipt> => {

  return customFetch<ProjectPhaseCreateReceipt>(getCreateProjectPhaseUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectPhase,)
  }
);}



export const getGetProjectPhaseUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}`
}

/**
 * Returns one phase with the same office, client-publication, and crew-assignment boundaries as the phase list.
 */
export const getProjectPhase = async (id: string, options?: RequestInit): Promise<ProjectPhase> => {

  return customFetch<ProjectPhase>(getGetProjectPhaseUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateProjectPhaseUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}`
}

/**
 * Owner or manager only. Replaces editable phase details with optimistic versioning and a required reason. Accepted, cancelled, and archived phases cannot be edited.
 */
export const updateProjectPhase = async (id: string,
    updateProjectPhase: UpdateProjectPhase, options?: RequestInit): Promise<ProjectPhaseReceipt> => {

  return customFetch<ProjectPhaseReceipt>(getUpdateProjectPhaseUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectPhase,)
  }
);}



export const getTransitionProjectPhaseUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}/transitions`
}

/**
 * Owner or manager only. Applies a validated phase lifecycle transition with an explicit reason. Unmet prerequisites require a recorded override for ready/in-progress states; acceptance requires linked work to be reviewed, cancelled, or skipped.
 */
export const transitionProjectPhase = async (id: string,
    projectPhaseTransition: ProjectPhaseTransition, options?: RequestInit): Promise<ProjectPhaseTransitionReceipt> => {

  return customFetch<ProjectPhaseTransitionReceipt>(getTransitionProjectPhaseUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      projectPhaseTransition,)
  }
);}



export const getPublishProjectPhaseUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}/publish`
}

/**
 * Owner or manager only. Publishes a client-safe summary for manager-review or accepted work. It does not alter crew work, files, billing, or payments.
 */
export const publishProjectPhase = async (id: string,
    projectPhasePublication: ProjectPhasePublication, options?: RequestInit): Promise<ProjectPhaseReceipt> => {

  return customFetch<ProjectPhaseReceipt>(getPublishProjectPhaseUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      projectPhasePublication,)
  }
);}



export const getGetProjectPhaseHistoryUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}/history`
}

/**
 * Office-only append-only phase history. Clients and crew cannot read the event ledger.
 */
export const getProjectPhaseHistory = async (id: string, options?: RequestInit): Promise<ProjectPhaseEvent[]> => {

  return customFetch<ProjectPhaseEvent[]>(getGetProjectPhaseHistoryUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListProjectPhaseBillingIntentsUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}/billing-intents`
}

/**
 * Owner, manager, or finance only. Lists existing phase billing intents and associated dashboard drafts. QuickBooks remains the accounting system of record.
 */
export const listProjectPhaseBillingIntents = async (id: string, options?: RequestInit): Promise<ProjectPhaseBillingIntent[]> => {

  return customFetch<ProjectPhaseBillingIntent[]>(getListProjectPhaseBillingIntentsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateProjectPhaseBillingIntentUrl = (id: string,) => {




  return `/api/v1/project-phases/${id}/billing-intents`
}

/**
 * Owner, manager, or finance only. Creates exactly one idempotent dashboard billing draft for an accepted phase and approved estimate. It never posts, sends, charges, credits, or records a QuickBooks payment.
 */
export const createProjectPhaseBillingIntent = async (id: string,
    projectPhaseBillingIntentInput: ProjectPhaseBillingIntentInput, options?: RequestInit): Promise<ProjectPhaseBillingIntentReceipt> => {

  return customFetch<ProjectPhaseBillingIntentReceipt>(getCreateProjectPhaseBillingIntentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      projectPhaseBillingIntentInput,)
  }
);}



export const getListSalesLeadsUrl = () => {




  return `/api/v1/leads`
}

/**
 * Office-only lead list. Owner, manager, and sales can see commercial assessment inquiries; dispatch and finance receive the ordinary operational lead list.
 */
export const listSalesLeads = async ( options?: RequestInit): Promise<SalesLead[]> => {

  return customFetch<SalesLead[]>(getListSalesLeadsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateSalesLeadUrl = () => {




  return `/api/v1/leads`
}

/**
 * Office-only manual lead creation. It records intake only; it does not create a client, property, assessment, estimate, job, or billing record.
 */
export const createSalesLead = async (createSalesLead: CreateSalesLead, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateSalesLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSalesLead,)
  }
);}



export const getConvertSalesLeadUrl = (id: string,) => {




  return `/api/v1/leads/${id}/convert`
}

/**
 * Owner, manager, or sales only. Converts one eligible lead into a linked client and property. Repeating a completed conversion returns the existing linkage. It does not create an estimate, schedule work, dispatch, publish, bill, or call a provider.
 */
export const convertSalesLead = async (id: string,
    salesLeadConversion: SalesLeadConversion, options?: RequestInit): Promise<SalesLeadConversionReceipt> => {

  return customFetch<SalesLeadConversionReceipt>(getConvertSalesLeadUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      salesLeadConversion,)
  }
);}



export const getRecordEstimateDecisionUrl = (id: string,) => {




  return `/api/v1/estimates/${id}/decision`
}

/**
 * Office staff may move a draft estimate to sent. Only an authorized client may approve or decline a current sent estimate for an accessible property. A recorded approval includes the approving identity and timestamp; stale or repeated decisions fail.
 */
export const recordEstimateDecision = async (id: string,
    estimateDecision: EstimateDecision, options?: RequestInit): Promise<EstimateDecisionReceipt> => {

  return customFetch<EstimateDecisionReceipt>(getRecordEstimateDecisionUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      estimateDecision,)
  }
);}



export const getReviseEstimateUrl = (id: string,) => {




  return `/api/v1/estimates/${id}/revise`
}

/**
 * Owner, manager, or sales only. Creates the next revision in the same estimate series. Current revision and draft/sent state are required; an approved scope is immutable and requires a change order.
 */
export const reviseEstimate = async (id: string,
    estimateRevision: EstimateRevision, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getReviseEstimateUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      estimateRevision,)
  }
);}



export const getCreateEstimateChangeOrderUrl = (id: string,) => {




  return `/api/v1/estimates/${id}/change-order`
}

/**
 * Owner, manager, or sales only. Creates a separate draft change order only from an approved estimate. It does not alter the approved scope, post billing, send an invoice, or collect payment.
 */
export const createEstimateChangeOrder = async (id: string,
    estimateChangeOrder: EstimateChangeOrder, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateEstimateChangeOrderUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      estimateChangeOrder,)
  }
);}



export const getPauseRecurringServiceUrl = (id: string,) => {




  return `/api/v1/recurring-services/${id}/pause`
}

/**
 * Owner, manager, or dispatch only. Pauses or resumes future recurrence generation; it does not rewrite existing work orders or billing.
 */
export const pauseRecurringService = async (id: string,
    recurringServicePause: RecurringServicePause, options?: RequestInit): Promise<PublicationReceipt> => {

  return customFetch<PublicationReceipt>(getPauseRecurringServiceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recurringServicePause,)
  }
);}



export const getListInspectionReportsUrl = () => {




  return `/api/v1/inspections`
}

/**
 * Owner, manager, and dispatch receive operational inspection reports. Clients receive only explicitly published reports for accessible properties and never the submitting staff user ID.
 */
export const listInspectionReports = async ( options?: RequestInit): Promise<InspectionReport[]> => {

  return customFetch<InspectionReport[]>(getListInspectionReportsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateInspectionReportUrl = () => {




  return `/api/v1/inspections`
}

/**
 * Records an operational inspection report. It remains private until an owner or manager explicitly publishes it.
 */
export const createInspectionReport = async (createInspectionReport: CreateInspectionReport, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateInspectionReportUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInspectionReport,)
  }
);}



export const getPublishInspectionReportUrl = (id: string,) => {




  return `/api/v1/inspections/${id}/publish`
}

/**
 * Owner or manager only. Makes a report client-visible; it does not alter work, files, billing, payment, or underlying property condition data. Repeating publication is safe.
 */
export const publishInspectionReport = async (id: string, options?: RequestInit): Promise<PublicationReceipt> => {

  return customFetch<PublicationReceipt>(getPublishInspectionReportUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getListBillingDraftsUrl = () => {




  return `/api/v1/billing`
}

/**
 * Office roles receive operational billing drafts. Clients receive only posted, ownership-verified drafts for accessible properties. QuickBooks remains authoritative for posted accounting balances and payments.
 */
export const listBillingDrafts = async ( options?: RequestInit): Promise<BillingDraft[]> => {

  return customFetch<BillingDraft[]>(getListBillingDraftsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateBillingDraftUrl = () => {




  return `/api/v1/billing`
}

/**
 * Creates an idempotent dashboard billing draft under the approved-estimate cap. It never posts, sends, or pays a QuickBooks invoice.
 */
export const createBillingDraft = async (createBillingDraft: CreateBillingDraft, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateBillingDraftUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBillingDraft,)
  }
);}



export const getListDashboardPropertiesUrl = () => {




  return `/api/v1/properties`
}

/**
 * Operational unarchived properties. Client responses omit internal fields; crew only sees properties with active assigned work.
 */
export const listDashboardProperties = async ( options?: RequestInit): Promise<DashboardProperty[]> => {

  return customFetch<DashboardProperty[]>(getListDashboardPropertiesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateDashboardPropertyUrl = () => {




  return `/api/v1/properties`
}

/**
 * Office-only property creation for a client. It records a property only; it does not schedule work, grant client access, publish material, or create billing.
 */
export const createDashboardProperty = async (createDashboardProperty: CreateDashboardProperty, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateDashboardPropertyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDashboardProperty,)
  }
);}



export const getGetPropertyTimelineUrl = (id: string,) => {




  return `/api/v1/properties/${id}/timeline`
}

/**
 * Latest 200 captured field events and inspection reports. Clients require field/work publication and receive only published inspections. Crew sees assigned work only.
 */
export const getPropertyTimeline = async (id: string, options?: RequestInit): Promise<PropertyTimelineEvent[]> => {

  return customFetch<PropertyTimelineEvent[]>(getGetPropertyTimelineUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetPropertyWorkspaceUrl = (id: string,) => {




  return `/api/v1/properties/${id}/workspace`
}

/**
 * Permission-guarded property workspace projection. Client and crew views exclude access instructions and internal notes; office views include only notes linked to the client and this property or client-wide notes.
 */
export const getPropertyWorkspace = async (id: string, options?: RequestInit): Promise<PropertyWorkspace> => {

  return customFetch<PropertyWorkspace>(getGetPropertyWorkspaceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListPropertyFilesUrl = (id: string,) => {




  return `/api/v1/properties/${id}/files`
}

/**
 * Ready file metadata only; clients see published files and crew sees files for assigned work. Object keys and storage URLs are never included.
 */
export const listPropertyFiles = async (id: string, options?: RequestInit): Promise<PropertyFile[]> => {

  return customFetch<PropertyFile[]>(getListPropertyFilesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetPrivateFileContentUrl = (id: string,) => {




  return `/api/v1/files/${id}/content`
}

/**
 * Authorized private image bytes; never a storage URL. Requires property grants and publication or crew assignment. Response is uncached.
 */
export const getPrivateFileContent = async (id: string, options?: RequestInit): Promise<Blob> => {

  return customFetch<Blob>(getGetPrivateFileContentUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUploadFieldPhotoUrl = (id: string,) => {




  return `/api/v1/files/${id}`
}

/**
 * Raw image bytes (not multipart or JSON). Keep operation ID, original bytes, property, work and classification unchanged on retry. Never publishes content. Supports exact image/jpeg, image/png or image/webp Content-Type.
 */
export const uploadFieldPhoto = async (id: string,
    uploadFieldPhotoBody: Blob,
    headers: UploadFieldPhotoHeaders, options?: RequestInit): Promise<PhotoUploadReceipt> => {


  const uploadHeaders = new Headers(options?.headers);
  const mime = uploadHeaders.get('Content-Type') || uploadFieldPhotoBody.type;
  if (!['image/jpeg', 'image/png', 'image/webp'].includes(mime))
    throw new TypeError('Photo Blob or Content-Type must declare JPEG, PNG, or WebP');
  uploadHeaders.set('Content-Type', mime);
  for (const [key, value] of Object.entries(headers))
    if (value !== undefined) uploadHeaders.set(key, value);

  return customFetch<PhotoUploadReceipt>(getUploadFieldPhotoUrl(id),
  {
    ...options,
    method: 'POST',
    headers: uploadHeaders,
    body: uploadFieldPhotoBody
  }
);}



export const getListServiceAgreementsUrl = (params?: ListServiceAgreementsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/service-agreements?${stringifiedParams}` : `/api/v1/service-agreements`
}

/**
 * Management/finance financial projection; dispatch scope/dates only. No client, crew or sales access.
 */
export const listServiceAgreements = async (params?: ListServiceAgreementsParams, options?: RequestInit): Promise<ServiceAgreementPage> => {

  return customFetch<ServiceAgreementPage>(getListServiceAgreementsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateServiceAgreementUrl = () => {




  return `/api/v1/service-agreements`
}

export const createServiceAgreement = async (createServiceAgreement: CreateServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getCreateServiceAgreementUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createServiceAgreement,)
  }
);}



export const getGetServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}`
}

export const getServiceAgreement = async (id: string, options?: RequestInit): Promise<ServiceAgreement> => {

  return customFetch<ServiceAgreement>(getGetServiceAgreementUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getUpdateServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}`
}

export const updateServiceAgreement = async (id: string,
    editServiceAgreement: EditServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getUpdateServiceAgreementUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editServiceAgreement,)
  }
);}



export const getPreviewServiceAgreementActivationUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/activation-preview`
}

export const previewServiceAgreementActivation = async (id: string,
    agreementVersion: AgreementVersion, options?: RequestInit): Promise<AgreementActivationPreview> => {

  return customFetch<AgreementActivationPreview>(getPreviewServiceAgreementActivationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementVersion,)
  }
);}



export const getActivateServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/activate`
}

export const activateServiceAgreement = async (id: string,
    agreementVersion: AgreementVersion, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getActivateServiceAgreementUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementVersion,)
  }
);}



export const getCancelServiceAgreementUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/cancel`
}

export const cancelServiceAgreement = async (id: string,
    cancelServiceAgreement: CancelServiceAgreement, options?: RequestInit): Promise<ServiceAgreementFinancial> => {

  return customFetch<ServiceAgreementFinancial>(getCancelServiceAgreementUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cancelServiceAgreement,)
  }
);}



export const getPreviewAgreementChargeUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/charge-preview`
}

export const previewAgreementCharge = async (id: string,
    agreementChargeSource: AgreementChargeSource, options?: RequestInit): Promise<AgreementChargePreview> => {

  return customFetch<AgreementChargePreview>(getPreviewAgreementChargeUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeSource,)
  }
);}



export const getListAgreementChargesUrl = (id: string,
    params?: ListAgreementChargesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/service-agreements/${id}/charges?${stringifiedParams}` : `/api/v1/service-agreements/${id}/charges`
}

export const listAgreementCharges = async (id: string,
    params?: ListAgreementChargesParams, options?: RequestInit): Promise<AgreementChargeHistory> => {

  return customFetch<AgreementChargeHistory>(getListAgreementChargesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPrepareAgreementChargeUrl = (id: string,) => {




  return `/api/v1/service-agreements/${id}/charges`
}

export const prepareAgreementCharge = async (id: string,
    agreementChargeSource: AgreementChargeSource, options?: RequestInit): Promise<AgreementChargeReceipt> => {

  return customFetch<AgreementChargeReceipt>(getPrepareAgreementChargeUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeSource,)
  }
);}



export const getGetAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/review`
}

export const getAgreementChargeReview = async (id: string, options?: RequestInit): Promise<AgreementChargeReview> => {

  return customFetch<AgreementChargeReview>(getGetAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPreviewAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/review-preview`
}

export const previewAgreementChargeReview = async (id: string,
    agreementChargeReviewInput: AgreementChargeReviewInput, options?: RequestInit): Promise<AgreementChargeReviewPreview> => {

  return customFetch<AgreementChargeReviewPreview>(getPreviewAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeReviewInput,)
  }
);}



export const getListAgreementChargeReviewsUrl = (id: string,
    params?: ListAgreementChargeReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/agreement-charges/${id}/reviews?${stringifiedParams}` : `/api/v1/agreement-charges/${id}/reviews`
}

export const listAgreementChargeReviews = async (id: string,
    params?: ListAgreementChargeReviewsParams, options?: RequestInit): Promise<AgreementChargeReviewHistory> => {

  return customFetch<AgreementChargeReviewHistory>(getListAgreementChargeReviewsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getRecordAgreementChargeReviewUrl = (id: string,) => {




  return `/api/v1/agreement-charges/${id}/reviews`
}

export const recordAgreementChargeReview = async (id: string,
    agreementChargeReviewRecordInput: AgreementChargeReviewRecordInput, options?: RequestInit): Promise<AgreementChargeReviewReceipt> => {

  return customFetch<AgreementChargeReviewReceipt>(getRecordAgreementChargeReviewUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementChargeReviewRecordInput,)
  }
);}



export const getListAgreementChargeQueueUrl = (params?: ListAgreementChargeQueueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/agreement-charge-queue?${stringifiedParams}` : `/api/v1/agreement-charge-queue`
}

/**
 * Management/finance current action queue. Capped, unmatched and prepared cancellation issues remain visible. Recheck eligibility before preparing.
 */
export const listAgreementChargeQueue = async (params?: ListAgreementChargeQueueParams, options?: RequestInit): Promise<AgreementChargeQueue> => {

  return customFetch<AgreementChargeQueue>(getListAgreementChargeQueueUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListAgreementPreparationJobsUrl = (params?: ListAgreementPreparationJobsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/agreement-preparation-jobs?${stringifiedParams}` : `/api/v1/agreement-preparation-jobs`
}

/**
 * Management and finance durable billing-draft preparation queue. This never posts an invoice, sends a message, or charges a payment method.
 */
export const listAgreementPreparationJobs = async (params?: ListAgreementPreparationJobsParams, options?: RequestInit): Promise<AgreementPreparationJobPage> => {

  return customFetch<AgreementPreparationJobPage>(getListAgreementPreparationJobsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetAgreementPreparationJobUrl = (id: string,) => {




  return `/api/v1/agreement-preparation-jobs/${id}`
}

export const getAgreementPreparationJob = async (id: string, options?: RequestInit): Promise<AgreementPreparationJob> => {

  return customFetch<AgreementPreparationJob>(getGetAgreementPreparationJobUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPreviewAgreementPreparationRetryUrl = (id: string,) => {




  return `/api/v1/agreement-preparation-jobs/${id}/retry-preview`
}

/**
 * Zero-write eligibility evaluation before retrying a failed preparation job. It never calls accounting or messaging providers.
 */
export const previewAgreementPreparationRetry = async (id: string,
    agreementPreparationRetryPreviewInput: AgreementPreparationRetryPreviewInput, options?: RequestInit): Promise<AgreementPreparationRetryPreview> => {

  return customFetch<AgreementPreparationRetryPreview>(getPreviewAgreementPreparationRetryUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementPreparationRetryPreviewInput,)
  }
);}



export const getRetryAgreementPreparationUrl = (id: string,) => {




  return `/api/v1/agreement-preparation-jobs/${id}/retries`
}

/**
 * Records an idempotent office retry request for an eligible failed job. The worker creates a billing draft later; this endpoint never posts an invoice or sends a message.
 */
export const retryAgreementPreparation = async (id: string,
    agreementPreparationRetryInput: AgreementPreparationRetryInput, options?: RequestInit): Promise<AgreementPreparationRetryReceipt> => {

  return customFetch<AgreementPreparationRetryReceipt>(getRetryAgreementPreparationUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agreementPreparationRetryInput,)
  }
);}



export const getListAgreementRecurrencesUrl = () => {




  return `/api/v1/recurring-services`
}

export const listAgreementRecurrences = async ( options?: RequestInit): Promise<AgreementRecurrenceOption[]> => {

  return customFetch<AgreementRecurrenceOption[]>(getListAgreementRecurrencesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateRecurringServiceUrl = () => {




  return `/api/v1/recurring-services`
}

/**
 * Owner, manager, or dispatch only. Records a recurrence configuration; occurrence generation remains worker-controlled.
 */
export const createRecurringService = async (createRecurringService: CreateRecurringService, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateRecurringServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRecurringService,)
  }
);}



export const getListAgreementEstimatesUrl = () => {




  return `/api/v1/estimates`
}

export const listAgreementEstimates = async ( options?: RequestInit): Promise<AgreementEstimateOption[]> => {

  return customFetch<AgreementEstimateOption[]>(getListAgreementEstimatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateSalesEstimateUrl = () => {




  return `/api/v1/estimates`
}

/**
 * Owner, manager, or sales only. Creates a draft estimate for an operational property. It does not send, approve, schedule, dispatch, publish, post billing, or collect payment.
 */
export const createSalesEstimate = async (createSalesEstimate: CreateSalesEstimate, options?: RequestInit): Promise<CreatedResource> => {

  return customFetch<CreatedResource>(getCreateSalesEstimateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSalesEstimate,)
  }
);}



