import type { BlockDef } from "./block-registry.shared";
import {
  ALIGN_OPTIONS,
  BENEFIT_LAYOUT_OPTIONS,
  BUTTON_ACTION_OPTIONS,
  BUTTON_VARIANT_OPTIONS,
  CALLOUT_VARIANT_OPTIONS,
  COLUMNS_EXTENDED_OPTIONS,
  COLUMNS_OPTIONS,
  CTA_VARIANT_OPTIONS,
  DIVIDER_STYLE_OPTIONS,
  EXPERIENCE_LEVEL_OPTIONS,
  FEATURE_LIST_COLUMNS_OPTIONS,
  HEADING_LEVEL_OPTIONS,
  HERO_LAYOUT_OPTIONS,
  HERO_MIN_HEIGHT_OPTIONS,
  IMAGE_POSITION_OPTIONS,
  IMAGE_WIDTH_OPTIONS,
  LINK_LIST_COLUMNS_OPTIONS,
  SHARED_MOBILE_IMAGE_DEFAULTS,
  SHARED_MOBILE_IMAGE_PROP_DEFS,
  SPACING_OPTIONS,
  VIDEO_ASPECT_OPTIONS,
} from "./block-registry.shared";

export const BASE_BLOCK_REGISTRY: BlockDef[] = [
  {
    type: "hero",
    label: "Hero",
    iconName: "Sparkles",
    description: "Full-width hero with heading, subheading, and CTA buttons",
    category: "hero",
    defaultProps: {
      heading: "Welcome to Core Platform",
      accentHeading: "",
      headingColor: "",
      accentHeadingColor: "",
      subheading:
        "Connecting members with verified providers, practical resources, and configurable community tools.",
      subheadingColor: "",
      ctaText: "Find a Verified Provider",
      ctaLink: "/directory",
      ctaAction: "internal-link",
      ctaOpenInNewTab: false,
      ctaFormSlug: "contact-form",
      ctaModalTitle: "",
      ctaModalDescription: "",
      ctaSecondaryText: "Learn More",
      ctaSecondaryLink: "/about",
      ctaSecondaryAction: "internal-link",
      ctaSecondaryOpenInNewTab: false,
      ctaSecondaryFormSlug: "contact-form",
      ctaSecondaryModalTitle: "",
      ctaSecondaryModalDescription: "",
      backgroundImageUrl: "",
      backgroundPositionX: 50,
      backgroundPositionY: 50,
      overlayColor: "#000000",
      overlayOpacity: 50,
      badge: "",
      layout: "stacked",
      videoBackgroundUrl: "",
      minHeight: "420",
    },
    propDefs: [
      { key: "badge", label: "Badge Text", type: "text", placeholder: "e.g. New, Coming Soon" },
      { key: "heading", label: "Heading", type: "text", placeholder: "Main heading" },
      {
        key: "accentHeading",
        label: "Accent Heading",
        type: "text",
        placeholder: "Optional highlighted heading text",
      },
      { key: "headingColor", label: "Heading Color", type: "color", placeholder: "#ffffff" },
      {
        key: "accentHeadingColor",
        label: "Accent Heading Color",
        type: "color",
        placeholder: "#89cda1",
      },
      {
        key: "subheading",
        label: "Subheading",
        type: "textarea",
        placeholder: "Supporting text beneath the heading",
      },
      { key: "subheadingColor", label: "Subheading Color", type: "color", placeholder: "#ffffff" },
      {
        key: "ctaText",
        label: "Primary Button Text",
        type: "text",
        placeholder: "e.g. Find a Verified Provider",
      },
      {
        key: "ctaAction",
        label: "Primary Button Action",
        type: "select",
        options: BUTTON_ACTION_OPTIONS,
      },
      { key: "ctaLink", label: "Primary Button Link", type: "url", placeholder: "/directory" },
      { key: "ctaOpenInNewTab", label: "Primary Open In New Tab", type: "boolean" },
      { key: "ctaFormSlug", label: "Primary Button Form", type: "form-select" },
      {
        key: "ctaModalTitle",
        label: "Primary Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "ctaModalDescription",
        label: "Primary Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
      {
        key: "ctaSecondaryText",
        label: "Secondary Button Text",
        type: "text",
        placeholder: "e.g. Learn More",
      },
      {
        key: "ctaSecondaryAction",
        label: "Secondary Button Action",
        type: "select",
        options: BUTTON_ACTION_OPTIONS,
      },
      {
        key: "ctaSecondaryLink",
        label: "Secondary Button Link",
        type: "url",
        placeholder: "/about",
      },
      { key: "ctaSecondaryOpenInNewTab", label: "Secondary Open In New Tab", type: "boolean" },
      { key: "ctaSecondaryFormSlug", label: "Secondary Button Form", type: "form-select" },
      {
        key: "ctaSecondaryModalTitle",
        label: "Secondary Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "ctaSecondaryModalDescription",
        label: "Secondary Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
      {
        key: "backgroundImageUrl",
        label: "Background Image",
        type: "image-url",
        placeholder: "Upload or select image",
      },
      {
        key: "backgroundPositionX",
        label: "Image Position X (%)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        key: "backgroundPositionY",
        label: "Image Position Y (%)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        key: "videoBackgroundUrl",
        label: "Video Background URL",
        type: "url",
        placeholder: "https://example.com/video.mp4",
      },
      { key: "overlayColor", label: "Overlay Color", type: "color", placeholder: "#000000" },
      { key: "overlayOpacity", label: "Overlay Opacity (%)", type: "number", min: 0, max: 100 },
      { key: "layout", label: "Layout", type: "select", options: HERO_LAYOUT_OPTIONS },
      {
        key: "minHeight",
        label: "Min Height (px)",
        type: "select",
        options: HERO_MIN_HEIGHT_OPTIONS,
      },
    ],
  },
  {
    type: "section-header",
    label: "Section Header",
    iconName: "Heading",
    description: "Title, optional eyebrow label, and subtitle",
    category: "layout",
    defaultProps: {
      eyebrow: "Our Approach",
      title: "Why Platform-Approved Providers Matter",
      subtitle: "We match members with verified providers who understand their needs and context.",
      alignment: "center",
      headingLevel: "h2",
    },
    propDefs: [
      {
        key: "eyebrow",
        label: "Eyebrow Label",
        type: "text",
        placeholder: "Small label above title",
      },
      { key: "title", label: "Title", type: "text", placeholder: "Section title" },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Supporting description",
      },
      { key: "alignment", label: "Alignment", type: "select", options: ALIGN_OPTIONS },
      {
        key: "headingLevel",
        label: "Heading Level",
        type: "select",
        options: HEADING_LEVEL_OPTIONS,
      },
    ],
  },
  {
    type: "rich-text",
    label: "Rich Text",
    iconName: "FileText",
    description: "Free-form text content with alignment control",
    category: "content",
    defaultProps: {
      content: "<p>Enter your content here.</p>",
      alignment: "left",
    },
    propDefs: [
      { key: "content", label: "Content", type: "richtext", placeholder: "Enter content..." },
      { key: "alignment", label: "Alignment", type: "select", options: ALIGN_OPTIONS },
    ],
  },
  {
    type: "text-image",
    label: "Text + Image",
    iconName: "LayoutTemplate",
    description: "Side-by-side text and image with configurable position",
    category: "content",
    defaultProps: {
      eyebrow: "Our Story",
      heading: "About Our Mission",
      subtitle:
        "Use this supporting introduction to frame the section before the main body copy begins.",
      body: "<p>We provide access to culturally informed providers who understand what it means to grow up between worlds.</p>",
      alignment: "left",
      headingLevel: "h2",
      imageUrl: "",
      imageAlt: "About Core Platform",
      imageCaption: "",
      imagePosition: "right",
      ...SHARED_MOBILE_IMAGE_DEFAULTS,
    },
    propDefs: [
      {
        key: "eyebrow",
        label: "Eyebrow Label",
        type: "text",
        placeholder: "Small label above title",
      },
      { key: "heading", label: "Section Title", type: "text", placeholder: "Section heading" },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Supporting description",
      },
      { key: "alignment", label: "Alignment", type: "select", options: ALIGN_OPTIONS },
      {
        key: "headingLevel",
        label: "Heading Level",
        type: "select",
        options: HEADING_LEVEL_OPTIONS,
      },
      { key: "body", label: "Body Text", type: "richtext", placeholder: "Main text content" },
      { key: "imageUrl", label: "Image", type: "image-url", placeholder: "Upload or select image" },
      {
        key: "imageAlt",
        label: "Image Alt Text",
        type: "text",
        placeholder: "Descriptive alt text",
      },
      {
        key: "imageCaption",
        label: "Image Caption",
        type: "text",
        placeholder: "Optional caption",
      },
      {
        key: "imagePosition",
        label: "Image Position",
        type: "select",
        options: IMAGE_POSITION_OPTIONS,
      },
      ...SHARED_MOBILE_IMAGE_PROP_DEFS,
    ],
  },
  {
    type: "two-column-text",
    label: "Two Column Text",
    iconName: "LayoutTemplate",
    description: "Two side-by-side content columns with optional bullet lists",
    category: "content",
    defaultProps: {
      title: "Compare Your Options",
      subtitle: "",
      leftHeading: "Column One",
      leftBody: "<p>Use this space for supporting copy before the list.</p>",
      leftItems: [{ text: "Bullet point one" }, { text: "Bullet point two" }],
      rightHeading: "Column Two",
      rightBody: "<p>Use this column for a second list or additional detail.</p>",
      rightItems: [{ text: "Bullet point one" }, { text: "Bullet point two" }],
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "Optional section heading",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Optional supporting description",
      },
      {
        key: "leftHeading",
        label: "Left Column Heading",
        type: "text",
        placeholder: "Left column title",
      },
      {
        key: "leftBody",
        label: "Left Column Body",
        type: "richtext",
        placeholder: "Optional supporting text",
      },
      {
        key: "leftItems",
        label: "Left Column Items",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Item Text", type: "text", placeholder: "Bullet point" },
        ],
      },
      {
        key: "rightHeading",
        label: "Right Column Heading",
        type: "text",
        placeholder: "Right column title",
      },
      {
        key: "rightBody",
        label: "Right Column Body",
        type: "richtext",
        placeholder: "Optional supporting text",
      },
      {
        key: "rightItems",
        label: "Right Column Items",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Item Text", type: "text", placeholder: "Bullet point" },
        ],
      },
    ],
  },
  {
    type: "callout-box",
    label: "Callout Box",
    iconName: "Quote",
    description: "Highlighted callout content with optional button",
    category: "content",
    defaultProps: {
      title: "Important Takeaway",
      subtitle: "",
      content:
        "<p>Use this callout to highlight a key message, important note, or short supporting explanation.</p>",
      variant: "accent",
      ctaText: "",
      ctaLink: "",
      ctaAction: "internal-link",
      ctaOpenInNewTab: false,
      ctaFormSlug: "contact-form",
      ctaModalTitle: "",
      ctaModalDescription: "",
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "Optional section heading",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Optional supporting description",
      },
      {
        key: "content",
        label: "Content",
        type: "richtext",
        placeholder: "Add highlighted content...",
      },
      { key: "variant", label: "Style Variant", type: "select", options: CALLOUT_VARIANT_OPTIONS },
      { key: "ctaText", label: "Button Text", type: "text", placeholder: "Optional button label" },
      { key: "ctaAction", label: "Button Action", type: "select", options: BUTTON_ACTION_OPTIONS },
      { key: "ctaLink", label: "Button Link", type: "url", placeholder: "/page or https://..." },
      { key: "ctaOpenInNewTab", label: "Open In New Tab", type: "boolean" },
      { key: "ctaFormSlug", label: "Assigned Form", type: "form-select" },
      {
        key: "ctaModalTitle",
        label: "Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "ctaModalDescription",
        label: "Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
    ],
  },
  {
    type: "link-list",
    label: "Link List",
    iconName: "List",
    description: "Editorial list of resource links with optional descriptions",
    category: "content",
    defaultProps: {
      title: "Helpful Resources",
      subtitle: "",
      columns: "1",
      links: [
        { label: "Resource title", description: "Short supporting description", url: "#" },
        { label: "Another resource", description: "Optional summary text", url: "#" },
      ],
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "Optional section heading",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Optional supporting description",
      },
      { key: "columns", label: "Columns", type: "select", options: LINK_LIST_COLUMNS_OPTIONS },
      {
        key: "links",
        label: "Links",
        type: "array-items",
        itemSchema: [
          { key: "label", label: "Label", type: "text", placeholder: "Link title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Optional supporting text",
          },
          { key: "url", label: "URL", type: "url", placeholder: "/page or https://..." },
        ],
      },
    ],
  },
  {
    type: "cta",
    label: "Call to Action",
    iconName: "Megaphone",
    description: "Bold call-to-action section with one or two buttons",
    category: "conversion",
    defaultProps: {
      heading: "Ready to Get Started?",
      subheading: "Find a platform-approved provider and begin your next step today.",
      primaryText: "Browse the Directory",
      primaryLink: "/directory",
      primaryAction: "internal-link",
      primaryOpenInNewTab: false,
      primaryFormSlug: "contact-form",
      primaryModalTitle: "",
      primaryModalDescription: "",
      secondaryText: "Join the Network",
      secondaryLink: "/join",
      secondaryAction: "internal-link",
      secondaryOpenInNewTab: false,
      secondaryFormSlug: "contact-form",
      secondaryModalTitle: "",
      secondaryModalDescription: "",
      variant: "dark",
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "CTA heading" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      { key: "primaryText", label: "Primary Button", type: "text", placeholder: "Button label" },
      {
        key: "primaryAction",
        label: "Primary Button Action",
        type: "select",
        options: BUTTON_ACTION_OPTIONS,
      },
      { key: "primaryLink", label: "Primary Button Link", type: "url", placeholder: "/directory" },
      { key: "primaryOpenInNewTab", label: "Primary Open In New Tab", type: "boolean" },
      { key: "primaryFormSlug", label: "Primary Button Form", type: "form-select" },
      {
        key: "primaryModalTitle",
        label: "Primary Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "primaryModalDescription",
        label: "Primary Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
      {
        key: "secondaryText",
        label: "Secondary Button",
        type: "text",
        placeholder: "Optional secondary button",
      },
      {
        key: "secondaryAction",
        label: "Secondary Button Action",
        type: "select",
        options: BUTTON_ACTION_OPTIONS,
      },
      { key: "secondaryLink", label: "Secondary Button Link", type: "url", placeholder: "/about" },
      { key: "secondaryOpenInNewTab", label: "Secondary Open In New Tab", type: "boolean" },
      { key: "secondaryFormSlug", label: "Secondary Button Form", type: "form-select" },
      {
        key: "secondaryModalTitle",
        label: "Secondary Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "secondaryModalDescription",
        label: "Secondary Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
      { key: "variant", label: "Style Variant", type: "select", options: CTA_VARIANT_OPTIONS },
    ],
  },
  {
    type: "cards-grid",
    label: "Cards Grid",
    iconName: "LayoutGrid",
    description: "A configurable grid of icon + text cards",
    category: "content",
    defaultProps: {
      title: "Why Choose Core Platform",
      subtitle: "",
      columns: "3",
      cards: [
        {
          title: "Culturally Informed",
          description: "Verified providers who serve this community.",
          icon: "Globe",
        },
        {
          title: "Specialized Support",
          description: "Targeted help for unique Core Platform challenges.",
          icon: "Heart",
        },
        {
          title: "Global Community",
          description: "Connect with others who share your journey.",
          icon: "Users",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Grid section title" },
      {
        key: "subtitle",
        label: "Section Subtitle",
        type: "text",
        placeholder: "Optional subtitle",
      },
      { key: "columns", label: "Columns", type: "select", options: COLUMNS_OPTIONS },
      {
        key: "cards",
        label: "Cards",
        type: "array-items",
        itemSchema: [
          { key: "title", label: "Card Title", type: "text", placeholder: "Card title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Card description",
          },
          {
            key: "icon",
            label: "Icon Name (Lucide)",
            type: "text",
            placeholder: "e.g. Globe, Heart, Users",
          },
        ],
      },
    ],
  },
  {
    type: "faq",
    label: "FAQ",
    iconName: "HelpCircle",
    description: "Collapsible frequently asked questions accordion",
    category: "content",
    defaultProps: {
      title: "Frequently Asked Questions",
      items: [
        {
          question: "Who is this platform for?",
          answer:
            "Core Platform can support configurable directories, member communities, education, events, and resource libraries.",
        },
        {
          question: "How are verified providers vetted?",
          answer:
            "All verified providers complete a thorough application and background verification process.",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "FAQ section heading" },
      {
        key: "items",
        label: "Questions",
        type: "array-items",
        itemSchema: [
          { key: "question", label: "Question", type: "text", placeholder: "FAQ question" },
          { key: "answer", label: "Answer", type: "textarea", placeholder: "FAQ answer" },
        ],
      },
    ],
  },
  {
    type: "testimonials",
    label: "Testimonials",
    iconName: "Quote",
    description: "Quote cards from clients or community members",
    category: "social-proof",
    defaultProps: {
      title: "What Our Community Says",
      items: [
        {
          quote:
            "Finding a verified provider who truly understood my Core Platform experience was life-changing.",
          name: "Sarah M.",
          role: "Core Platform Client",
          location: "Singapore",
        },
        {
          quote: "I finally feel seen and understood in a way I never did before.",
          name: "James T.",
          role: "Core Platform Client",
          location: "Germany",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Testimonials heading" },
      {
        key: "items",
        label: "Testimonials",
        type: "array-items",
        itemSchema: [
          { key: "quote", label: "Quote", type: "textarea", placeholder: "Testimonial text" },
          { key: "name", label: "Name", type: "text", placeholder: "Person's name" },
          { key: "role", label: "Role", type: "text", placeholder: "e.g. Core Platform Client" },
          { key: "location", label: "Location", type: "text", placeholder: "e.g. Singapore" },
        ],
      },
    ],
  },
  {
    type: "featured-professionals",
    label: "Featured Verified Providers",
    iconName: "UserCheck",
    description: "Live grid of featured providers from the directory",
    category: "data",
    defaultProps: {
      title: "Meet Our Verified Providers",
      subtitle: "Browse our network of platform-approved professionals.",
      limit: 3,
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Supporting text" },
      { key: "limit", label: "Max Providers to Show", type: "number", min: 1, max: 12 },
    ],
  },
  {
    type: "featured-counselors",
    label: "Featured Verified Providers",
    iconName: "UserCheck",
    description: "Live grid of featured providers from the directory",
    category: "data",
    defaultProps: {
      title: "Meet Our Verified Providers",
      subtitle: "Browse our network of platform-approved professionals.",
      limit: 3,
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Supporting text" },
      { key: "limit", label: "Max Providers to Show", type: "number", min: 1, max: 12 },
    ],
  },
  {
    type: "events-preview",
    label: "Events Preview",
    iconName: "CalendarDays",
    description: "Live upcoming events from the events system",
    category: "data",
    defaultProps: {
      title: "Upcoming Events",
      subtitle: "Join our community events and webinars.",
      limit: 4,
      ctaText: "",
      ctaLink: "",
      ctaAction: "internal-link",
      ctaOpenInNewTab: false,
      ctaFormSlug: "contact-form",
      ctaModalTitle: "",
      ctaModalDescription: "",
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Supporting text" },
      { key: "limit", label: "Max Events to Show", type: "number", min: 1, max: 12 },
      { key: "ctaText", label: "Button Text", type: "text", placeholder: "Optional button label" },
      { key: "ctaAction", label: "Button Action", type: "select", options: BUTTON_ACTION_OPTIONS },
      { key: "ctaLink", label: "Button Link", type: "url", placeholder: "/events or https://..." },
      { key: "ctaOpenInNewTab", label: "Open In New Tab", type: "boolean" },
      { key: "ctaFormSlug", label: "Assigned Form", type: "form-select" },
      {
        key: "ctaModalTitle",
        label: "Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "ctaModalDescription",
        label: "Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
    ],
  },
  {
    type: "blog-preview",
    label: "Blog Preview",
    iconName: "BookOpen",
    description: "Live featured blog/insights articles",
    category: "data",
    defaultProps: {
      title: "Latest Insights",
      subtitle: "Resources and perspectives for the Core Platform community.",
      limit: 5,
      enableHoverMotion: true,
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Supporting text" },
      { key: "limit", label: "Max Articles to Show", type: "number", min: 1, max: 12 },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "button-group",
    label: "Button Group",
    iconName: "MousePointerClick",
    description: "One or more buttons in a row",
    category: "conversion",
    defaultProps: {
      alignment: "center",
      buttons: [
        {
          text: "Get Started",
          action: "url",
          link: "/directory",
          formSlug: "contact-form",
          modalTitle: "",
          modalDescription: "",
          variant: "default",
        },
        {
          text: "Learn More",
          action: "url",
          link: "/about",
          formSlug: "contact-form",
          modalTitle: "",
          modalDescription: "",
          variant: "outline",
        },
      ],
    },
    propDefs: [
      { key: "alignment", label: "Alignment", type: "select", options: ALIGN_OPTIONS },
      {
        key: "buttons",
        label: "Buttons",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Button Text", type: "text", placeholder: "Button label" },
          { key: "action", label: "Action", type: "select", options: BUTTON_ACTION_OPTIONS },
          { key: "link", label: "Link", type: "url", placeholder: "/page or https://..." },
          { key: "openInNewTab", label: "Open In New Tab", type: "boolean" },
          { key: "formSlug", label: "Assigned Form", type: "form-select" },
          {
            key: "modalTitle",
            label: "Modal Title",
            type: "text",
            placeholder: "Optional modal title override",
          },
          {
            key: "modalDescription",
            label: "Modal Description",
            type: "textarea",
            placeholder: "Optional modal description",
          },
          { key: "variant", label: "Style", type: "select", options: BUTTON_VARIANT_OPTIONS },
        ],
      },
    ],
  },
  {
    type: "image-block",
    label: "Image Block",
    iconName: "Image",
    description: "A standalone image with optional caption",
    category: "media",
    defaultProps: {
      imageUrl: "",
      alt: "",
      caption: "",
      width: "contained",
      ...SHARED_MOBILE_IMAGE_DEFAULTS,
    },
    propDefs: [
      { key: "imageUrl", label: "Image", type: "image-url", placeholder: "Upload or select image" },
      {
        key: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "Descriptive alt text for accessibility",
      },
      { key: "caption", label: "Caption", type: "text", placeholder: "Optional image caption" },
      { key: "width", label: "Image Width", type: "select", options: IMAGE_WIDTH_OPTIONS },
      ...SHARED_MOBILE_IMAGE_PROP_DEFS,
    ],
  },
  {
    type: "video-embed",
    label: "Video Embed",
    iconName: "Play",
    description: "Embed a YouTube or Vimeo video",
    category: "media",
    defaultProps: {
      url: "",
      title: "",
      aspectRatio: "16/9",
    },
    propDefs: [
      {
        key: "url",
        label: "Video URL (YouTube or Vimeo)",
        type: "url",
        placeholder: "https://youtube.com/...",
      },
      { key: "title", label: "Title (optional)", type: "text", placeholder: "Video title" },
      { key: "aspectRatio", label: "Aspect Ratio", type: "select", options: VIDEO_ASPECT_OPTIONS },
    ],
  },
  {
    type: "raw-html",
    label: "Raw HTML / Embed",
    iconName: "FileText",
    description: "Trusted raw HTML, scripts, iframes, or 3rd-party embed code",
    category: "media",
    defaultProps: {
      title: "",
      subtitle: "",
      html: '<div class="rounded-xl border p-6 text-center text-sm text-muted-foreground">Paste trusted embed code here.</div>',
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "Optional section heading",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "textarea",
        placeholder: "Optional supporting description",
      },
      {
        key: "html",
        label: "HTML / Embed Code",
        type: "textarea",
        placeholder: "<iframe ...></iframe>",
      },
    ],
  },
  {
    type: "contact-info",
    label: "Contact Info",
    iconName: "Phone",
    description: "A list of contact details with icons",
    category: "content",
    defaultProps: {
      title: "Get in Touch",
      items: [
        { icon: "MapPin", label: "Location", value: "Global - serving members worldwide" },
        { icon: "Globe", label: "Website", value: "www.coreplatform.com" },
      ],
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "Contact section heading",
      },
      {
        key: "items",
        label: "Contact Items",
        type: "array-items",
        itemSchema: [
          {
            key: "icon",
            label: "Icon (Lucide name)",
            type: "text",
            placeholder: "e.g. MapPin, Mail, Phone",
          },
          { key: "label", label: "Label", type: "text", placeholder: "e.g. Email, Phone" },
          { key: "value", label: "Value", type: "text", placeholder: "Contact detail" },
        ],
      },
    ],
  },
  {
    type: "divider",
    label: "Divider / Spacer",
    iconName: "Minus",
    description: "Visual divider or empty spacing between sections",
    category: "layout",
    defaultProps: {
      style: "spacer",
      spacing: "md",
    },
    propDefs: [
      { key: "style", label: "Style", type: "select", options: DIVIDER_STYLE_OPTIONS },
      { key: "spacing", label: "Spacing", type: "select", options: SPACING_OPTIONS },
    ],
  },
  {
    type: "feature-list",
    label: "Feature List",
    iconName: "List",
    description: "Icon + title + description features in a configurable column layout",
    category: "content",
    defaultProps: {
      title: "Key Features",
      subtitle: "",
      columns: "3",
      features: [
        {
          icon: "CheckCircle",
          title: "Vetted Professionals",
          description: "Every professional is carefully reviewed and verified.",
        },
        {
          icon: "Globe",
          title: "Global Reach",
          description: "Connect with professionals worldwide.",
        },
        {
          icon: "Heart",
          title: "Culturally Informed",
          description: "Professionals who understand the Core Platform experience.",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      { key: "columns", label: "Columns", type: "select", options: FEATURE_LIST_COLUMNS_OPTIONS },
      {
        key: "features",
        label: "Features",
        type: "array-items",
        itemSchema: [
          {
            key: "icon",
            label: "Icon (Lucide)",
            type: "text",
            placeholder: "e.g. CheckCircle, Globe",
          },
          { key: "title", label: "Title", type: "text", placeholder: "Feature title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Feature description",
          },
        ],
      },
    ],
  },
  {
    type: "objection-busters",
    label: "Objection Busters",
    iconName: "ShieldCheck",
    description: "Address common concerns with reassuring responses",
    category: "conversion",
    defaultProps: {
      title: "Common Questions & Concerns",
      subtitle: "",
      items: [
        {
          concern: "Will the professional understand my background?",
          response:
            "Every professional in our directory has specific training or lived experience with cross-cultural populations.",
        },
        {
          concern: "Can services be delivered online?",
          response:
            "Many providers offer virtual options. Each listing can explain service format, availability, and fit.",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "items",
        label: "Objections",
        type: "array-items",
        itemSchema: [
          { key: "concern", label: "Concern", type: "text", placeholder: "What they worry about" },
          {
            key: "response",
            label: "Response",
            type: "textarea",
            placeholder: "Reassuring answer",
          },
        ],
      },
    ],
  },
  {
    type: "before-after",
    label: "Before & After",
    iconName: "ArrowRight",
    description: "Timeline-style milestones showing transformation or progress",
    category: "social-proof",
    defaultProps: {
      title: "Your Journey",
      subtitle: "",
      items: [
        {
          before: "Feeling isolated and misunderstood",
          after: "Connected with a professional who gets it",
          milestone: "Week 1",
        },
        {
          before: "Struggling to articulate cross-cultural grief",
          after: "Learning frameworks to process your experience",
          milestone: "Month 1",
        },
        {
          before: "Navigating identity confusion alone",
          after: "Building confidence in your multicultural identity",
          milestone: "Month 3",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "items",
        label: "Milestones",
        type: "array-items",
        itemSchema: [
          {
            key: "milestone",
            label: "Milestone Label",
            type: "text",
            placeholder: "e.g. Week 1, Step 1",
          },
          { key: "before", label: "Before", type: "text", placeholder: "Starting point" },
          { key: "after", label: "After", type: "text", placeholder: "Outcome" },
        ],
      },
    ],
  },
  {
    type: "trust-bar",
    label: "Trust Bar",
    iconName: "Shield",
    description: "Row of trust signals with icons and labels",
    category: "social-proof",
    defaultProps: {
      items: [
        { icon: "ShieldCheck", label: "Verified Professionals" },
        { icon: "Lock", label: "Secure & Confidential" },
        { icon: "Globe", label: "Global Network" },
        { icon: "Heart", label: "Platform-Approved Support" },
      ],
    },
    propDefs: [
      {
        key: "items",
        label: "Trust Signals",
        type: "array-items",
        itemSchema: [
          {
            key: "icon",
            label: "Icon (Lucide)",
            type: "text",
            placeholder: "e.g. ShieldCheck, Lock",
          },
          { key: "label", label: "Label", type: "text", placeholder: "Trust signal text" },
        ],
      },
    ],
  },
  {
    type: "press-mentions",
    label: "Press Mentions",
    iconName: "Newspaper",
    description: "Display media logos with optional links",
    category: "social-proof",
    defaultProps: {
      title: "As Seen In",
      items: [{ name: "Publication Name", logoUrl: "", link: "" }],
    },
    propDefs: [
      {
        key: "title",
        label: "Section Title",
        type: "text",
        placeholder: "e.g. As Seen In, Featured By",
      },
      {
        key: "items",
        label: "Press Items",
        type: "array-items",
        itemSchema: [
          { key: "name", label: "Publication Name", type: "text", placeholder: "e.g. CNN, Forbes" },
          { key: "logoUrl", label: "Logo Image", type: "image-url", placeholder: "Upload logo" },
          { key: "link", label: "Link (optional)", type: "url", placeholder: "https://..." },
        ],
      },
    ],
  },
  {
    type: "social-proof-stats",
    label: "Social Proof Stats",
    iconName: "TrendingUp",
    description: "Key statistics with values, labels, and optional disclaimer",
    category: "social-proof",
    defaultProps: {
      title: "",
      stats: [
        { value: "500+", label: "Professionals in Network" },
        { value: "40+", label: "Countries Represented" },
        { value: "10,000+", label: "Members Connected" },
      ],
      disclaimer: "",
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Optional heading" },
      {
        key: "stats",
        label: "Statistics",
        type: "array-items",
        itemSchema: [
          { key: "value", label: "Value", type: "text", placeholder: "e.g. 500+, 98%" },
          { key: "label", label: "Label", type: "text", placeholder: "What the stat represents" },
        ],
      },
      {
        key: "disclaimer",
        label: "Disclaimer",
        type: "text",
        placeholder: "Optional disclaimer text",
      },
    ],
  },
  {
    type: "gallery",
    label: "Gallery",
    iconName: "Images",
    description: "Reusable CMS photo gallery with display controls",
    category: "media",
    defaultProps: {
      galleryId: "",
      layout: "inherit",
      columnsDesktop: 3,
      columnsTablet: 2,
      columnsMobile: 1,
      spacing: "md",
      imageRatio: "4/3",
      cropMode: "cover",
      borderRadius: "md",
      hoverEffect: "zoom",
      maxImages: 0,
      transitionEffect: "none",
      arrowIconColor: "",
      arrowBackgroundColor: "",
      showTitle: true,
      showCaptions: true,
      lightbox: true,
    },
    propDefs: [
      { key: "galleryId", label: "Gallery", type: "gallery-select" },
      {
        key: "layout",
        label: "Layout Override",
        type: "select",
        options: [
          { label: "Use gallery default", value: "inherit" },
          { label: "Grid", value: "grid" },
          { label: "Masonry", value: "masonry" },
          { label: "Carousel", value: "carousel" },
          { label: "Slider", value: "slider" },
          { label: "Featured + thumbnails", value: "featured" },
        ],
      },
      { key: "columnsDesktop", label: "Desktop Columns", type: "number", min: 1, max: 6 },
      { key: "columnsTablet", label: "Tablet Columns", type: "number", min: 1, max: 4 },
      { key: "columnsMobile", label: "Mobile Columns", type: "number", min: 1, max: 2 },
      {
        key: "spacing",
        label: "Spacing",
        type: "select",
        options: [
          { label: "None", value: "none" },
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
      {
        key: "imageRatio",
        label: "Image Ratio",
        type: "select",
        options: [
          { label: "Natural", value: "auto" },
          { label: "Square", value: "1/1" },
          { label: "4:3", value: "4/3" },
          { label: "3:2", value: "3/2" },
          { label: "16:9", value: "16/9" },
        ],
      },
      {
        key: "cropMode",
        label: "Image Fit",
        type: "select",
        options: [
          { label: "Crop to fill", value: "cover" },
          { label: "Fit full image", value: "contain" },
        ],
      },
      {
        key: "borderRadius",
        label: "Corner Radius",
        type: "select",
        options: [
          { label: "None", value: "none" },
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
      {
        key: "hoverEffect",
        label: "Hover Effect",
        type: "select",
        options: [
          { label: "None", value: "none" },
          { label: "Zoom", value: "zoom" },
          { label: "Fade", value: "fade" },
        ],
      },
      { key: "maxImages", label: "Image Limit", type: "number", min: 0, max: 200 },
      {
        key: "transitionEffect",
        label: "Transition Effect",
        type: "select",
        options: [
          { label: "No transition effect", value: "none" },
          { label: "Fade", value: "fade" },
          { label: "Slide left/right", value: "slide" },
          { label: "Zoom", value: "zoom" },
        ],
      },
      { key: "arrowIconColor", label: "Arrow Color", type: "color", placeholder: "#ffffff" },
      {
        key: "arrowBackgroundColor",
        label: "Arrow Background",
        type: "color",
        placeholder: "#6b7280",
      },
      { key: "showTitle", label: "Show Title", type: "boolean" },
      { key: "showCaptions", label: "Show Captions", type: "boolean" },
      { key: "lightbox", label: "Lightbox", type: "boolean" },
    ],
  },
  {
    type: "image-grid",
    label: "Image Grid",
    iconName: "Grid3X3",
    description: "Multi-image grid with configurable columns",
    category: "media",
    defaultProps: {
      title: "",
      columns: "3",
      gap: "md",
      images: [],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Optional heading" },
      { key: "columns", label: "Columns", type: "select", options: COLUMNS_OPTIONS },
      { key: "gap", label: "Gap Size", type: "select", options: SPACING_OPTIONS },
      {
        key: "images",
        label: "Images",
        type: "array-items",
        itemSchema: [
          { key: "url", label: "Image", type: "image-url", placeholder: "Upload image" },
          { key: "alt", label: "Alt Text", type: "text", placeholder: "Image description" },
          { key: "caption", label: "Caption", type: "text", placeholder: "Optional caption" },
        ],
      },
    ],
  },
  {
    type: "slider",
    label: "Content Slider",
    iconName: "GalleryHorizontal",
    description: "Image or content slider with navigation controls",
    category: "media",
    defaultProps: {
      title: "",
      slides: [
        { imageUrl: "", heading: "Slide 1", description: "First slide description" },
        { imageUrl: "", heading: "Slide 2", description: "Second slide description" },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Optional heading" },
      {
        key: "slides",
        label: "Slides",
        type: "array-items",
        itemSchema: [
          { key: "imageUrl", label: "Image", type: "image-url", placeholder: "Upload slide image" },
          { key: "heading", label: "Heading", type: "text", placeholder: "Slide heading" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Slide description",
          },
        ],
      },
    ],
  },
  {
    type: "stats-bar",
    label: "Stats Bar",
    iconName: "BarChart3",
    description: "Horizontal row of stats with icons, values, and labels",
    category: "data",
    defaultProps: {
      items: [
        { icon: "Users", value: "1,000+", label: "Active Members" },
        { icon: "Globe", value: "45+", label: "Countries" },
        { icon: "Star", value: "4.9", label: "Average Rating" },
      ],
    },
    propDefs: [
      {
        key: "items",
        label: "Stats",
        type: "array-items",
        itemSchema: [
          { key: "icon", label: "Icon (Lucide)", type: "text", placeholder: "e.g. Users, Globe" },
          { key: "value", label: "Value", type: "text", placeholder: "e.g. 1,000+" },
          { key: "label", label: "Label", type: "text", placeholder: "Stat description" },
        ],
      },
    ],
  },
  {
    type: "icon-grid",
    label: "Icon Grid",
    iconName: "Grid2X2",
    description: "Icon + title cards in a configurable grid",
    category: "content",
    defaultProps: {
      title: "",
      subtitle: "",
      columns: "4",
      items: [
        { icon: "Globe", title: "International" },
        { icon: "Heart", title: "Compassionate" },
        { icon: "Users", title: "Community" },
        { icon: "ShieldCheck", title: "Trusted" },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Optional heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      { key: "columns", label: "Columns", type: "select", options: COLUMNS_EXTENDED_OPTIONS },
      {
        key: "items",
        label: "Items",
        type: "array-items",
        itemSchema: [
          { key: "icon", label: "Icon (Lucide)", type: "text", placeholder: "e.g. Globe, Heart" },
          { key: "title", label: "Title", type: "text", placeholder: "Item title" },
        ],
      },
    ],
  },
  {
    type: "benefit-stack",
    label: "Benefit Stack",
    iconName: "ListChecks",
    description: "Benefits list in a stack or timeline layout",
    category: "content",
    defaultProps: {
      title: "Benefits",
      subtitle: "",
      layout: "stack",
      items: [
        {
          icon: "CheckCircle",
          title: "Expert Guidance",
          description: "Work with professionals who specialize in cross-cultural challenges.",
        },
        {
          icon: "Globe",
          title: "Global Accessibility",
          description: "Find support no matter where you are in the world.",
        },
        {
          icon: "Heart",
          title: "Cultural Understanding",
          description: "Be understood without having to explain your background.",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      { key: "layout", label: "Layout", type: "select", options: BENEFIT_LAYOUT_OPTIONS },
      {
        key: "items",
        label: "Benefits",
        type: "array-items",
        itemSchema: [
          { key: "icon", label: "Icon (Lucide)", type: "text", placeholder: "e.g. CheckCircle" },
          { key: "title", label: "Title", type: "text", placeholder: "Benefit title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Benefit description",
          },
        ],
      },
    ],
  },
  {
    type: "science-explainer",
    label: "Science Explainer",
    iconName: "FlaskConical",
    description: "Evidence-based content with citations and sources",
    category: "content",
    defaultProps: {
      title: "The Research Behind Our Approach",
      body: "",
      citations: [{ text: "Core Platform Training Research Study, 2024", url: "" }],
    },
    propDefs: [
      { key: "title", label: "Title", type: "text", placeholder: "Section heading" },
      { key: "body", label: "Content", type: "richtext", placeholder: "Explain the evidence..." },
      {
        key: "citations",
        label: "Citations",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Citation Text", type: "text", placeholder: "Author, Year, Title" },
          { key: "url", label: "Link (optional)", type: "url", placeholder: "https://..." },
        ],
      },
    ],
  },
  {
    type: "safety-checklist",
    label: "Safety Checklist",
    iconName: "ClipboardCheck",
    description: "Required and optional items with disclaimer",
    category: "content",
    defaultProps: {
      title: "Safety & Quality Standards",
      disclaimer: "",
      items: [
        { text: "Licensed or credentialed professional", required: true },
        { text: "Cross-cultural training or experience", required: true },
        { text: "Background verification completed", required: true },
        { text: "Specialized in Core Platform-related challenges", required: false },
      ],
    },
    propDefs: [
      { key: "title", label: "Title", type: "text", placeholder: "Section heading" },
      {
        key: "disclaimer",
        label: "Disclaimer",
        type: "textarea",
        placeholder: "Optional legal disclaimer",
      },
      {
        key: "items",
        label: "Checklist Items",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Item Text", type: "text", placeholder: "Checklist item" },
          { key: "required", label: "Required?", type: "boolean" },
        ],
      },
    ],
  },
  {
    type: "guarantee-warranty",
    label: "Guarantee & Assurance",
    iconName: "BadgeCheck",
    description: "Guarantee points with a support CTA",
    category: "conversion",
    defaultProps: {
      title: "Our Commitment to You",
      subtitle: "",
      items: [
        { text: "Every professional is individually vetted and verified" },
        { text: "Your privacy and confidentiality are always protected" },
        { text: "Support team available if you need help finding the right match" },
      ],
      ctaText: "Contact Support",
      ctaLink: "/contact",
      ctaAction: "internal-link",
      ctaOpenInNewTab: false,
      ctaFormSlug: "contact-form",
      ctaModalTitle: "",
      ctaModalDescription: "",
    },
    propDefs: [
      { key: "title", label: "Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "items",
        label: "Guarantee Points",
        type: "array-items",
        itemSchema: [
          { key: "text", label: "Point", type: "text", placeholder: "Guarantee bullet point" },
        ],
      },
      { key: "ctaText", label: "CTA Button Text", type: "text", placeholder: "Button label" },
      {
        key: "ctaAction",
        label: "CTA Button Action",
        type: "select",
        options: BUTTON_ACTION_OPTIONS,
      },
      { key: "ctaLink", label: "CTA Link", type: "url", placeholder: "/contact" },
      { key: "ctaOpenInNewTab", label: "Open In New Tab", type: "boolean" },
      { key: "ctaFormSlug", label: "Assigned Form", type: "form-select" },
      {
        key: "ctaModalTitle",
        label: "Modal Title",
        type: "text",
        placeholder: "Optional modal title override",
      },
      {
        key: "ctaModalDescription",
        label: "Modal Description",
        type: "textarea",
        placeholder: "Optional modal description",
      },
    ],
  },
  {
    type: "delivery-setup",
    label: "Process Steps",
    iconName: "Workflow",
    description: "Step-by-step process with optional included items list",
    category: "content",
    defaultProps: {
      title: "How It Works",
      subtitle: "",
      steps: [
        {
          step: "1",
          title: "Browse the Directory",
          description: "Search by specialty, location, or language.",
        },
        {
          step: "2",
          title: "Review Profiles",
          description: "Read about their approach and qualifications.",
        },
        {
          step: "3",
          title: "Make Contact",
          description: "Reach out directly through their profile.",
        },
      ],
      includedItems: [],
    },
    propDefs: [
      { key: "title", label: "Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "steps",
        label: "Steps",
        type: "array-items",
        itemSchema: [
          { key: "step", label: "Step Number/Label", type: "text", placeholder: "e.g. 1, Step A" },
          { key: "title", label: "Title", type: "text", placeholder: "Step title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Step details",
          },
        ],
      },
      {
        key: "includedItems",
        label: "What's Included (optional)",
        type: "array-items",
        itemSchema: [{ key: "text", label: "Item", type: "text", placeholder: "Included item" }],
      },
    ],
  },
  {
    type: "recovery-use-cases",
    label: "Use Cases",
    iconName: "Users",
    description: "Persona-based messaging showing who this is for",
    category: "content",
    defaultProps: {
      title: "Who Is Core Platform For?",
      subtitle: "",
      personas: [
        {
          title: "Members",
          description: "People looking for trusted providers, resources, events, and next steps.",
          icon: "User",
        },
        {
          title: "Families",
          description:
            "Households looking for practical resources, trusted services, and community support.",
          icon: "Users",
        },
        {
          title: "Organizations",
          description:
            "Companies and schools supporting internationally mobile employees and students.",
          icon: "Building2",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "personas",
        label: "Personas",
        type: "array-items",
        itemSchema: [
          { key: "icon", label: "Icon (Lucide)", type: "text", placeholder: "e.g. User, Users" },
          {
            key: "title",
            label: "Persona Title",
            type: "text",
            placeholder: "e.g. Members",
          },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Who they are and what they need",
          },
        ],
      },
    ],
  },
  {
    type: "protocol-builder",
    label: "Protocol Builder",
    iconName: "ListOrdered",
    description: "Step-by-step protocols organized by experience level",
    category: "content",
    defaultProps: {
      title: "Getting Started Guide",
      subtitle: "",
      level: "beginner",
      steps: [
        { title: "Create Your Account", description: "Sign up for free and set your preferences." },
        {
          title: "Explore the Directory",
          description: "Use filters to find professionals matching your needs.",
        },
        {
          title: "Schedule a Session",
          description: "Contact a professional and book your first appointment.",
        },
      ],
    },
    propDefs: [
      { key: "title", label: "Title", type: "text", placeholder: "Protocol title" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Optional subtitle" },
      {
        key: "level",
        label: "Experience Level",
        type: "select",
        options: EXPERIENCE_LEVEL_OPTIONS,
      },
      {
        key: "steps",
        label: "Steps",
        type: "array-items",
        itemSchema: [
          { key: "title", label: "Step Title", type: "text", placeholder: "Step title" },
          {
            key: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Step details",
          },
        ],
      },
    ],
  },
];
