import type { BlockDef } from "./block-registry.shared";
import { COLUMNS_OPTIONS } from "./block-registry.shared";

export const BASE_DYNAMIC_BLOCK_TYPES: BlockDef[] = [
  {
    type: "team",
    label: "Team",
    iconName: "Users",
    description: "Selected team members with portraits, bio excerpts, and full biographies",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      title: "Meet Our Team",
      subtitle: "",
      memberIds: [],
      layout: "portraits",
      columns: "3",
      showRole: true,
      showExcerpt: true,
      excerptLength: 180,
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text" },
      { key: "subtitle", label: "Introduction", type: "textarea" },
      { key: "memberIds", label: "Team Members", type: "team-select" },
      {
        key: "layout",
        label: "Template",
        type: "select",
        options: [
          { label: "Portrait Grid", value: "portraits" },
          { label: "Bordered Cards", value: "cards" },
          { label: "Horizontal Profiles", value: "horizontal" },
        ],
      },
      {
        key: "columns",
        label: "Grid Columns (portrait and card layouts)",
        type: "select",
        options: COLUMNS_OPTIONS,
      },
      { key: "showRole", label: "Show Role", type: "boolean" },
      { key: "showExcerpt", label: "Show Bio Excerpt", type: "boolean" },
      { key: "excerptLength", label: "Excerpt Length", type: "number", min: 40, max: 500 },
    ],
  },
  {
    type: "therapist-map",
    label: "Global Provider Map (Live Data)",
    iconName: "Map",
    description: "Interactive map showing live directory profiles",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      title: "Our Verified Providers Around the World",
      subtitle: "Click a pin to learn more about a verified provider near you",
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text", placeholder: "Section heading" },
      { key: "subtitle", label: "Subtitle", type: "textarea", placeholder: "Supporting text" },
    ],
  },
  {
    type: "blog-post-feed",
    label: "Blog Post Feed (Live)",
    iconName: "Rss",
    description: "Paginated blog post grid with search and category filters",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      postsPerPage: 9,
      gridColumns: "3",
      feedStyle: "pagination",
      showSearch: true,
      showCategoryFilter: true,
      showTagFilter: true,
      enableHoverMotion: true,
    },
    propDefs: [
      { key: "postsPerPage", label: "Posts Per Page", type: "number", min: 3, max: 24 },
      { key: "gridColumns", label: "Grid Columns", type: "select", options: COLUMNS_OPTIONS },
      {
        key: "feedStyle",
        label: "Archive Navigation",
        type: "select",
        options: [
          { label: "Pagination", value: "pagination" },
          { label: "Load More", value: "load-more" },
        ],
      },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showCategoryFilter", label: "Show Category Filter", type: "boolean" },
      { key: "showTagFilter", label: "Show Tag Filter", type: "boolean" },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "blog-featured-post",
    label: "Blog Featured Post (Live)",
    iconName: "FileText",
    description: "Large featured blog post card from latest published post",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      layout: "split",
      enableHoverMotion: true,
    },
    propDefs: [
      {
        key: "layout",
        label: "Featured Layout",
        type: "select",
        options: [
          { label: "Split Card", value: "split" },
          { label: "Stacked Card", value: "stacked" },
        ],
      },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "standard-blog-page",
    label: "Standard Blog Page (Live)",
    iconName: "Newspaper",
    description:
      "Combined blog archive with filters, featured post, and article feed in one reusable live block",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      layout: "split",
      postsPerPage: 9,
      gridColumns: "3",
      feedStyle: "pagination",
      showSearch: true,
      showCategoryFilter: true,
      showTagFilter: true,
      enableHoverMotion: true,
    },
    propDefs: [
      {
        key: "layout",
        label: "Featured Layout",
        type: "select",
        options: [
          { label: "Split Card", value: "split" },
          { label: "Stacked Card", value: "stacked" },
        ],
      },
      { key: "postsPerPage", label: "Posts Per Page", type: "number", min: 3, max: 24 },
      { key: "gridColumns", label: "Grid Columns", type: "select", options: COLUMNS_OPTIONS },
      {
        key: "feedStyle",
        label: "Archive Navigation",
        type: "select",
        options: [
          { label: "Pagination", value: "pagination" },
          { label: "Load More", value: "load-more" },
        ],
      },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showCategoryFilter", label: "Show Category Filter", type: "boolean" },
      { key: "showTagFilter", label: "Show Tag Filter", type: "boolean" },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "events-archive",
    label: "Events Archive (Live)",
    iconName: "CalendarDays",
    description:
      "Upcoming events listing with list/calendar views powered by the live events system",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Upcoming Events",
      subheading: "Share trainings, workshops, and community events with members and providers.",
      defaultView: "list",
      showViewToggle: true,
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Section heading" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      {
        key: "defaultView",
        label: "Default View",
        type: "select",
        options: [
          { label: "List", value: "list" },
          { label: "Calendar", value: "calendar" },
        ],
      },
      { key: "showViewToggle", label: "Show View Toggle", type: "boolean" },
    ],
  },
  {
    type: "video-archives",
    label: "Video Archives (Live)",
    iconName: "Video",
    description:
      "On-demand recording archive with search and purchase/access controls powered by live event recordings",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Video Archives",
      subheading: "Browse our collection of past trainings and webinars.",
      showSearch: true,
      showYearFilter: true,
      showAccessFilter: true,
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Section heading" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showYearFilter", label: "Show Year Filter", type: "boolean" },
      { key: "showAccessFilter", label: "Show Access Filter", type: "boolean" },
    ],
  },
  {
    type: "directory-browser",
    label: "Professional Directory (Live)",
    iconName: "Map",
    description:
      "Interactive directory with filters, results, and map powered by live directory data",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Find a Verified Provider",
      subheading:
        "Search verified providers by specialty, location, language, or service format, then explore results on the map.",
      showCategoryChips: true,
      showMap: true,
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Section heading" },
      {
        key: "subheading",
        label: "Subheading",
        type: "textarea",
        placeholder: "Optional supporting text",
      },
      { key: "showCategoryChips", label: "Show Category Chips", type: "boolean" },
      { key: "showMap", label: "Show Map", type: "boolean" },
    ],
  },
  {
    type: "career-listings",
    label: "Career Listings (Live)",
    iconName: "BriefcaseBusiness",
    description: "Searchable Career Center job board powered by live job listings",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      eyebrow: "Career Center",
      heading: "Open Positions",
      subheading: "Browse current opportunities and apply directly through the Career Center.",
    },
    propDefs: [
      { key: "eyebrow", label: "Eyebrow", type: "text", placeholder: "Career Center" },
      { key: "heading", label: "Heading", type: "text", placeholder: "Open Positions" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
    ],
  },
  {
    type: "portfolio-grid",
    label: "Portfolio Grid (Live)",
    iconName: "FolderKanban",
    description: "Searchable portfolio archive powered by live case-study projects",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      eyebrow: "Portfolio",
      heading: "Selected Work",
      subheading: "Explore case studies, projects, and outcomes from our portfolio.",
      layout: "grid",
      featuredOnly: false,
      excludeFeatured: false,
      showSearch: true,
      showIndustryFilter: true,
      showCategoryFilter: true,
      showLocationFilter: true,
      limit: 0,
    },
    propDefs: [
      { key: "eyebrow", label: "Eyebrow", type: "text", placeholder: "Portfolio" },
      { key: "heading", label: "Heading", type: "text", placeholder: "Selected Work" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      {
        key: "layout",
        label: "Layout",
        type: "select",
        options: [
          { label: "Grid", value: "grid" },
          { label: "List", value: "list" },
        ],
      },
      { key: "featuredOnly", label: "Featured Only", type: "boolean" },
      { key: "excludeFeatured", label: "Exclude Featured", type: "boolean" },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showIndustryFilter", label: "Show Industry Filter", type: "boolean" },
      { key: "showCategoryFilter", label: "Show Category Filter", type: "boolean" },
      { key: "showLocationFilter", label: "Show Location Filter", type: "boolean" },
      { key: "limit", label: "Item Limit", type: "number", min: 0, max: 48 },
    ],
  },
  {
    type: "contact-form",
    label: "Contact Form (Live)",
    iconName: "Mail",
    description: "Contact form with validation and submission — managed automatically",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {},
    propDefs: [],
  },
  {
    type: "form-embed",
    label: "Form Embed",
    iconName: "FileText",
    description: "Reusable form selected from the Forms library, embeddable in pages and widgets",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      formSlug: "contact-form",
    },
    propDefs: [{ key: "formSlug", label: "Assigned Form", type: "form-select" }],
  },
  {
    type: "join-hero",
    label: "Join Hero (Live)",
    iconName: "UserPlus",
    description: "Join page hero heading for verified providers — managed automatically",
    isDynamic: true,
    category: "hero",
    defaultProps: {
      heading: "Are you a verified provider?",
      accentHeading: "Join the Network!",
      headingColor: "",
      accentHeadingColor: "",
      subheading: "",
      subheadingColor: "",
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Main heading" },
      {
        key: "accentHeading",
        label: "Accent Heading",
        type: "text",
        placeholder: "Highlighted heading text",
      },
      { key: "headingColor", label: "Heading Color", type: "color", placeholder: "#ffffff" },
      {
        key: "accentHeadingColor",
        label: "Accent Heading Color",
        type: "color",
        placeholder: "#89cda1",
      },
      {
        key: "subheading",
        label: "Subheading",
        type: "textarea",
        placeholder: "Optional supporting text",
      },
      { key: "subheadingColor", label: "Subheading Color", type: "color", placeholder: "#ffffff" },
    ],
  },
  {
    type: "join-registration-form",
    label: "Join Hero + Application Status (Live)",
    iconName: "UserPlus",
    description:
      "Combined Join page hero, application status, and member login prompt — managed automatically",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Are you a verified provider?",
      accentHeading: "Join the Network!",
      headingColor: "",
      accentHeadingColor: "",
      subheading: "",
      subheadingColor: "",
      applicationStatusText: "Applications are currently open.",
      loginPromptPrefix: "If you're already a member click here to",
      loginLinkText: "Log in",
      loginPromptSuffix: "to your profile!",
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Main heading" },
      {
        key: "accentHeading",
        label: "Accent Heading",
        type: "text",
        placeholder: "Highlighted heading text",
      },
      { key: "headingColor", label: "Heading Color", type: "color", placeholder: "#ffffff" },
      {
        key: "accentHeadingColor",
        label: "Accent Heading Color",
        type: "color",
        placeholder: "#89cda1",
      },
      {
        key: "subheading",
        label: "Subheading",
        type: "textarea",
        placeholder: "Optional supporting text",
      },
      { key: "subheadingColor", label: "Subheading Color", type: "color", placeholder: "#ffffff" },
      {
        key: "applicationStatusText",
        label: "Button Status Text",
        type: "text",
        placeholder: "Applications are currently open.",
      },
      {
        key: "loginPromptPrefix",
        label: "Login Prompt Prefix",
        type: "text",
        placeholder: "If you're already a member click here to",
      },
      { key: "loginLinkText", label: "Login Link Text", type: "text", placeholder: "Log in" },
      {
        key: "loginPromptSuffix",
        label: "Login Prompt Suffix",
        type: "text",
        placeholder: "to your profile!",
      },
    ],
  },
];
