import type { BlockDef } from "./block-registry.shared";
import { COLUMNS_OPTIONS } from "./block-registry.shared";

export const BASE_DYNAMIC_BLOCK_TYPES: BlockDef[] = [
  {
    type: "team",
    label: "Team",
    iconName: "Users",
    description: "Selected team members with portraits, bio excerpts, and full biographies",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      title: "Meet Our Team",
      subtitle: "",
      memberIds: [],
      layout: "portraits",
      columns: "3",
      showRole: true,
      showExcerpt: true,
      excerptLength: 180,
    },
    propDefs: [
      { key: "title", label: "Section Title", type: "text" },
      { key: "subtitle", label: "Introduction", type: "textarea" },
      { key: "memberIds", label: "Team Members", type: "team-select" },
      {
        key: "layout",
        label: "Template",
        type: "select",
        options: [
          { label: "Portrait Grid", value: "portraits" },
          { label: "Bordered Cards", value: "cards" },
          { label: "Horizontal Profiles", value: "horizontal" },
        ],
      },
      {
        key: "columns",
        label: "Grid Columns (portrait and card layouts)",
        type: "select",
        options: COLUMNS_OPTIONS,
      },
      { key: "showRole", label: "Show Role", type: "boolean" },
      { key: "showExcerpt", label: "Show Bio Excerpt", type: "boolean" },
      { key: "excerptLength", label: "Excerpt Length", type: "number", min: 40, max: 500 },
    ],
  },
  {
    type: "blog-post-feed",
    label: "Blog Post Feed (Live)",
    iconName: "Rss",
    description: "Paginated blog post grid with search and category filters",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      postsPerPage: 9,
      gridColumns: "3",
      feedStyle: "pagination",
      showSearch: true,
      showCategoryFilter: true,
      showTagFilter: true,
      enableHoverMotion: true,
    },
    propDefs: [
      { key: "postsPerPage", label: "Posts Per Page", type: "number", min: 3, max: 24 },
      { key: "gridColumns", label: "Grid Columns", type: "select", options: COLUMNS_OPTIONS },
      {
        key: "feedStyle",
        label: "Archive Navigation",
        type: "select",
        options: [
          { label: "Pagination", value: "pagination" },
          { label: "Load More", value: "load-more" },
        ],
      },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showCategoryFilter", label: "Show Category Filter", type: "boolean" },
      { key: "showTagFilter", label: "Show Tag Filter", type: "boolean" },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "blog-featured-post",
    label: "Blog Featured Post (Live)",
    iconName: "FileText",
    description: "Large featured blog post card from latest published post",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      layout: "split",
      enableHoverMotion: true,
    },
    propDefs: [
      {
        key: "layout",
        label: "Featured Layout",
        type: "select",
        options: [
          { label: "Split Card", value: "split" },
          { label: "Stacked Card", value: "stacked" },
        ],
      },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "standard-blog-page",
    label: "Standard Blog Page (Live)",
    iconName: "Newspaper",
    description:
      "Combined blog archive with filters, featured post, and article feed in one reusable live block",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      layout: "split",
      postsPerPage: 9,
      gridColumns: "3",
      feedStyle: "pagination",
      showSearch: true,
      showCategoryFilter: true,
      showTagFilter: true,
      enableHoverMotion: true,
    },
    propDefs: [
      {
        key: "layout",
        label: "Featured Layout",
        type: "select",
        options: [
          { label: "Split Card", value: "split" },
          { label: "Stacked Card", value: "stacked" },
        ],
      },
      { key: "postsPerPage", label: "Posts Per Page", type: "number", min: 3, max: 24 },
      { key: "gridColumns", label: "Grid Columns", type: "select", options: COLUMNS_OPTIONS },
      {
        key: "feedStyle",
        label: "Archive Navigation",
        type: "select",
        options: [
          { label: "Pagination", value: "pagination" },
          { label: "Load More", value: "load-more" },
        ],
      },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showCategoryFilter", label: "Show Category Filter", type: "boolean" },
      { key: "showTagFilter", label: "Show Tag Filter", type: "boolean" },
      { key: "enableHoverMotion", label: "Enable Hover Motion", type: "boolean" },
    ],
  },
  {
    type: "events-archive",
    label: "Events Archive (Live)",
    iconName: "CalendarDays",
    description:
      "Upcoming events listing with list/calendar views powered by the live events system",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Upcoming Events",
      subheading: "Share trainings, workshops, and community events with members and providers.",
      defaultView: "list",
      showViewToggle: true,
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Section heading" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      {
        key: "defaultView",
        label: "Default View",
        type: "select",
        options: [
          { label: "List", value: "list" },
          { label: "Calendar", value: "calendar" },
        ],
      },
      { key: "showViewToggle", label: "Show View Toggle", type: "boolean" },
    ],
  },
  {
    type: "video-archives",
    label: "Video Archives (Live)",
    iconName: "Video",
    description:
      "On-demand recording archive with search and purchase/access controls powered by live event recordings",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      heading: "Video Archives",
      subheading: "Browse our collection of past trainings and webinars.",
      showSearch: true,
      showYearFilter: true,
      showAccessFilter: true,
    },
    propDefs: [
      { key: "heading", label: "Heading", type: "text", placeholder: "Section heading" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
      { key: "showSearch", label: "Show Search", type: "boolean" },
      { key: "showYearFilter", label: "Show Year Filter", type: "boolean" },
      { key: "showAccessFilter", label: "Show Access Filter", type: "boolean" },
    ],
  },
  {
    type: "career-listings",
    label: "Career Listings (Live)",
    iconName: "BriefcaseBusiness",
    description: "Searchable Career Center job board powered by live job listings",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      eyebrow: "Career Center",
      heading: "Open Positions",
      subheading: "Browse current opportunities and apply directly through the Career Center.",
    },
    propDefs: [
      { key: "eyebrow", label: "Eyebrow", type: "text", placeholder: "Career Center" },
      { key: "heading", label: "Heading", type: "text", placeholder: "Open Positions" },
      { key: "subheading", label: "Subheading", type: "textarea", placeholder: "Supporting text" },
    ],
  },
  {
    type: "contact-form",
    label: "Contact Form (Live)",
    iconName: "Mail",
    description: "Contact form with validation and submission — managed automatically",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {},
    propDefs: [],
  },
  {
    type: "form-embed",
    label: "Form Embed",
    iconName: "FileText",
    description: "Reusable form selected from the Forms library, embeddable in pages and widgets",
    isDynamic: true,
    category: "dynamic",
    defaultProps: {
      formSlug: "contact-form",
    },
    propDefs: [{ key: "formSlug", label: "Assigned Form", type: "form-select" }],
  },
];
